### ISSUE TITLE
CX Consultation Draft 6: CDR Logo

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#107]
### For review
The DSB CX team is seeking feedback and review of the use of the CDR logo within the ecosystem. Refer to [Consultation Draft 6 - CDR Logos.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/4385292/Consultation.Draft.6.-.CDR.Logos.pdf). 

_Please note the focus of this consultation is related to the CX considerations not technical standards at this stage._

### Context
The Australian Competition and Consumer Commission (ACCC) is looking to prioritise the use of the CDR logo for 2020 CDR implementations. 

Possible considerations include:
- The use of the CDR logo by accredited persons/accredited data recipients (ADRs) in connection with requests for consent to collect and use CDR data.
- The use of the CDR logo by data holders (DHs) in connection with requests to authorise the disclosure of CDR data.
- Licence terms to accompany the use of the CDR logo.

The ACCC is considering how the standards might require the use of the CDR logo.

Version 1.2.0 of the Consumer Experience (CX) Guidelines contain non-mandatory guidelines on CDR logo use as follows:
- ADR guidelines on p.37-39 stating ADRs ‘SHOULD use CDR branding provided by the ACCC to facilitate consistency, familiarity, and trust in the CDR ecosystem.’
- A DH guideline on p.78 stating DHs ‘SHOULD show the ACCC provided CDR branding…’ in the context of the authorisation flow.

This consultation is being conducted to obtain feedback on:
1. The changing of existing items on CDR Logos from CX Guidelines (a SHOULD) to CX Standards (a MUST);
2. Where else in the Consent Model and CDR ecosystem the CDR logo could be applied;
3. Whether such inclusions should be classed as guidelines or standards;
4. The time required for successful implementation of the options in this paper, and any other options raised for consideration.

Feedback posted in this thread will be considered as part of the CX consultation. Feedback can also be provided via the [CX Consultation Page](https://consumerdatastandards.org.au/workinggroups/consumer-experience/consultations-cx-workstream/).

**Feedback for this paper is planned to close on 9th April 2020.**

**Comment by Susan-CDR** [comment]
Suncorp would like clarity if the ADR details (name and ID) must always be displayed alongside the CDR logo.  This is how it has been displayed in the examples, but it is unclear if this is a requirement or not.  It would be a consistent customer experience if the CDR logo was displayed throughout the consent flow where the customer is taking an action in both the ADR and DH spaces. This supports the consumer to make the decision/action by associating the ‘trust mark’ to support them in making decisions about sharing their data. With regards to requirements for the displaying the CDR logo outside of the consent flow, these should be classed as guidelines rather than standards, due to the many ways that notifications, consumer dashboards and joint account management services could be implemented.

**Comment by commbankoss** [comment]
Commonwealth Bank's feedback to the decision proposal is attached here: 
[CBA Response to April 2020 CX Consultation CDR Logos_CBA.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/4454306/CBA.Response.to.April.2020.CX.Consultation.CDR.Logos_CBA.pdf)

**Comment by NationalAustraliaBank** [comment]
NAB agrees if a logo were to be provided, participants of the CDR must use it. This would provide clear expectations for consumers to look for it, and will build trust in the framework.

**Further possibilities for guidelines to use this logo:**
- Educational pages and FAQs about CDR on participants' websites.
- API documentation sites, both for the CDS and Data holders as way of identifying which APIs are specific to the Consumer Data Standards.

**Proposed commencement date**
November 20 is a reasonable time frame. In order to implement, participants would need:
- logos in different aspect ratios. A horizontal logo and another that's more square would allow usage that may help on smaller screens;
- a logo in a high resolution, or vector format should be provided in the mean time for the purposes of design and development;
- defined requirements for sizes;
- any messaging required in alternative text for accessibility.

**CDR Logo use by ADRs and DHs**
The CDR logo is a way to establish trust with an ADR, and should be used appropriately in that context. NAB agrees with the proposals outlined for the ADR consent experience. To create a strong link between ADRs and the CDR within the authorisation DH experience, we think it should be used in the following ways:
- In the authorisation flow, we recommend that the requirement is simply 'DHs MUST use the CDR Logo in the authorisation flow in relation to the ADR requesting data.' 
- We should also be consistent for dashboards. 'DHs MUST use the CDR Logo on consumer dashboards in relation to the sharing arrangements with an ADR.'
- The CDR logo should not be included in the authentication steps as a 'MUST'. A consumer isn't authenticating into the CDR, they're authenticating into a DH brand.
- Requiring logos in notifications as a 'MUST' is problematic, as different notification methods won't have that option available. This is should be a guideline.

**Comment by WestpacOpenBanking** [comment]
Westpac supports the use of the CDR logo by data holders and data recipients for the purposes of establishing consistency and familiarity in the CDR ecosystem. We remark that the value of the logo from a trust point of view is more complex - customers may become more suspicious if they see a third party logo whilst authenticating with their bank and malicious third parties may attempt to use any logo to create a false sense of trust.

Westpac is not currently supportive of changing the CX guidelines from a SHOULD to a MUST for data holders at this time. Short term, this is because there is already a very significant amount of work ahead in the consent space required for November timeframes. This includes the introduction of a joint account management service, closed accounts, concurrent consent and any new CX requirements. Longer term we think that, upon investigation, there may be contexts, perhaps related to accessibility or unusual device types where it it will make sense to omit the logo.

**Comment by CDR-API-Stream** [comment]
Thanks everyone for all your feedback and participation. The feedback period has now closed. The DSB will review the responses and will provide additional commentary here.

**Comment by CDR-CX-Stream** [comment]
Thank you to everyone for your contributions. This issue depends on rules changes so any final proposals will be delayed so that new rules can be consulted on.

**Comment by CDR-CX-Stream** [comment]
For noting: AGL provided a response to this decision proposal within the consultation window. Inline with the DSB's open consultation process it has been posted here for visibility.

[AGL Submission to DSB - CX CDR Logo - 9 April.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/4491192/AGL.Submission.to.DSB.-.CX.CDR.Logo.-.9.April.pdf)

**Comment by CDR-CX-Stream** [comment]
**For noting:** ME Bank provided a response to this decision proposal within the consultation window. In line with the DSB's open consultation process it has been linked to here for visibility:

https://consumerdatastandards.org.au/workinggroups/consumer-experience/consultations-cx-workstream/consultation-draft-6/

**Comment by CDR-CX-Stream** [comment]
**For noting:** Origin provided a response to this decision proposal within the consultation window. In line with the DSB's open consultation process it has been shared here for visibility:

[CDR Logo - CX Consultation 6 - Origin comments.docx](https://github.com/ConsumerDataStandardsAustralia/standards/files/4501164/CDR.Logo.-.CX.Consultation.6.-.Origin.comments.docx)

**Comment by CDR-CX-Stream** [comment]
This issue will be closed before any decisions are proposed. As these proposals depend on policy considerations any further recommendations will only be suggested after inter-agency consultation has also been conducted.
