### ISSUE TITLE
CX guidelines v1.3.0 Feedback

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards#123]
Commonwealth Bank has the following feedback on version 1.3.0 of the CX Guidelines:

**Concurrent consent**
The technical standards currently specify that _"until November 2020, data recipients MUST actively revoke previously supplied refresh tokens, immediately after receiving the tokens for a newly established consent"_. The standards also explicitly call out that concurrent consent must NOT be implemented until November 2020. However, the CX Guidelines/Standards do not explicitly call out the same obligation

- Commonwealth Bank requests that the CX Standards be aligned to the CDS standards the explicitly call out the obligation to NOT implement concurrent consent until November, for example: _"Until November 2020, Data recipients MUST NOT create concurrent consents."_

**Unavailable accounts in the authorisation Flow**
The CX Standards was amended with the addition of the following (page 16): _"Data holders are not permitted to show unavailable joint accounts as joint accounts need to be elected via a joint account management service before they are permitted to appear in the authorisation flow (See CDR Rules: Schedule 3, 4.1(1); 4.2; 4.3(3); and CDR Rule 4.24)_".

- Commonwealth Bank seeks to clarify whether this will be revisited for November timelines once the feedback on [Consultation Draft #5](https://github.com/ConsumerDataStandardsAustralia/standards/issues/106) for joint accounts is considered.

**CDR Logo & Accreditation number in authorisation flow**
Commonwealth Bank supports the removal of the CDR logo and accreditation ID as a requirement in the authorisation flow, given these are not yet available.

Page 112 of the CX Guidelines V1.3.0 currently states _"Data holders SHOULD provide instructions for how consumers can verify a data recipient’s accreditation via an ACCC-provided URL pending the ACCC making this functionality available"_.

- Can Data61 confirm that this requirement remains relevant given the accreditation ID has been removed, and the ACCC have not provided an update on when this URL would be made available for ADRs and DHs to integrate into their experience? Commonwealth Bank recommend this requirement is also removed from the CX guidelines, and reintroduced once the URL, CDR logo, and Accreditation ID are made available.

**Comment by CDR-CX-Stream** [comment]
Hi @commbankoss,

Thank you for this feedback.

**Concurrent consent**
This will be incorporated into the next release.

**Unavailable accounts**
The intention is to revisit this item but the rules would need to be amended to allow it. As such, this is a rules question first and any related CX Standards will be delayed until rules amendments can be considered/made.

**CDR Logo and Accreditation number**
These items have been referred to at a high level noting that it is an optional item and can only be implemented when the ACCC provides the functionality. If this functionality is not available in the next release we will consider removing it.
(NB the cited guideline refers to the dashboard rather than the authorisation flow.)

**Comment by WestpacOpenBanking** [comment]
Westpac welcomes the opportunity to comment on the low-fidelity reauthorisation prototypes and reauthorisation.
We would not support the flow as presented in the low fidelity prototype. Customers should be fully informed of the scope of any reauthorisation, at the data holder. This ensures that:
* The details of the authorisation as actually requested (as opposed to displayed at the ADR) can be verified by the customer.
* Customers are not surprised by an immediate a reauthorisation after authentication without expectation or warning.

Streamlining of reauthorisation may be possible in two ways:

* Removing scope selection steps on the data recipient side. 
* Not including an account (re)-selection step during the data holder reauthorisation steps. This was omitted in the low fidelity prototype. Consideration should be given as to when this should or should not occur. The recommended behaviour may depend on whether the reauthorisation request includes a different set of data clusters to the original authorisation or not as well as data recipient preference. Customer testing should be performed with regard to the desirability of this option and consideration should be given to the additional friction induced.

We would recommend setting guidelines rather than hard requirements for data recipients and data holders in relation to these. For example it may be recommended that account selection would occur whenever new data clusters are recommended. 

In addition to the above, we also have the following additional recommendations:

* Consideration should be given as to whether the CX guidelines should set requirements around the content, timing and frequency of re-authorisation notifications sent to customers. We suggest in particular that recommendations to omit ‘sensitive’ content from notifications are given.
* Should customers be able to opt out from re-authorisation notifications?
* Should there be guidelines to prevent excessive re-authorisation notifications?
* Should it be possible to select additional data clusters beyond the original authorisation during re-authorisation?

**Comment by CDR-API-Stream** [comment]
After internal discussion the DSB would like to request that general feedback on CX be posted on the standards maintenance repository.  The CX team will be monitoring the issue tracker there.

This issue will be closed.  If there is more feedback to be provided on this topic please create a maintenance issue and reference this issue for continuity.
