### ISSUE TITLE
Noting Paper 136 - November 2020 Consent Transition Guidance

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#136]
To provide guidance for Data Recipients and Data Holders as the ecosystem moves to adopt concurrent consent, a noting paper has been produced to describe how the ecosystem as a whole can transition from the current single extant consent model towards the standards defined with November 2020 obligations including concurrent consent, consent revocation and the adoption of the Pushed Authorisation Request (PAR) standard.

This noting paper takes into consideration issues raised through the ACDS Standards Maintenance process as well as changes proposed in [Decision Proposal #135](https://github.com/ConsumerDataStandardsAustralia/standards/issues/135).

[Noting Paper 136 - November 2020 Consent Transition-v2.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/5038633/Noting.Paper.136.-.November.2020.Consent.Transition-v2.pdf)

This document has been updated to fix formatting of the scenario example table, cross referenced DP 135 recommendations and change history is included in the appendix. No changes have been made to the substance of the document.

--

The original noting paper is available below:
[Noting Paper 136 - November 2020 Consent Transition.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/4998683/Noting.Paper.136.-.November.2020.Consent.Transition.pdf)

**Comment by CDR-API-Stream** [comment]
Minor fixes to this document has been updated to correct formatting of the scenario example table, cross referenced DP 135 recommendations and change history is included in the appendix. No changes have been made to the substance of the document.

**Comment by spikejump** [comment]
@CDR-API-Stream thank you for putting together the transition paper.  We've got some clarification questions after reading the paper.

**Assumption**
CDS spec v1.4 will be the version where all participants work with for Nov'20

**Question 1**
Given technically, there's enough interoperability detection between participants for supportability of various functional features, is it correct to say that on Nov 1 2020, an ADR can continue to operation in v1.2 with a DH that's supporting (all or parts) of v1.4?

For example, ADR initiates a consent flow via /authorise endpoint - no PAR.  DH returns tokens, including `cdr_arrangement_id`.  ADR continues to revoke consent via DH's existing Token Revocation endpoint.  DH revokes consent using ADR's existing Token Revocation endpoint (due to no published 'recipient_base_uri').

**Question 2**
Is there a deprecation date for DH to support v1.2?  Is this governed in anyway?

**Question 3**
Is it correct that the only thing the DH MAY not support on Nov 1 is PAR?  e.g. it is not possible that a DH will support Concurrent Consent but does not support CDR Arrangement Revocation endpoint?

**Question 4**
Is there a mandatory date for ADRs to support CDR Arrangement Revocation endpoint or for that matter any of v1.4?

**Question 5**
There are a couple of references in the Noting Paper to DH calling DRs CDR Arrangement Revocation endpoint and receiving a 422 error.  This is not possible when ADRs do not yet support CDR Arrangement Revocation endpoint.  In which case, perhaps the DH should rely on whether ADRs have `recipient_base_uri `in their SSA to determine whether to call the CDR Arrangement Revocation endpoint or the existing Token Revocation endpoint.

**Comment by CDR-API-Stream** [comment]
Thank you to everyone who's put forward views and proposals. Consultation has been closed and feedback will be considered.
