### ISSUE TITLE
Decision Proposal 140 - Gateway Authentication and Authorisation Mechanisms

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#140]
Below is a decision proposal document for consultation on authentication, authorisation and authorisation management mechanisms for designated gateways with specific reference to the Energy sector.
[Decision Proposal 140 - Gateway Authentication and Authorisation Mechanisms.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/5562717/Decision.Proposal.140.-.Gateway.Authentication.and.Authorisation.Mechanisms.pdf)

The ACCC has requested that the DSB conduct a technical consultation on the implementation options and implications on authentication, authorisation and authorisation management using a designated gateway to inform the rules decision making process and privacy impact assessment process.

This consultation is focussed on technical and customer experience concerns only and will not seek to address any policy or rules issues.

This consultation will be open for feedback until the 11th of December.  Please note that a workshop to discuss the subject matter of this consultation will be held on the 24th November.

**Comment by CDR-CX-Stream** [comment]
The [workshop on gateway authentication and authorisation](https://consumerdatastandards.gov.au/event/dsb-energy-draft-standards-with-authorisation-authentication-workshop/) was run on 24th November and well attended by representatives from the energy and financial sectors - including both DHs and ADRs - along with other industry representatives and government agencies.

Participants were walked through the draft payload standards and the potential CX of the gateway authentication, authorisation, and dashboard options outlined in DP140. The agenda included a Q&A for each item, and participants provided feedback, preferences, and considerations for the flow options outlined in DP140.

The workshop artefacts and participant feedback/outputs have been [made public on this Miro board](https://miro.com/app/board/o9J_lf7ioDU=/).

The community may find the flows and comments on this Miro board useful when considering their submissions to DP140, which may include feedback/queries on the flows themselves.

**Comment by Kat-AGL** [comment]
**Posting on behalf of AGL Energy regarding assumption of AEMO as consents master**

First, thank you for hosting the recent workshop on this decision proposal, these types of forums are incredibly useful and it generated a lot of interesting discussion.

Decision Proposal 140 has been prepared based on a number of assumptions that are identified as constraining the data standards body in the options presented. In particular, the DSB states that the gateway masters consents data - “one of the primary functions of the gateway will be to ensure that requests to obtain CDR data are appropriately authorised. To do this the gateway must have access to the detail of the authorised consents that are used to make these requests. **This means that the gateway must be the master** (ie. the primary holder) of the set of authorised consents."

We encourage further testing of this assumption, and consider there is sufficient flexibility within the legislation, designation instrument and the ACCC rules making powers to allow for a change in this assumption. While we agree that AEMO must be a holder of consents (e.g. a trusted store/cache) we do not believe that this then equates to requiring AEMO to be the master of consent. Altering this assumption would open the possibility for other authorisation and authentication options under the standards. 

In particular, we note that neither the CDR legislation nor the ACCC energy rules framework paper contemplated the concept of a master of authorised consents. While the ACCC framework proposed that AEMO might hold some CDR data as a gateway, it was not to be the sole data holder and there was no specific commentary on who should hold consent data. We also note that the ACCC stated in this framework that the process of authentication and authorisation occurs in accordance with any requirements in the CDR energy rules. The gateway’s role in this process is to be determined’ (p.18). 

The CDR legislation is inherently flexible in the rules which govern the gateway as well as the function and responsibilities of the gateway. It provides discretion as to what rules can be made regarding the method by which consumers provide valid consents (e.g. 56BC(2)) and further discretion that rules ‘may’ be made under 56BG(1)(b) for a designated gateway to be involved in that consent process. 

The energy designation instrument does not require any consents arrangement, noting by example under the Explanatory Memorandum that this could be done by the CDR Rules. 

At a principle level, a core policy objective of the CDR is to give consumers better access to, and control over, their data. The idea of AEMO as a ‘master’ of consent authorisation (rather than an ADR having that responsibility) is arguably inconsistent with this objective, as practically consumers will see retailers such as AGL as the ‘holders’ of their data (and accordingly the appropriate holders of consumers’ consent regarding what is done with that data). 

If the current assumption is maintained, it will not allow transparency for consumers on how their data is being managed and accessed, limit future options for cross-sectoral CDR development, optionality for consumer channel choice, and create significant inefficiencies and security risks contrary to the technical standard outcome principles of ensuring APIs are secure, use open standards and are simple. 

AGL therefore recommends the DSB amend the current assumption that the “gateway masters consent data” and modify decision proposal 140 to support a decentralised approach to consent mastering. Our preferred approach consent management would be performed by the energy retailer and gateway would act as a consent trusted store and user of the consent data.

Any potential risks and inefficiencies resulting from decentralising consent mastering can be addressed through learnings from Open Banking, leveraging established integration patterns and security protocols.

We note that in Open Banking several options exist for banks who prefer to outsource or delegate their CDR obligation to 3rd parties. We anticipate our preferred federated approach to consent mastering would encourage these 3rd parties to participate in the Energy CDR regime.

**Comment by johnAEMO** [comment]
**AEMO Response to DSB Decision Proposal 140** 

Thank you for the opportunity to contribute to the above discussion.

As the designated Gateway for the implementation of the CDR in energy, AEMO sees the Gateway as an opportunity to support the industry in implementing the CDR. The Gateway will ensure that the costs associated with the implementation and operation of CDR for energy across all retailers are allocated as efficiently as possible, to minimise the costs that end up being passed to consumers.  

AEMO understands the concept of ‘Master of Consent’ as described in the assumptions but would rather the concept be titled in terms of Authorisation, as that is the step it is intended to relate to. With Consent being the overall process which includes the steps of the consumer giving Consent to the ADR, Authentication being secured by the current retailer and Authorisation given by the consumer to the Data Holder, rewording the assumption would remove any confusion.  

To that end AEMO is willing to perform the role of Authorisation if required by the CDR Rules and/or standards.  As a function of the CDR, and in keeping with our submission to the ACCC Rules Framework Consultation, AEMO does not envisage a need to manage information that could be deemed personal in performing this role. As such, AEMO is of the opinion that the roles of conducting authentication and the offering of a consumer-facing dashboard are best performed by the consumer’s current retailer.  Further AEMO is not willing to be exposed to the end consumer or to retain any PII/consumer information.  Our rationale for this is explained in our submission to the ACCC Rules Framework Consultation.

As an additional benefit of the Gateway performing authorisation, AEMO holds the historical chain of retailers responsible for each NMI and in an industry where there is significant consumer churn, holding this at the Gateway allows the direction of data requests to the applicable Data Holder(s).  While a consumer may be reasonably aware of their current retailer (and nominates it at the ADR), their previous retailers and sequence are less likely to be recalled.  Depending on the position determined on access to historical data, there will be benefit to consumers if this data is leveraged at the time of Authorisation, collating this into a single screen and not require multiple separate authorisations.

**Comment by AthenaJay** [comment]
Hi,

Would it be possible to seek an extension on the deadline today to provide comments?

Athena(OAIC)

**Comment by jsaxon-red** [comment]
Red and Lumo will have strict regulatory obligations under the CDR to maintain the integrity of our customers' data and by implication, their privacy and safety.
More importantly, our customers expect this from us so we face reputational risks if we do not meet this expectation.

Therefore, we are concerned about gateway technical implementations that don't minimise the risk of data breach as far as possible.

In our view, the selection of a gateway for the transfer of sensitive customer information does not necessarily mean that it must the consent master, or that the details of said consents would be opaque to the retailer, as has been proposed.

We do not believe the applied technical implementation impacts were understood and assessed in any detail throughout the Treasury and ACCC's consultation processes on how the CDR should apply to the energy sector.

Moreover, we do not expect the energy CDR rules will prescribe this detail. Therefore, we welcome the opportunity to work with both the ACCC and DSB to develop a practical solution that also meets the overarching policy intent.

**Comment by PratibhaOrigin** [comment]
Thank you for the opportunity to provide feedback.  This response follows the authorisation and authentication workshop held on 24 November 2020.  Origin representatives attended this workshop from both a policy and technical perspective. 

### ****AEMO** role as a “gateway”** 
•	Origin has previously supported AEMO’s role as a gateway on the assumption that the gateway would function as a conduit for CDR data and not store data. This is noted in our policy submission to the ACCC’s “Data Access Models for Energy” in March 2019.
•	It was further supported given the understanding, at the time, that:
1. a consumer would be requesting data from multiple data holders (ie retailers), however this will not be the case as the use case scenarios are limited to current ‘active’ accounts; and
2. it would leverage current AEMO B2B systems to allow the exchange of data.  Rather new systems and protocols are being developed for the exchange of data.

•	The workshop on 24 November 2020 was the first time that industry has discussed AEMO’s role as a gateway from a technical solution perspective with clarity being provided on the implications of the existence of the gateway.
DSB Proposed Assumption 
•	The gateway masters consent data assumption– we understand that it is proposed that the gateway be a single point of trust and be the master for holding a customer’s consent. This is not supported by Origin.  

**Policy concerns**

- From a policy perspective, this assumption has not been raised nor discussed.  It was always assumed that the consent requirements would follow industry practices whereby the party that obtained the consent would hold the record of the consent. We raise consumer concerns that if a customer gave consent to Origin for the purpose of authentication, but then the customers consent is held by a party to which the customer has no relationship nor knowledge of – we believe this will raise consumer concerns on how their data is being managed and accessed.
- It is noted that the energy legislative framework does not prescribe the functions and responsibilities of the gateway (ie AEMO).  The energy designation instrument does not mention consent functions of the gateway and rather designates the gateway for the purposes of certain data sets and provides that the disclosure of data will be in accordance with the CDR Rules. It is noted that the CDR legislation provides discretion in terms of ‘valid consent’ but is not yet defined in the energy sector.  We believe that this provides the ACCC discretion on how to define the consent Rules. 

**System security and privacy concerns**

- We believe that this assumption poses a privacy and security risk in that a party (ie AEMO) that has no direct contact with a customer is the party that is proposed to hold the truth as to the type and form of consent provided.  AEMO will not be privy to how the consent was obtained nor the customer details of who the person was that provided the consent.  As discussed in the workshop and previous meetings with the ACCC, the role of the gateway should be to perform the authorisation check to ensure requests being provided to data holders, via the gateway, is from a trusted or authorised party.  
- Further, we are not comfortable with ‘outsourcing’ the authorisation/customer consent to the gateway given the risks that data not relevant to a customer is shared with a customer who was not entitled to receive the data.  For example:

1. If the ADR has requested the data for last X months, how does AEMO know if there has not been a change of retailer during this period? 
2. Similarly, on the flip side, if an ADR has requested the data for x months, how does AEMO validate the same customer was there for last x months? 
3. Also, related to above the clarity on how to handle requests around historical data for a customer if there have been change in the retailers/customers during the requested period.

There is always a risk that there is a time lapse to updating move in and move out customers or there is a change to customer details on an account. Retailers are the only ones to hold this information. AEMO does not hold any customer details on an account and cannot determine who a customer is at a site or premises.  

- Any transfer of data increases the risk of data transfer errors.  Consent is a fundamental element of the framework and will be a critical element to the operation of the framework – this will be particularly true if a ‘write’ function is introduced.  This risk should be minimised by keeping the consent with the primary source of consent. 

- This technical option could interfere with the scheme objective of inter-operability.  The assumption does not appear to accommodate the inclusion of other products or services offered by an energy retailer.  For example, an energy retailer offering energy + telecommunications.  Would AEMO hold the energy consent, but then a separate consent is held with the retailer for other products on the account?  We fail to see how AEMO would be the ‘consent master’ for a telecommunication consent.

- Origin is supportive of flows compliant with OAUTH2 and would be keen to get information on how we would remain OAUTH2 compliant with the gateway model. Origin prefers data holders remaining the source of truth and responsible party for authorisation of all customer data requests due to above mentioned security concerns.

•	**Liability** 

- The suggested model puts AEMO as consent master which raises the question of accountability and liability. In an event of data and consent related breaches, is the liability sit with AEMO? Hence, the clear breach reporting and accountability should be called out in the rules. 
- Based on the above, it is Origin’s view that consent management should be decentralised (ie party that receives the consent, holds the consent) and AEMO should act as the pipeline for the transfer of consented data. We believe that the risks associated with the DSB’s proposed assumption are significant and this level of risk is not supported in the energy market.
- The above views also raise concerns as to the proposed role of the gateway.  We request further discussion and clarity on the roles and responsibilities of a gateway.  Particularly, 
- Is a gateway needed if it is not intended that data will be sourced from multiple retailers? We understand that data requests will be limited to current active accounts.  What are the additional tasks/services a gateway would be performing? As proposed above, Origin’s preference is that data holders maintain their own authorization log master. 
- Technical complications – there are additional technical complications with regards to consumer dashboards, time delays of passing data through various parties and the additional privacy and system security concerns of information flows through multiple parties. 
- Other sectors – As CDR is going to be implemented across various industries/sectors, the role of gateway should be clearly defined and established so that it is applicable across various sectors where there is a need for gateway.

### Authentication
Origin prefers - Option 1 – Retailer redirect

1.	As retailers already share a relationship with the customer, this option would help customer build confidence in the CDR process when they see a familiar screen, branding and tone of the retailer.
2.	IFrame option would be clunky and challenging to use in native app. 
3.	Security preference – This option is preferred from a security standpoint as it is compliant to the OAUTH2 specifications and allows us to reuse this for other use-cases. This option also provides the user with assurance of the authenticity of the login page i.e. that this is indeed the retailer they are supplying their credentials to.
4.	Although option 1 and option 2 are similar in terms of implementation cost, we need to take into consideration any future changes to the authentication/authorization process, the additional testing with AEMO and management.  This is likely to make option 2 more expensive in terms of ongoing and maintenance cost.
5.	Joint account holder/authorised contacts scenarios – With CDR future changes proposing to include the joint account holder/authorised contact scenarios, it will be even more complicated to perform additional authentication with the joint account holders under option 2. 
6.	Gateway supporting multiple holders raises a question how identity validation will be implemented across different holders – Is the request always going to current retailer? In case of multiple data holders (change retailer or switch in progress scenario), how will authentication request be triggered.

### Authorisation
Origin prefers - Option 1 – Extension of authentication
Origin would prefer authorization process and log to sit with data holders(retailers).

1.	Same reasons as above for authentication 1-6.
2.	With option 1, at least the number of re-directions will be comparatively less.
3.	Authentication and authorisation can be performed in one interaction and smooth flow with CX again will help build confidence in CDR process.
4.	Option 2 will impact the data holders which serve more than just electricity service. With CDR being implemented across various industries in future, option 2 will result in restricted solution which may not be easily scalable across other sectors.

### Dashboard

Origin at this stage doesn’t prefer Option 1 and 2 because of concerns raised above. 
We would request more clarity around - Option 3 – Retailer presents using gateway APIs

Please confirm how the option 3 will work – 
1)	Model 1
 
![image](https://user-images.githubusercontent.com/72119982/101857983-d21df080-3bbc-11eb-8955-f7c733cae8bb.png)


2)	Model 2 
 
![image](https://user-images.githubusercontent.com/72119982/101857998-d77b3b00-3bbc-11eb-9a45-7f7e0d3f2fc2.png)

3)	Model 3
 
![image](https://user-images.githubusercontent.com/72119982/101858015-de09b280-3bbc-11eb-97fb-320c33fbd801.png)


Origin’s recommendation is for the dashboard and authorisation logs to sit with data holders considering below points - 
1.	As retailer already shares a relationship with the customer, this option would help customer build confidence in the CDR process when they see a familiar screen, branding, and tone of the retailer.
2.	IFrame option would be clunky and challenging to use in native app.
3.	 ‘The gateway masters consent data’ -  gateway as a single point of trust and consent master is a security risk because of reasons suggested above. 
4.	Considering the future of CDR with other sectors like gas, telecommunications included, having the dashboard at data holder level (ie retailer) would serve as single stop shop for customers to update the authorisations for multiple industries and it serves as good customer experience. 
5.	In this paper/proposal, the only dashboard mentioned is at gateway/data holder side. But there will also be a dashboard to provide/update/revoke authorisation at an ADR side. 
o	This means whenever there is an update to an authorised consent via ADR dashboard, it needs to flow through AEMO as gateway and update the data holder authorization records accordingly. 
o	And similarly, if the authorization is updated at data holder dashboard , does it need to flow through AEMO as gateway again and update the ADR records accordingly?
o	Does the authorization data need to be in sync for all 3 parties at all times – ADR, data holder and AEMO (gateway).

Overall, we suggest the technical implementation impacts of suggested gateway models should be explored and tested further with customer data privacy and security in consideration.

Cheers!
Pratibha

**Comment by SelenaLiuEA** [comment]
Good afternoon, 

The posts above highlight the need for more discussion on issues around authentication and authorisation, and the roles of the gateway and dataholders. 

We agree with AEMO's clarification that the master of consent assumption, really should be referring to the master of authentication.

**Master of authentication assumption** 

EnergyAustralia is open to further discussing the issues around this assumption and potential alternatives. Our views below are subject to reaching a position on the Master of authentication assumption, and could but are not expected to change.

**Options in DSB proposal**  

We support Option 1 across authentication and authorisation (“Retailer redirect”) and Option 3 for the dashboard (“Retailer presents using APIs”). These options involve the retailer hosting and designing the solutions. We agree with the benefits of these options raised in the DSB’s paper. In particular, adopting Option 1 across all functions will reduce any friction that arises from redirection between different parties and allow for consistency of design. 
 
“Retailer direct” and “Retailer present” options also align more closely with the banking sector CDR. We do not consider that the presence of a gateway in the energy sector should change the general policy direction of data holders being primarily responsible for authorisation etc. Maintaining as much consistency across sectors will allow for scale efficiencies to be achieved by third party IT providers seeking to enter and provide data holders solutions for authorisation etc. 
 
In addition, EA notes further reasons as to why a “Gateway presents” model for authorisation and the dashboard functionality is problematic. AEMO does not have a customer facing relationship.
 
Only a retailer has the infrastructure in place to field questions/complaints regarding authorisation/withdrawing authorisation, where these are received outside a digital journey through assisted channels e.g. call centre. There are therefore efficiencies if the Retailer presents the authorisation and the dashboard to the customer as they will be able to deal with questions/complaints more efficiently. E.g. a customer may call a retailer’s call centre and ask how they can withdraw their authorisation, the retailer consultant can direct that customer to the digital dashboard and even potentially check the authorisation status in the dashboard. 
 
It also makes sense to have the authorisation and dashboard reside with the retailer, given the retailer will be performing authentication and could be receiving customer questions and complaints about authentication already. i.e. all possible customer facing transactions via assisted channels should reside with the retailer.  This is also particularly important if the CDR were to ever take a non-digital form in the future and providing assisted channels would be unavoidable. A “Gateway presents” model would undermine any possibility of full non-digital engagement in the future – should the CDR ever take that direction.
 
As is very clear from the above comments – there are many issues the DSB will need to work through to ensure that authentication and authorisation is current (and reflects changes to account holder etc); and that authentication and authorisation is appropriate (e.g. does not raise any family violence risks). We look forward to further consultation on these issues.

Regards, 
Selena

**Comment by commbankoss** [comment]
Commonwealth Bank suggests to use the authentication and authorization model used in banking for all sectors i.e. authentication, authorisation, access and consent management performed by Data Holders (also referred to as retailers in the energy sector), Data Recipients communicate directly with Data Holders. The implementation can be simplified for new industry participants by further aligning with industry standards, eliminating the need for custom CDR specific work.

Commonwealth Bank is opposed to the introduction of the Gateway, as this will unnecessarily complicate the ecosystem, lead to confusing consumer experience, and create integration and security challenges. Introduction of a new separate security profile for Gateway-to-Retailer communications is unnecessary and opens the ecosystem to additional threats and vulnerabilities. If this profile is introduced, it should be thoroughly designed and reviewed before being mandated. Centralized consent management doesn't deliver the intended simplification benefits, while complicating end to end setup, authorization establishment, and enforcement.

From Data Recipient perspective, it is preferred to maintain the same authentication, authorisation, and API consumption models for all industries/sectors.

**Comment by CDR-API-Stream** [comment]
Thanks everyone for the contributions via the workshop and via this consultation thread.  The results of the consultation will be documented and communicated to the ACCC as requested.  As the final position on many of the issues covered in this consultation will first be dealt with in the rules the DSB will not be making a recommendation or publishing a final decision in response to this consultation.
