### ISSUE TITLE
Noting Paper 141 - GitHub Promotion Process

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#141]
This item is provided to communicate a noting paper related to the process by which changes to the standards are authored by DSB team members prior to approval by the Chair and subsequent publishing.

The noting paper is attached below:
[Noting Paper - GitHub Promotion Process.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/5581172/Noting.Paper.-.GitHub.Promotion.Process.pdf)

This process will be used to author the changes for v1.6.0 of the standards.  Suggestions for amendment or improvement are welcome.

**Comment by perlboy** [comment]
What was wrong with git-flow? 

I don't understand why the DSB is so intent on creating new ways of managing technical change. Are you creating a technical standard for open data sharing or trying to reinvent technical project management? I feel whoever authored this noting paper needs to go read [The Cathederal and the Bazaar](http://www.catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/ar01s10.html). 

This sentence seems particularly relevant considering by the time this change process is implemented any new comer is going to be totally confused:
> When you start community-building, what you need to be able to present is a plausible promise. Your program doesn't have to work particularly well. It can be crude, buggy, incomplete, and poorly documented. What it must not fail to do is (a) run, and (b) convince potential co-developers that it can be evolved into something really neat in the foreseeable future.

**Comment by JamesMBligh** [comment]
Nothing is or was wrong with git-flow, it just didn't fully match our internal workflow in the DSB or the way we consult with the community.  At the end of the day we are building a standard governed by legislative and regulatory processes and, although we are using GitHub, we aren't building open source.

We thought this process would allow the community to track the various sources of change into the standards better and get early insight into the authored changes.  I hope it does.

For the record, I have read the The Cathedral and the Bazaar but it was a while ago.  I read it when it was first published because I am that old.

**Comment by perlboy** [comment]
> Nothing is or was wrong with git-flow, it just didn't fully match our internal workflow in the DSB or the way we consult with the community. 

It also means that **all** existing tooling for commonly solved problems is now broken and essentially the DSB is requiring literally hundreds of software engineers across the ecosystem to deliberately seek to learn the "DSB way" in accordance with the way <5 people have decided.

> At the end of the day we are building a standard governed by legislative and regulatory processes and, although we are using GitHub, we aren't building open source.
> We thought this process would allow the community to track the various sources of change into the standards better and get early insight into the authored changes. I hope it does.

Exposing changes in a staged way rather than releasing them out of the blue as swathes of diff on a Sunday does allow earlier insight. Spraying a variety of changes across a virtual wackamole of branches simply appears to be some misguided attempt at trying to not comply with the rest of the software development universe.

It's clear to me this isn't a consultation so I guess do whatever you like. Enjoy your merge hell because it's coming.

Meanwhile, we'll be over on [dsb-standards](https://github.com/bizaio/dsb-standards) releasing things in boring and easy to understand ways for the newbies.

**Comment by biza-io** [comment]
Biza.io does not believe the reasons articulated by the DSB are sufficient grounds to diverge from accepted engineering practices and that the assertion the proposed method is _"is loosely based on GitFlow"_ is a misrepresentation. We request that the DSB consult with impacted parties (ie. all implementers) to ensure the release method adopted by the DSB is conducive to efficient integration into engineering norms.

**Comment by CDR-API-Stream** [comment]
Thanks for the feedback Biza.  This thread is consultation.  For the authoring process of the standards, however, it is entirely unclear how anyone outside of the DSB is impacted as only the DSB will be operating under this process.  The purpose of the process described is to give greater visibility to the community of changes to standards as they are being authored.

Also, we do not believe it is a misrepresentation to say the process is loosely based on GitFlow.

**Comment by CDR-API-Stream** [comment]
The period for providing feedback on for this noting paper is complete so the issue is now being closed.

**Comment by CDR-API-Stream** [comment]
The following feedback was received by NAB prior to the closing date via ZenDesk and has been posted with permission:

> NAB welcomes the proposed changes in this noting paper.
> As per our feedback in Github # 135, it has been difficult to assess the impact of a Decision Proposal’s net effect to the standards (ie overlaying multiple decision proposals to understand which parts of the current standards will be changed/replaced and which parts will remain).
> 
> We believe this proposed approach will assist in removing this ambiguity and also reduce the risk of inadvertent transcription errors between decision proposals to the standards themselves. 
>
> Our only feedback for consideration by the DSB relates to the number of repositories – we believe these could be simplified into a single repo with multiple branches (instead of authoring in staging and then promoting into standards).
