### ISSUE TITLE
Noting Paper 142 -  CDR data quality issues summary

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#142]
This item is provided to communicate and seek feedback on a noting paper related to CDR data quality issues.

The noting paper is attached below:
<add attachment here>

Feedback is now open on this noting paper. Feedback is planned to be closed on 28 February 2021.
[Noting Paper - CDR data quality issues summary.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/5620383/Noting.Paper.-.CDR.data.quality.issues.summary.pdf)

**Comment by commbankoss** [comment]
Commonwealth Bank requests an extension to 28/02 to respond on this issue.

**Comment by NationalAustraliaBank** [comment]
NAB also requests for an extension until 28/02 to respond to this noting paper.

**Comment by CDR-API-Stream** [comment]
This thread is being extended until the 28th of February as requested by participants

**Comment by commbankoss** [comment]
Commonwealth Bank's feedback on Noting Papers 142 and 143 (conventions as a whole) is as follows:

The proposed conventions are a way of suggesting interpretation of the standards in a non-binding manner. These add another source for consultation and information for participants to use for standards interpretation. We advise against adopting conventions as an interpretation mechanism.

The same functionality can be addressed by including MAY and SHOULD type statements in the standards, maintaining centralisation of standards interpretation to the standards themselves, and consultation to the existing channels (i.e. GitHub).

Additionally, supplying more examples in the standards, and creating a tool to validate against the standards, would also assist in improving data quality.

**Comment by NationalAustraliaBank** [comment]
The noting paper assumes the data quality issues are always due to non-compliant DH implementations, but it is observed that in many cases the standards are not prescriptive and are open to participant's interpretation by choice. DH invests considerable amount of time and effort to interpret the rules & standards as they are defined and ensure their implementations are compliant with the CDR. It is not clear from the paper how the non-compliance will be identified and who will adjudicate if there is a disagreement on the interpretation of the standards.

Conventions do not ensure the data quality issues are fixed as they are not enforceable, which is contrary to the goal of this noting paper. Also, Conventions cannot be used to make a DH update the implementation retrospectively as they have no compliance obligation, hence we recommend an update to the standard in these scenarios; including the cases where the standards are ambiguous or overly permissive which are resulting in data quality issues. 

Currently, the CDR Support portal is only used to submit requests for clarification to data standards body and the participants are not expected to monitor this portal for issues being assigned to them. We recommend a separate consultation for defining the operational process on how these issues can be reported, assigned and tracked to resolution.

**Comment by CDR-API-Stream** [comment]
Thank you for the feedback.  This issue is now being closed
