### ISSUE TITLE
Decision Proposal 153 - Technical Standards Changes to Accommodate V2 Rules

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#153]
This decision proposal contains a review of the amendments to the CDR rules published on the 23rd of December 2020 to identify changes to the technical CDR standards.  This includes the API standards, high level standards and the information security profile.  This decision proposal does not cover consumer experience standards or guidelines which will be addressed separately.

The proposal is attached below:
[Decision Proposal 153 - Technical Standards Changes to Accommodate V2 Rules.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/5846875/Decision.Proposal.153.-.Technical.Standards.Changes.to.Accommodate.V2.Rules.pdf)

Currently, the DSB have not identified any material changes to the standards that are required by the amended rules.  This proposal gives more detail and is presented for consultation so that the community can highlight any required changes that we may have missed.

Feedback is now open on this proposal. This thread will remain open until February 19th 2021.

**Comment by anzbankau** [comment]
Overall we are broadly comfortable with the approach to D153 being no change to technical standards as result of rule changes, although we do expect some changes to the registry design. We note that it may be beneficial to include an assessment of whether the API standards cater for sharing of non-individuals to confirm there is no impact to the schemas.

We also note the close correlation between completion of D153 and D157 to allow data holders to have full clarity on the build impacts for November. There are areas of related CX standards which need to be clarified in D157 to complete the build approach (for example disclosure of additional information within the dashboard). We feel the proposed schedule for D157 is too long to allow for an effective build path to November currently being full completion of CX standards by May 2021. This feedback will also be provided within D157.

Some specific clarifications we would like for the technical standards relating to complex business accounts are:
- Who will be the 'subject' in the business context? Is it the user or the organisation?
  - The standards state: _Subject Identifier. A locally unique and never reassigned identifier within the Issuer for the End-User, which is intended to be consumed by the Client_
  - This should presumably still be the individual user - not the business.
  - This means userinfo information shared is all about the user, not the organisation/customer.
- How would replacement consents work (i.e. specifying an existing CDR arrangement ID)? Presumably only the initiating user could perform this for an existing authorisation.
- How should the Get Customer response be populated? Should the user information be returned in the 'agent' fields?
- If the above is based on the user who authorised then will the isOwned flag always be ‘no’ for complex business accounts?
- Given the rules state that the authorisation would outlive the user working at the organisation - how will this interact with any of the above?

**Comment by perlboy** [comment]
We have similar questions to @anzbankau, particularly with regards to interaction behaviours associated with business accounts. We would also like to understand if the behaviour alters between business accounts associated with sole traders and limited liability companies. Finally we would like to understand the lifecycle of consents on business accounts in the event of a sale of the business or, in the sole trader situation, the customer base.

We would appreciate an answer on these questions as soon as possible as we have an active installation occurring involving a significant number of business accounts.

**Comment by WestpacOpenBanking** [comment]
At a high-level Westpac agrees that the current technical standards should accommodate changes required for Rules 2.0. However, we would like to note we are in the process of completing our detailed analysis of the new Rules which may uncover the need for new/modified technical standards.

The rules indicate a November 1 compliance date for Direct to customer data access and have explicit references to the data standards. Although direct to customer data access is not a new addition to the new version of the rules, we ask DSB to clarify what new standards are intended in relation to this item and when they might be finalized.

Based on our preliminary analysis of the proposal, we have the following comments and questions:

* Our understanding is that data holders will not be required to make any changes in relation separated consent types, for example consents to use. We would appreciate if this could be explicitly confirmed. 
* Our understanding is that data holders will not be required display information about cases where one data recipient is collecting data on behalf of another data recipient. We would appreciate if this could be explicitly confirmed.
* The data standards body may wish to consider if it would be appropriate to set security requirements in the case of transfer of CDR data between accredited persons. We note the importance of securing all transfers of CDR data.

We note that any identified CX changes or registry changes may result in changes to the technical standards and refer to our response in relation to [noting paper 157](https://github.com/ConsumerDataStandardsAustralia/standards/issues/157).

**Comment by CDR-API-Stream** [comment]
Hi @anzbankau, thanks for the feedback. To address your specific technical questions, please see responses below.

> 1. Who will be the 'subject' in the business context? Is it the user or the organisation?

It would be the nominated representative of the organisation (in other words, the end user that established consent who has delegated authority to share data on behalf of the consumer – in this case, the organisation).

>   * The standards state: Subject Identifier. A locally unique and never reassigned identifier within the Issuer for the End-User, which is intended to be consumed by the Client
>   * This should presumably still be the individual user - not the business.
>   * This means userinfo information shared is all about the user, not the organisation/customer.

It would be the details of the agent of the organisation acting as the nominated representative. Name would be the agent name, given_name would be the agentFirstName, and family_name would be the agentLastName, updated_at would be the last time those details were updated.

> 2. How would replacement consents work (i.e. specifying an existing CDR arrangement ID)? Presumably only the initiating user could perform this for an existing authorisation.

The DSB is working with the ACCC to draft a response providing guidance here. CDR Arrangement IDs are bound to the subject, so they are not transferable across different “sub” values.

> 3. How should the Get Customer response be populated? Should the user information be returned in the 'agent' fields?

The organisation details will be returned in Get Customer. The user’s information would be returned in the agent details that’s correct. agentRole should be used a free form text field to be populated by the Data Holder and is meant to indicate the capacity that the individual is operating when sharing the data of the organisation.  Whatever role or function that is currently shown in your digital channels would be appropriate. A reasonable default value would be fine if such a field is not routinely captured.

> 4. If the above is based on the user who authorised then will the isOwned flag always be ‘no’ for complex business accounts?

That may depend on the relationship of the nominated rep and the account. For instance, a director who owns the account and is the nominated rep may have the isOwned flag == true, whereas an accountant employed by the business but does not own the account would have isOwned == false.

> 5. Given the rules state that the authorisation would outlive the user working at the organisation - how will this interact with any of the above?

The DSB is working with the ACCC to draft a response providing guidance here.

**Comment by SelenaLiuEA** [comment]
Hi All, 

Two questions from EnergyAustralia: 

- **Changes to who may share CDR data** – The DSB is proposing no change. But we query whether there needs to be another option other than the “isOwner” flag for Secondary Users. isOwner means a "Flag indicating that the customer associated with the authorisation is an owner of the account. Does not indicate sole ownership, however. If not present then 'true' is assumed". 

- **Required and voluntary product data disclosures** – The DSB says that the rule amendments do not directly imply any changes to the technical standards. The changes to the rules for Version 2 specify a new 2.4(2A) which provides that “If the data holder discloses any requested voluntary product data to the requester, it must do so: 
(a) through its product data request service; and
(b) in accordance with the data standards".

While the DSB’s position might be appropriate, we question whether any of the data standards should change to recognise what could be quite different voluntary data. 

Agree with Westpac's comment above - The data standards body may wish to consider if it would be appropriate to set security requirements in the case of transfer of CDR data between accredited person

Thanks 
Selena

**Comment by CDR-API-Stream** [comment]
In response to the feedback from @WestpacOpenBanking:

> The rules indicate a November 1 compliance date for Direct to customer data access and have explicit references to the data standards. Although direct to customer data access is not a new addition to the new version of the rules, we ask DSB to clarify what new standards are intended in relation to this item and when they might be finalized.

The DSB is expecting to consult, in tandem with the ACCC, on Direct to Consumer this quarter.  This will be via a dedicated decision proposal.

> Based on our preliminary analysis of the proposal, we have the following comments and questions:
> 
> * Our understanding is that data holders will not be required to make any changes in relation separated consent types, for example consents to use. We would appreciate if this could be explicitly confirmed.

That is aligned with the understanding of the DSB.  Consents to use and disclose will need to be expressed by the ADR when they seek user consent but these are to be managed on the ADR side.  The communications between ADR and DH is primarily concerned with consent to collect.

> * Our understanding is that data holders will not be required display information about cases where one data recipient is collecting data on behalf of another data recipient. We would appreciate if this could be explicitly confirmed.

This would be a CX concern and should be addressed by the CX team under https://github.com/ConsumerDataStandardsAustralia/standards/issues/157.  From a technical perspective the existence of ADR to ADR transfers would not be communicated to the DH via the consent authorisation process.  If anything is to be displayed it would be via meta data obtained from the register.

> * The data standards body may wish to consider if it would be appropriate to set security requirements in the case of transfer of CDR data between accredited persons. We note the importance of securing all transfers of CDR data.

Currently the position of the DSB is that we will not be creating standards for this transfers noting that the rules already create obligations for ensuring these transfers are secure.  This position may change in the future as the regime evolves and a clear need for standardisation arises.  This is similar to our current position on transfers between data holders under the more standard white labelling scenarios and between data holders and outsource service providers.

> We note that any identified CX changes or registry changes may result in changes to the technical standards and refer to our response in relation to [noting paper 157](https://github.com/ConsumerDataStandardsAustralia/standards/issues/157).

We do not yet see any changes to the technical standards arising from the CX changes.  The DSB is, of course, working as a team to ensure if any need arises then it is dealt with across the standards.

**Comment by CDR-API-Stream** [comment]
In response to the feedback from @SelenaLiuEA :
> * **Changes to who may share CDR data** – The DSB is proposing no change. But we query whether there needs to be another option other than the “isOwner” flag for Secondary Users. isOwner means a "Flag indicating that the customer associated with the authorisation is an owner of the account. Does not indicate sole ownership, however. If not present then 'true' is assumed".

The *isOwner* flag was included as the result of extensive consultation.  It was a balanced position between the need for ADRs to understand the relationship of the sharing customer with the accounts being shared and the need to protect the information of third parties that are not involved in the consent process.

The *isOwner* flag was deliberately chosen so as not to inadvertently convey information about third party relationships to ADRs while still expressing the customer relationship to the account.

For the purpose of this consultation the DSB has not identified any rule changes that would alter this position but if there is a specific issue in the v2 rules that you believe needs to be addressed please let us know.

> * **Required and voluntary product data disclosures** – The DSB says that the rule amendments do not directly imply any changes to the technical standards. The changes to the rules for Version 2 specify a new 2.4(2A) which provides that “If the data holder discloses any requested voluntary product data to the requester, it must do so:
>   (a) through its product data request service; and
>   (b) in accordance with the data standards".
> While the DSB’s position might be appropriate, we question whether any of the data standards should change to recognise what could be quite different voluntary data.

The DSB does not believe this raises any changes to the standards as the mechanisms for extending the standards for voluntary data are already accommodated under the [Extensibility Section](https://consumerdatastandardsaustralia.github.io/standards/#extensibility) of the standards.

> Agree with Westpac's comment above - The data standards body may wish to consider if it would be appropriate to set security requirements in the case of transfer of CDR data between accredited person

Please see the response to Westpac posted above.

**Comment by NationalAustraliaBank** [comment]
NAB would like to provide the following feedback / questions: 

**Direct Consumer data requests -**
- The compliance date for “Part 3—Consumer data requests made by eligible CDR consumers” is 1 November 2021.   NAB would like to clarify whether data standards are going to be published in relation to this item and when are these expected to be finalised?  If no data standards are going to be published, then NAB would like to point out that there is potential for consumers to receive different results across the various DHs which may impact the customer experience.

**ADR to ADR consents / data transfers -** 
- NAB does not agree with the following statements in the Decision Proposal paper : 
> _The rules allow for the transfer of CDR data between ADRs as long as appropriate consent is obtained. While the rules define obligations that ADRs must meet in order to make these transfers there is no requirement for the DSB to make standards for this transfer. As these transfers will be for a broad range of uses and there is no requirement for standardisation of these transfers (as there is for DH to ADR transfer) there is currently no requirement to define a binding standard for these transfers._
- In line with Division 8.14 of the Rules (“Data Standards that must be made”), NAB believes the data standards ought to be extended to cover all data sharing consent types and the disclosure of CDR data between ADRs to ADRs.  
- NAB believes it is important to have visibility of where our customer's data goes in order to take proactive steps to protect customers against fraud and identity theft in the event of a data breach and that the absence of technical standards regulating the transfer of data between ADRs introduces an unacceptable risk to the security and privacy of consumer data within the CDR ecosystem. 
- In the event of a data breach, DH's will have limited visibility of the data exposure outside the direct DH-to-ADR scope, thereby limiting our ability to take proactive action to protect our customers against fraud and identity theft in those scenarios.  Furthermore, we believe that consistent technical standards to manage the flow of data across the entire ecosystem (including ADR to ADR data transfers) is necessary to promote consumer confidence that their data is safe. 



**Transition -** 
- Our understanding from the Rules is that existing consents will transition to “consent to collect” ie. DHs are not required to make any changes as a result of the introduction of the new consent types. Is this correct?  


**Ongoing -** 
- For new consents going forward, is the intention that DHs will only track of “consent to collect”?


**Secondary users -** 
- We understand that, when a secondary user authorises "consent to collect" with an ADR, the account holder has visibility of that consent (via the DH dashboard / notifications).  However, in the scenario where the secondary user authorises disclosure consent  (ie. for data to be shared from ADR to another ADR), how will the account owner gain visibility of where their data has gone? NAB believes that in this scenario, the account holder should have visibility of where their data has gone and be able to revoke / stop that sharing.
- Should the secondary user be allowed to authorise **customer scopes**?  Reason being, as per the Rules, we understand that the secondary user applies in the context of **an account** ("a person is a secondary user for an account with a data holder in a particular designated sector if the person has account privileges **in relation to the account"**). We interpret this to mean that the secondary user is only authorised to share account data but not the customer’s personal data.  Is this correct?
- Assuming a secondary user is allowed to authorise customer scopes: If a secondary user instruction applies to a joint account and a consent is authorised by that secondary user on that joint account, whose customer details should be returned in the Get Customer / Get Customer Details API’s?  Both Joint account holders' customer details?  If yes, then there may be a need to change the Get Customer API schema definition in the standards to facilitate this. 
- Please clarify how the “IsOwned” parameter is expected to work in the scenario where the secondary user authorises "consent to collect' data.


**Nominated representatives –** 
- If a consent is authorised by a nominated representative on behalf of a Non-Individual or Partnership customer, whose customer details should be returned in the Get Customer / Get Customer Details API’s? 
- Are consents created by nominated representatives tied to the nominated representative's "role" or their User Id ?
- What should happen to the consents created by the nominated representative when that person leaves the organization? Should their consents expire?  Should DH continue sharing data for those consents?
- If an organisation has multiple nominated representatives (or if a nominated representative is replaced as per the above point), is there an expectation that the existing consent can be amended by **any** of those nominated representatives or just the nominated representative who provided the consent? 
- We would like to clarify whether the following reference in V1.6.0 of the standards needs to be amended as a result of the above scenarios:  _"If the cdr_arrangement_id is not related to the consumer being authenticated it MUST be rejected."_


**Consent amendment –** 
- The following reference from V1.6.0 of the standards implies that a new consent is created when an Arrangement ID is provided in the request object.  NAB believes this should be updated to reflect the 'amend consent' functionality introduced by new Rules: _"If a data recipient provides the cdr_arrangement_id claim in the request object to the data holder's PAR End Point, the data holder MUST revoke any existing tokens related to the arrangement once the **new consent** is successfully established and a new set of tokens has been provided to the data recipient"_



**Get API's -**
-  NAB would like to highlight that our detailed assessment of the Get API’s is in progress (eg. Get Customer, Get Accounts, Get Account Details; Get Balances, Get Transactions etc).  As a result, we do not have any specific feedback on the impact to the API schemas for non-individual / partnership customer types / secondary users at this point.

 **Temporary Restrictions -** 
- NAB would like to clarify whether any Registry standards changes are required in relation to Part 5 - 5.33 Temporary restriction on use of the Register?

**Comment by SelenaLiuEA** [comment]
Hi again,

Regarding: 

> The _isOwner_ flag was included as the result of extensive consultation. It was a balanced position between the need for ADRs to understand the relationship of the sharing customer with the accounts being shared and the need to protect the information of third parties that are not involved in the consent process.
> 
> The _isOwner_ flag was deliberately chosen so as not to inadvertently convey information about third party relationships to ADRs while still expressing the customer relationship to the account.
> 
> For the purpose of this consultation the DSB has not identified any rule changes that would alter this position but if there is a specific issue in the v2 rules that you believe needs to be addressed please let us know.

Can you please clarify how a secondary user would be reflected by using or not using the isOwner flag? 

Thanks 
Selena

**Comment by PratibhaOrigin** [comment]
### Feedback from Origin Energy on DP-153

Origin has reviewed DP 153 together with the ACCC Explanatory statement of the rule changes. We agree with the DP that no technical changes are required to the standards because of the rule changes. From a security perspective, the changes relating to the Functions and Powers of the Accredited Registrar (changes adding 5.33 and 5.34) are welcome as they have the goal of maintaining the integrity and security of the register.

**Comment by commbankoss** [comment]
Commonwealth Bank has the following feedback on Decision Proposal 153:

1. **Data transfers between Accredited Persons (AP):** to protect consumers, transfers of consumer data in the CDR ecosystem must occur in a secure manner. Therefore, adequate security and data standards should be applied for data transfers between Aps, in a similar way as Standards are applied for transfers between DHs and ADRs. Failure to do so will introduce risk of ecosystem breach. Additionally, we strongly recommend an independent security review of the ecosystem be conducted given this significant change to the ecosystem.
2. **Further clarifications:** Commonwealth Bank requires further clarification and guidance on new scenarios and behaviours to progress build, specifically on various edge cases and non-happy paths, relating to: 
    1. Joint Accounts (including in-flow election edge cases)
    2. Non-individual and secondary users (for example, when a nominated representative is replaced by a new representative)
3. **Expanded Register Powers:** the amended Rules empower the Register to direct Data Holders to not respond to consumer data requests, and to direct an Accredited Person not to make consumer data requests. Commonwealth Bank recommends that the Register uses existing mechanisms to accomplish these outcomes, for example, Participant Status APIs and/ or transport certificate revocation.
**4. Implementation timelines:** in line with Commonwealth Bank’s feedback on previous consultations, we strongly recommend that participants are provided with a minimum of six months to implement clarifications and changes to the Standards, as any changes require designing, building and testing.

**Comment by CDR-API-Stream** [comment]
Thank you to everyone who's put forward feedback. Consultation has been closed and feedback will now be reviewed and considered.

**Comment by CDR-API-Stream** [comment]
In response to feedback from @SelenaLiuEA:

> Can you please clarify how a secondary user would be reflected by using or not using the isOwner flag?

A consenting customer who is a primary account holder (ie. an owner of the account) would have the `isOwner` flag set to true for that account.  A consenting customer who is has permission to view and share an account but is not a primary account holder (ie. **not** an owner of the account) would have the `isOwner` flag set to false.

Note that this treatment is specific to accounts in the banking sector and there is currently no corollary field in the energy standards where primary and secondary holders are being dealt with differently.

**Comment by CDR-API-Stream** [comment]
In response to feedback from @NationalAustraliaBank and @commbankoss:

**Direct Consumer data requests**

As per the [DSB Future Plan](https://github.com/ConsumerDataStandardsAustralia/future-plan/projects/1) it is the DSB's intention to consult on Direct To Consumer in tandem with the rules team this quarter.  That is independent on the rules changes covered by this consultation, however.


**ADR to ADR standards**
There is currently no obligation in the rules to create standards for ADR to ADR data transfer.  There is also no obligation to create standards for DH to DH transfer or OSP to DH transfer.  The DSB is open to creating standards for all of these situations if required by the rules but there does not currently appear to be a need.  Information security is able to be managed via the requirements of the accreditation process (which is analogous to the requirements for information security applied to the banks, which are not prescriptive) and there is no advantage for standardisation for point to point communications between two contracted entities.


**Consent to collect**
It is the understanding of the DSB that the current standards already fully define the lifecycle for consent to collect.  Consent to use or disclose is expected to be managed by the ADR without the DH being involved.  In this context, while there are now additional obligations regarding consent for ADRs it does not mean that a technical standards change is required.

In relation to specific feedback from NAB on secondary users, we believe there may be a misunderstanding.  There is no concept of a secondary user being able to affect a consent - only the association of an account to which they have rights to an existing authorised consent.

**Nominated representatives**
The questions included under this banner are not related to the v2 rules and have previously been addressed in the standards.  We would recommend these questions being raised via the support portal so clarifications can be provided to all participants.

**Consent amendment**
To clarify the current standards the `arrangement_id` was introduced to allow for an ongoing authorised consent to collect to exist beyond the lifecycle of the technical consent mechanism represented by a refresh token in the normative standards.  The terminology where the technical consent construct defined in OAuth should not be confused with the legal concept of `consent to collect` that it is a representation of.

**Implementation timelines**
As the DSB has not identified any technical standards changes arising from the changes to the rules the topic of implementation timeframes isn't applicable to this consultation.

**Register feedback**
Currently, the register standards are managed by the ACCC to questions related to register standards should be directed to their GitHub page.

**Further clarifications**
@commbankoss indicated that further clarification and guidance on some topics is needed.  It is suggested that these clarifications be raised as issues on the support portal so clarity can be provided.

**Comment by CDR-API-Stream** [comment]
This consultation will now be closed and marked as `No Decision Taken` to reflect that no changes to the standards will be recommended to the Data Standards Chair
