### ISSUE TITLE
Decision Proposal 155 - Enhanced Error Handling: Error Code Catalogue

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#155]
This decision captures the outcome of the Enhanced Error Handling consultation. The Data Standards Chair approved the changes to be made. The decision record is available here: [Decision 154-155-156 - Enhanced Error Handling - Summary of Changes To Be Made.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/6572983/Decision.154-155-156.-.Enhanced.Error.Handling.-.Summary.of.Changes.To.Be.Made.pdf)

These changes will be incorporated into release v1.10.0 of the Consumer Data Standards

---

This issue pertains to the consultation for Enhanced Error Handling.

Specifically, this decision proposal is seeking to address the list of standardised error codes and HTTP status codes for error handling across the CDR ecosystem.

The consultation draft Decision Proposal has been attached below:
[Decision Proposal 155 - Enhanced Error Handling - CDR Error Code Catalogue.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/5852891/Decision.Proposal.155.-.Enhanced.Error.Handling.-.CDR.Error.Code.Catalogue.pdf)

Feedback is now open for this proposal. Feedback is planned to be closed on 19th February 2021.

**Comment by CDR-API-Stream** [comment]
Related Decision Proposals open for feedback:
- https://github.com/ConsumerDataStandardsAustralia/standards/issues/154
- https://github.com/ConsumerDataStandardsAustralia/standards/issues/156

**Comment by spikejump** [comment]
Intuit welcomes the opportunity to provide feedback on DP155.

**Unavailable vs Invalid Accounts**
We are requesting an enhancement to the definition of Invalid Accounts from what’s defined in the DP.  Currently, it says,

> An invalid account implies it is not associated with consent or is permanently unavailable.
> No subsequent request for the account will be successful.

However, invalid accounts should only refer to accounts that are **permanently** unavailable.  It should not include accounts that are not associated with consents that may be temporarily unavailable.

As an example,

- Day 1: account A1 may be consented to an ADR.
- Day 2: A1 is removed from the consent due to business/security reasons or via dashboard provided by DH by the customer.  A1 is _no longer associated_ with the consent but this may be **temporary**.  A1 at this time is an Unavailable account.
- Day 3: After business/security concerns are reviewed and the concerns removed, A1 is back to be associated with the consent.
On the other hand, if it was concluded that A1 can't be accessed forever due to business/security concerns then A1 will now be considered as an Invalid account.

We request Invalid Accounts to be reworded to

_An invalid account implies it is permanently unavailable._
_No subsequent request for the account will be successful._

**Appendix A**

We are also requesting change to the following error scenario descriptions.

| # | Existing Error Scenario Description | Requested Change | Rationale
-- | -- | -- | --
17 | The requested resource identifier is invalid, does not exist or will not be disclosed for business or security reasons. | The requested resource identifier is invalid, does not exist or will not be disclosed for business or security reasons **permanently**. | If the resource could one day be disclosed (due  to change in business/security reasons) then the error code of `urn:au-cds:error:cds-all:Resource/Invalid` is incorrect.  The correct code should be `urn:au-cds:error:cds-all:Resource/Unavailable`.
19 | The account bank account does not exist, the account is not associated to the consumer’s active consent, or business reasons exclude executing this resource. | The requested bank account does not exist or the account is **permanently** unavailable due to business or security reasons which exclude executing this resource. | Accounts not currently associated with an active consent MAY later be associated with an active consent (due to change in business/security reasons).   The error code `urn:au-cds:error:cds-banking:Authorisation/UnavailableBankingAccount` should instead be used when the condition is temporary.

**Comment by NationalAustraliaBank** [comment]
NAB welcomes the opportunity to provide the following feedback in relation to DP 155:

Item | Feedback
-- | --
Unavailable vs Invalid Accounts | UnavailableBankingAccount appears to overlap with InvalidBankingAccount. E.g. Both codes cater for when an account is no longer associated to an active consent. It would assist to have some examples such as: An account is associated to a consent and then gets removed from the consent (this may or may not change again the future) or an account is suspended or frozen.
Reference of the field should be provided in the error description along with the detail explaining the valid format.| NAB questions the value of providing references within the error description of the actual erroneous data.  For example, item 3 – whilst we agree there is value in returning error code ‘Invalid Field’, we feel that providing a reference of the actual field in the error description creates unnecessary complexity.
Item# 23 | NAB proposes returning 200 and an empty result list. If a page number is too large--for instance, if there are only 50 results, but the client requests pageSize=100&page=3--the resource MUST respond with the HTTP status code 200 OK and an empty result list.
Item# 24 | NAB proposes returning 400 to align with returning 400 for Invalid Header
Item# 25 | This item would be technically complex to implement (ie. determining across the various API's which has a scheduled outage vs unexpected outage / fully or partially unavailable would be difficult to implement).
Partial Success | NAB would like to confirm how to respond in a partial success scenario.  For example, when more than one account Id is requested (e.g. via bulk GET) and DH can only partially meet that request (eg. one of the accounts has no election / disclosure option selected ), how should the data holder respond?

**Comment by commbankoss** [comment]
Commonwealth Bank has the following feedback on the decision proposal:
- We support formally supporting 404 error codes, as per the recommendation on page 5.
- Line 8, 400 Bad request: we propose this error scenario should instead be 404, similar to line 14, as the request is well constructed but the brand itself is not valid.
- Line 21, 422 Unprocessable Entity: we propose this scenario is similar to line 12, and should be a 403.

**Comment by anzbankau** [comment]
We agree with not imposing requirements on components such as the WAF and API Gateway which will likely be products/services that have limits on customisation. However looking at the error code catalogue there are many MUST requirements that these components deal with and may not be achievable. We strongly advocate that the mandatory nature of this be modified so as not to dictate data holder implementations, and instead change all MUSTs to SHOULDs. This would mean where it is practicable for a data holder to align and implement they will. An example of this is scenario 1 - urn:au-cds:error:cdsall:Field/Missing - if a data holder's WAF or API Gateway is validating the request against the OpenAPI spec and the specification is violated then a HTTP 4xx code would be returned but would not include any information as to which mandatory field or header was responsible for the violation. As this level of detailed handling can't be managed by these components then the data holder's implementation would have to handle this at the application layer which in turn would result in a loosening of security in WAF and / or API Gateway to allow for this.

Additionally where the requirement is listed as a SHOULD - we would like it to be clarified that the expectation is that at a minimum the HTTP response code is adhered to for the scenario (which we agree is appropriate), but the requirement to provide a error payload and CDR error code is relaxed.

With respect to particular scenarios, we have the following queries:
- There appears to be some overlap between scenario 16 (urn:au-cds:error:cdsall:Resource/NotFound) & 17 (urn:au-cds:error:cdsall:Resource/Invalid) - both state they apply to invalid resource identifiers. Should this be updated to make scenario 16 focused on an end point that doesn't exist vs a resource identifier?
- When would scenario 10 (urn:au-cds:error:cdsall:Authorisation/AdrStatusNotActive) be used - given there are other scenarios that deal with the more granular software product status?

On the timing of these error handling decision proposals we do have concerns due to the the large amount of scope currently targeting the November release. We recommend an appropriate time would be February 2022.

**Comment by PratibhaOrigin** [comment]
### Feedback from Origin Energy on DP-155

Thanks for the opportunity to provide feedback on this DP. From our review of DP 154, 155 & 156 , it appears these papers will be still bit focussed on Banking sector at this stage. However, we have reviewed the paper from energy sector perspective and generic architecture & design preference.

For the DP 155 , no specific concerns from  Origin point of view. Just some minor design queries below - 

- General - If resource has been moved (as a result of some data migration), what would be error code: “unavailable“ or “moved“? 
-  Page 11. Items 15 and 16 - If resource not implemented how DH can differentiate between error code 15 and 16 (404), in terms of validity of resource  according to the standards?

**Comment by WestpacOpenBanking** [comment]
Westpac is supportive of the addition of the 404 (Not Found) HTTP code. We are also supportive of not imposing CDR error codes where the normative standards apply. We are generally supportive of a requirement level of SHOULD rather than MUST to allow for the possibility of edge cases in complex implementations.

We have the following  detailed questions and comments:
* Should not including versioning headers result in a urn:au-cds:error:cds-all:Header/Missing or a urn:au-cds:error:cds-all:Header/InvalidVersion header?
* Is there value in defining one error for every possible invalid query parameter?
* We would argue that urn:au-cds:error:cds-all:Authorisation/ AdrStatusNotActive could be removed in favour of urn:au-cds:error:cds-all:Authorisation/AdrSoftwareProductStatusNotActive – the defined behaviours now are purely implied by the software product status as there may be multiple ADR statuses 
* There may be value in differentiating between cases where consent is invalid and recovery is possible (e.g. a temporary block of some kind to prevent a risk of harm) and where it is not possible (i.e. it was revoked but an access token hasn’t expired).
* It would be difficult to support urn:au-cds:error:cds-all:Resource/NotImplemented in practise – deployments would in principle be required for every new resource ID added to the standards ahead of any obligation date.
* It may be difficult in practise to different between a urn:au-cds:error:cds-all:Resource/Invalid and a urn:au-cds:error:cds-all:Resource/NotFound scenario as described. We recommend that both are given a requirement level of SHOULD.
* A resource that is unavailable may by definition be unable to give an error response including the urn:au-cds:error:cds-all:Resource/Unavailable error code – we recommend that a requirement level of SHOULD is given.

**Comment by CDR-API-Stream** [comment]
Thank you to everyone who's put forward feedback. Consultation has been closed and feedback will now be reviewed and considered.

**Comment by CDR-API-Stream** [comment]
Thank you to everyone who provided feedback. Because the feedback has resulted in some improvements and changes to the catalogue, this thread will be reopened for one week in case any participants want to provide feedback on the changes to be adopted. **Feedback will close on Wednesday 21/04/2021.**

Rather than respond to each specific comment from the community, the feedback has been summarised.

**General feedback**
  * Introduction of 404 Not Found is supported
  * Good support for the majority of the error codes proposed with some fine tuning
  * Some data holders requested that some or all error codes be made SHOULDs rather than MUSTs
  * Several respondents provided feedback on the differentiation between Invalid vs Unavailable with practical suggestions to simplify this set of error codes
  * Respondents suggested changes to the CDR Register HTTP status codes to better align to the CDS
  * Where error codes are specified as SHOULDs, the HTTP status codes remain a MUST

**Feedback on error codes**
| # | Feedback | DSB position | DSB commentary | 
|-|-|:-:|-|
| 1 | Make all error codes **SHOULD**s rather than **MUST**s | :x: Not supported | The intent is to provide deterministic interoperability for ADRs. Making all error codes **SHOULD**s would not achieve this objective. |
| 2 | Where error codes are specified as **SHOULD**s, the HTTP status codes remain a **MUST** | :x: Not supported | All error codes defined in the catalogue include the recommended HTTP status code. Whilst it seems reasonable to enforce the the status code, this may have unintended implications issues and in practice it may be difficult where the WAF/ API Gateway doesn’t have custom error code policies. **SHOULD** is a keyword defined in RFC2119 with particular meaning. A participant that cannot implement the status code must have valid reasons in particular circumstances to ignore a particular item. Where a DH cannot respond with the recommended error code (where the error code is a **SHOULD**) then the DSB has previously given guidance that participants at least responds within the same class of status codes (i.e. 3xx/4xx/5xx).  |
| 3 | Error code 16 (`urn:au-cds:error:cds-all:Resource/NotFound`) and 17 (`urn:au-cds:error:cds-all:Resource/Invalid`) are duplicates | :exclamation: **Request community feedback** | The purpose of `Resource/NotFound` is the endpoint is not a valid CDR endpoint (e.g. `/wrong/foo-bar`). The intended meaning is similar to Resource/Invalid however `Resource/Invalid` is intended to signify that the resource identifier that was requested is invalid. As Resource/NotFound is a **SHOULD** and `Resource/Invalid` is a **MUST** because it is reasonably expected to be handled by the API application layer as opposed to an API Gateway, there would be a downgrading in the requirement level if these two codes were consolidated to either `Resource/NotFound` or `Resource/Invalid`. The benefit of consolidation is simplification of the catalogue. In the situation where consolidation is supported then `Resource/NotFound` would be more generic. |
| 4 | Create unique error codes for every single query parameter | :x: Not supported | This would not be scalable. It goes against the purpose of enhanced error handling which was to offer consistent, generic messaging so that the implementation did not become unreasonable. This can be dealt with by including specific details in the description message. | 
| 5 | Change error code 8 (`urn:au-cds:error:cds-register:Field/InvalidBrand`) response code to be 404 (Not Found).  | :white_check_mark: Adopt | The CDR Register has indicated willingness to support this change.  | 
| 6 | Change Error Code 24 (`urn:au-cds:error:cds-all:Field/InvalidPageSizeTooLarge`) to be 400 (Bad Request) | :white_check_mark: Adopt | An invalid page size can be interpreted as a malformed request. In this case, the DSB is recommending it be simplified to use `Field/InvalidPageSize` (error code #6) for both scenarios including where the page size is larger than the maximum allowed.  |
| 7 | Don’t include outage details in Error Code 25 (`urn:au-cds:error:cds-all:Service/Unavailable`) | :white_check_mark: Adopt | The description for Error Code 25 will the changed to remove detail of the CDR Outage status in the response because this is overly difficult to implement. Purpose of this error is to imply the endpoint being requested is unavailable | 
| 8 | Error code 10 (`urn:au-cds:error:cds-all:Authorisation/AdrStatusNotActive`) is not reachable  | :white_check_mark: Adopt | Error code 10 and error code 11 will be consolidated, removing code 11. `urn:au-cds:error:cds-all:Authorisation/AdrStatusNotActive` will be retained to encompass the software product and the associated ADR status |  
| 9 | Change Error Code 21 (`urn:au-cds:error:cds-all:Authorisation/RevokedArrangement`) to be 403 (Unauthorised) the same as Error Code 12 (`urn:au-cds:error:cds-all:Authorisation/InvalidConsent`) | :exclamation: **Request community feedback** | This issue is not with the ADR’s client authentication but the CDR Arrangement ID provided in the request body no longer being in a state that allows revocation. Unless there is strong feedback to the contrary, the DSB does not support this change because the two errors have very different and specific meanings  |
| 10 | How should the CDS handle resources that have moved? | :exclamation: **Request community feedback** | 302 Permanently Moved is reasonable expected to be used in situations where a resource has moved location. This is standard HTTP behaviour. It is anticipated this may occur for accountId scenarios as well as other resources. Supporting this will allow greater flexibility in the advent that account Id permanence issues arise. The DSB supports the inclusion of 302 Permanently Moved in the HTTP Response Codes section of the standards because it makes it clear that it is intended behaviour. If supported, it is recommended this be consulted on separately in the next Maintenance Iteration so that it does not delay the other Enhanced Error Handling changes |
| 11 | Should partial responses be supported? For example, when more than one account Id is requested (e.g. via bulk GET) and DH can only partially meet that request (eg. one of the accounts has no election / disclosure option selected). Another example is a white label product cannot be returned (white labeller is not responding) | :exclamation: **Request community feedback** | Previous guidance has stated that the full response should be returned or an error. If partial responses **in some well-defined situations** is considered the best outcome for ADRs then it should be raised as a change request by the community.  |

**Comment by spikejump** [comment]
We may have missed this in DSB's response above but the response does not seem to address [our request above](https://github.com/ConsumerDataStandardsAustralia/standards/issues/155#issuecomment-773768987) on clearer distinction between **permanent** vs **temporary** availability.  Appreciate consideration of the request.

In addition, to DSB's request for further community feedback:

- Feedback on error codes row 9: We agree they are two distinct errors.
- Feedback on error codes row 10: It would help to identify clearly the use-cases why/how resources have moved to understand whether 302 is applicable.

**Comment by CDR-API-Stream** [comment]
Hi @spikejump, 

> We may have missed this in DSB's response above but the response does not seem to address our request above on clearer distinction between permanent vs temporary availability. Appreciate consideration of the request.

This will be reviewed to make sure the feedback was correctly taken into account.

> Feedback on error codes row 10: It would help to identify clearly the use-cases why/how resources have moved to understand whether 302 is applicable.

You're absolutely correct. The proposal is to create a specific change request to deal with this because there will be impacts to ADRs given a way to process 302s has not been previously defined.

**Comment by anzbankau** [comment]
ANZ requests that the below error codes are converted from MUSTs to SHOULDs. This is because these validations are generally handled by API Security components which have minimal capability for custom error handling.

- Error code 1 - 400 (Bad Request) - urn:au-cds:error:cdsall:Field/Missing
- Error code 3 - 400 (Bad Request) - urn:au-cds:error:cdsall:Field/Invalid
- Error code 6 - 400 (Bad Request) - urn:au-cds:error:cdsall:Field/InvalidPageSize
- Error code 7 - 400 (Bad Request) - urn:au-cds:error:cdsall:Header/InvalidVersion
- Error code 22 - 406 (Not Acceptable) - urn:au-cds:error:cdsall:Header/UnsupportedVersion

Additionally would it be possible for the following error codes to only be MUSTs for authenticated APIs (i.e. excluding public end points), as this feels where the handling is useful for clients.

- Error code 17 - 404 (Not Found) [in path] 422 (Unprocessable Entity) [in body] - urn:au-cds:error:cdsall:Resource/Invalid
- Error code 18 - 404 (Not Found) [in path] 422 (Unprocessable Entity) [in body] - urn:au-cds:error:cdsall:Resource/Unavailable

**Comment by NationalAustraliaBank** [comment]
- NAB Supports consolidation of Error code 16 and 17 and the combined error code being Resource/Not Found

- NAB recommends Error Code 21 (urn:au-cds:error:cds-all:Authorisation/RevokedArrangement) to be changed to SHOULD if DSB doesn’t intend to consolidate it with Error code 12. Once an consent is successfully revoked, we no longer identify the arrangement ID anymore and would treat any further requests using the arrangement ID as invalid.

**Comment by CDR-API-Stream** [comment]
Hi @NationalAustraliaBank, given the change to requirement levels consolidating error codes 16 & 17 will cause and the limited feedback, these two codes won't be consolidated

For Error Code 21, the change to the error code has been adopted however the 422 Unprocessable Entity response code still applies. This is because the Arrangement ID is posted to the CDR Arrangement Revocation endpoint and the 422 response is consistent with other errors due to business logic.

**Comment by CDR-API-Stream** [comment]
Hi @anzbankau, although these error codes may be encountered at different levels within the application stack, the error codes will remain MUST level requirements. This is because the primary aim is to increase the uniformity and reliability for data recipients where an error it is reasonable to expect consistency where business logic errors are encountered.

**Comment by CDR-API-Stream** [comment]
The changes related to these consultations have now been staged in draft format. They are available for review here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.10.0...dp/154

At this time, the changes are not formal data standards. A formal decision will be taken to the Data Standards Chair next week. Where reviewers identify issues with presentation, please raise a change request on Standards Maintenance so the DSB can address.

A draft version of the generated standards documentation is viewable here: http://ec2-18-224-29-97.us-east-2.compute.amazonaws.com

**Comment by nils-work** [comment]
Hi @CDR-API-Stream 

1. Is this sentence correct?
`If otherwise specified, Data Recipients and Data Holders SHOULD use the standard error codes defined below`

2.  There is a \<br\/\> tag in the middle of this example
`"code": "urn:au-cds:error:cds-banking:<br/>Authorisation/UnavailableBankingAccount",`

3. The description in the 404 response to this request appears incorrect (it only partially matches the resource requested)
`https://data.holder.com.au/cds-au/v1/banking/accounts/b3f0c9d0/transactions/52e443ae13c5`

4. I think the description for the 406 error is a bit confusing due to the details in brackets (particularly `x-min-v`, also see item 5.)
An error like this should only occur when the single value of x-v or the complete range from x-min-v to x-v is higher or lower than the versions supported. Just removing the details in brackets may make the intent clearer. 
`A request is made for a version that is lower than the minimum version (x-min-v, x-<HID>-v) or greater than maximum version (x-v, x-<HID>-v) the Data Holder supports for the requested endpoint.`

5. Related to above, I think this example is confusing/invalid as I don't think there is a logical example of where a specific x-min-v **must** be requested. The ADR requests a range with a preference for the highest value in the range. 
If a version in the range is not available, it is really the x-v that is either too high or too low and never that the requested x-min-v must be higher. 
If both x-min-v and x-v are lower than the supported version, x-v is really what needs to be higher, as the ADR may support lower versions even if the DH doesn't, and the DH is not obliged to support the x-min-v requested, only something lower than, or equal to the x-v. That seems to mean there should not a need for a DH to throw an error asking for a higher acceptable minimum to be requested.
`"description": "'x-min-v' must be greater than or equal to '2'"`

6. The links in the API response sections to `400 - Invalid Page Size` do not have the correct anchor value.

**Comment by CDR-API-Stream** [comment]
Thanks @nils-work, for the review. Can you please clarify the issue you see with #1? The remainder of the issues have been addressed.

**Comment by nils-work** [comment]
Hi @CDR-API-Stream 

Initially I thought it had the meaning of -
"**Unless** otherwise specified ... use the standard codes" _(i.e. others take priority)_
or 
"If **not** otherwise specified ... use the standard codes" _(i.e. others take priority)_

The current wording seems to imply that the codes 'below' take priority '**if otherwise specified**'

I guess the confusion could be where you assume they may be 'otherwise specified'. 
In the CDS or other normative standards? Or is it just a typo?

**Comment by CDR-API-Stream** [comment]
Thanks @nils-work, the intention is not to impose CDS defined error codes where upstream standards apply (e.g. oAuth). The intention of this statement is that CDS error codes SHOULD be used unless they are clearly indicated to be mandatory (MUST) or optional (MAY) in any areas within the CDS standards.

Would it be more suitable to re-state this as:

> * Data Recipients and Data Holders SHOULD use the standard error codes as defined
> * Where a specific error code MUST be responded, this requirement is stated against the applicable error code or API endpoints
> * Where a specific error code MAY be responded, this requirement is stated against the applicable error code or API endpoints

**Comment by nils-work** [comment]
Hi @CDR-API-Stream 
Yes, that seems clearer to me, thanks

**Comment by CDR-API-Stream** [comment]
The Data Standards Chair approved the changes to be made. The decision record is available here: [Decision 154-155-156 - Enhanced Error Handling - Summary of Changes To Be Made.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/6572983/Decision.154-155-156.-.Enhanced.Error.Handling.-.Summary.of.Changes.To.Be.Made.pdf)

These changes will be incorporated into release v1.10.0 of the Consumer Data Standards

**Comment by CDR-API-Stream** [comment]
These changes have now been incorporated into [v1.10.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.10.0.html). Accordingly, this decision is closed.
