### ISSUE TITLE
Noting Paper 200 - Action Initiation Framework

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#200]
**Update: 30/08/2021** 
This Noting Paper will close at COB on Friday 3rd of September 2021.

---
**30/07/2021** 
To assist in informing inform the Government's response to the [Future Directions for the CDR](https://treasury.gov.au/publication/inquiry-future-directions-consumer-data-right-final-report) a workshop has been scheduled for the end of July 2021. In the lead up to this workshop, the DSB is seeking input on use cases and considerations for designing an economy-wide Action Initiation Framework. 

To provide context a noting paper has been developed to introduce key concepts and initial design hypotheses: [Noting Paper 200 - Action Initiation Framework.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/6773233/Noting.Paper.200.-.Action.Initiation.Framework.pdf)

The noting paper includes a template for documenting use cases. When suggesting use cases, the DSB requests comments in response to this noting paper use that template for consistency. This will assist in formulating the workshop inputs.

Feedback to the noting paper was used by the DSB as inputs into a half-day virtual workshop held on Tuesday 27th July to help inform the government's response to the action-initiation recommendations in the [Future Directions report](https://treasury.gov.au/publication/inquiry-future-directions-consumer-data-right-final-report).

The 27 July workshop artefacts have been made publicly available online (see: [Miro](https://miro.com/app/board/o9J_l55v_aw=/)). The outputs from this initial workshop are being analysed to generate a better understanding of what high value instructions might look like.

**Comment by CDR-API-Stream** [comment]
The noting paper has been published and is available in the original issue description [here](https://github.com/ConsumerDataStandardsAustralia/standards/issues/200#issue-933360885).

**Comment by SelenaLiuEA** [comment]
Hi All, 

EnergyAustralia's initial feedback on this Issues Paper is attached. We look forward to discussing this more tomorrow. 

Thank you 
[EnergyAustralia response - Action initiation - Issues Paper 200 - FINAL.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/6875419/EnergyAustralia.response.-.Action.initiation.-.Issues.Paper.200.-.FINAL.pdf)

**Comment by WestpacOpenBanking** [comment]
Westpac welcomes the opportunity to comment on Noting Paper 200. 

Our core remarks are:

* A number of CX flows will need to be developed for action initiation and some processes, such as account creation, may be better modelled from a CX perspective as a form of pre-population rather than as a consent activity where AAIs provide data to originate to ASPs. We are not supportive of a prescriptive approach involving standardised action steps because the data and processes involved will likely vary significantly between ASPs.
* We note that “pull actions” involve four parties (the customer, the merchant, the AAI and the ASP) and that implementing them would require a common identity between merchants and banks representing customers – a complex issue. We do not believe that pull actions are critical to the enablement of use cases (including payment initiation from a merchant via an ASP and direct debit-like functionality), and therefore we recommend that they be considered at a later stage subject to detailed technical feasibility assessment and, consideration of implementation costs and benefits.

We have the following comments on the paper:

* Principle 1: We recommend including statements to say that consent should be voluntary, express informed, specific to the purpose, time limited and easily withdrawn as per the current data sharing rules. As above, we note that some actions would be better viewed in terms of pre-population rather than as a consent flow.
* Principle 2: We agree that the CDR should only provide an alternative channel for consumers at the ‘instruction layer’ and not at the underlying ‘action layer’. We note that certain actions are not always initiated by the ASP. In particular, we expect that merchant-initiated transactions such as making a payment with a credit card or setting up a traditional direct debit would be excluded by this principle.
* Principle 10: We recommend the following wording instead “Utilisation of standards: CDR should seek to utilise and contribute to widely accepted international and domestic standards, unless a compelling case has been established not to do so.” This approach will maximise vendor support and hence participation in the CDR.
* We recommend the addition of the following principle: “Principle xx:  Secure: The standards should incorporate a high degree of security to protect customers. They should address technical security and aim to minimise risks using fine-grained consents.”
* We note that during the process of performing an action there is frequently a need for an ASP to interact with a customer. For example there may be a need to ‘step up’ in authentication level if an intent to perform an action looks suspicious (for example paying to a new payee). 
* The distributed action initiation model seems entirely related to white-labelling. It may be better to deal with white-labelled products using a similar approach to existing provisions.

**Comment by CDR-CX-Stream** [comment]
On Tuesday 27th July, the DSB and TSY ran a joint workshop in conjunction with consultation on [Noting Paper 200](https://github.com/ConsumerDataStandardsAustralia/standards/issues/200). This workshop was run to help inform the government's response to the action-initiation recommendations in the [Future Directions report](https://treasury.gov.au/publication/inquiry-future-directions-consumer-data-right-final-report).

Workshop participants ideated on a wide range of use cases, identified existing consumer needs and pain points, developed journey maps, and used these inputs to produce 10 high value/impact value propositions. The workshop artefacts have been made publicly available online (see: [Miro](https://miro.com/app/board/o9J_l55v_aw=/)).

The outputs from this initial workshop are being analysed to identify the scope of instructions raised in the workshop, and where instructions can support a broad range of value propositions. These outputs are being synthesised to generate a better understanding of what high value instructions might look like.

**Comment by CDR-API-Stream** [comment]
This Noting Paper will close at COB on Friday 3rd of September 2021. The DSB would welcome any further use cases or feedback before the closing date.

**Comment by CDR-API-Stream** [comment]
The following submission has been provided by TrueLayer and posted with permission on their behalf: [Noting Paper 200 - Action Initiation Framework - TrueLayer Response.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/7080239/Noting.Paper.200.-.Action.Initiation.Framework.-.TrueLayer.Response.pdf).
