### ISSUE TITLE
Decision Proposal 206 - Register Standards

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#206]
This decision proposal covers the approach and process for bringing the CDR Register Standards into the Consumer Data Right Standards so that they can be made binding.

The decision proposal is attached below:
[Decision Proposal 206 - Register Standards.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/6941945/Decision.Proposal.206.-.Register.Standards.pdf)

This consultation is now open for feedback and will be closed on the 10th September 2021.

**Comment by biza-io** [comment]
Biza.io makes the following suggestions:

- Include an explicit statement that the proposed transition does not alter the existing technical implementation of the existing specification in **any** way. This is an important distinction because the word "merge" can be misconstrued as a license to tweak and some of the areas (notably Client Authentication) are potentially exposed to unintended redefinition during the process
- Explicitly call out where the existing Register specification is divergent from the CDS norms, notably in the inconsistent use of `x-v` versioning headers which are not explicitly documented in the existing Standards as they are assumed
- The proposal suggests merging the Register APIs into the Standards however the Register APIs include OpenID Discovery and JWKS definitions which will be easily confused with Holder endpoints of the same nature

Finally Biza.io notes it is difficult to provide feedback on a Decision Proposal that does not include an actual target of the intended end state. We request that, following this decision proposal, a further proposal is put forward with an _actual_ draft of the intended merged artefacts. We are dubious as to whether this merge could be considered a minor change to the standards on the basis the number of shared elements changing within the documentation is significant.

**Comment by CDR-API-Stream** [comment]
Thanks for the feedback @biza-io.  The DSB is also concerned about the merge process accidentally resulting in interpretation changes resulting that are not intended.

To restate (or clarify) the intention of this process will be to merge with no material change and not to change the implementation requirements in any way.  Due to the complexity of the merge process we will consult on the specific changes but the intention is that this will be done via specific technical changes in the standards-staging repository.  This will remove the additional risk of transcription issues from a word document to the actual standards documentation.

A decision document for the chair will be created and submitted so this change will be published as minor change rather than a patch change.

**Comment by CDR-API-Stream** [comment]
In the absence of any feedback to the contrary, a decision will be submitted to the Chair along the lines of the recommendation.  This decision will be published if approved by the Chair.

**Comment by CDR-API-Stream** [comment]
Please find attached the final decision of the Chair:
[Decision 206 - Register Standards.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/7394066/Decision.206.-.Register.Standards.pdf)
