### ISSUE TITLE
Design Paper: Consumer Data Right Rules and Standards for the Telecommunications Sector

### ISSUE THREAD

**Issue by CDR-CX-Stream** [ConsumerDataStandardsAustralia/standards#235]
## Context
Treasury and the Data Standards Body are seeking input on the development of rules and standards to implement the CDR in the telecommunications sector. To support consultation and elicit informal feedback on these issues, a design paper is available for stakeholders’ consideration.

We invite all participants in the Consumer Data Right to raise queries and submit their feedback below as part of this GitHub consultation.

Link to key consultation documents: https://treasury.gov.au/consultation/c2022-250645
Feedback on this consultation closes on ~~29 of March 2022~~ **5th of April 2022**

## Design Paper
A design paper is a consultation approach that provides an opportunity for simultaneous consultation on the rules, policy, standards, and guidelines for a change to the Consumer Data Right. In the past we have worked together to solve implementation questions and challenges by first defining Rules and Standards and then requesting comment. A design paper allows participants to comment on the implications of proposed Rules and Standards, before they are defined. Where applicable, a design paper will also include consumer experience mock-ups to demonstrate the implementation and how that may affect existing participant's systems.

## Providing Feedback
A design paper will elicit feedback to be consumed by multiple teams. Feedback on the standards can be provided here and the DSB will respond directly as per usual. Rules and policy feedback can also be provided here and the DSB will seek to clarify this feedback and then provide it to the appropriate team for consideration.

Feedback can also be provided via email to [data@treasury.gov.au](mailto:data@treasury.gov.au) or to [contact@consumerdatastandards.gov.au](mailto:contact@consumerdatastandards.gov.au). 

As per usual practice, email submissions sent to [contact@consumerdatastandards.gov.au](mailto:contact@consumerdatastandards.gov.au) will be made public unless a request is included to keep the submission private. While we appreciate that some submissions may need to be private the fact that they will not be available for community discussion necessarily means we will not be able to give them the same consideration as public feedback. Legal requirements, such as those imposed by the Freedom of Information Act 1982, may affect the confidentiality of your feedback.

There will also be opportunities for discussion and feedback during March 2022 through a CDR forum.

**Comment by CDR-CX-Stream** [comment]
Treasury and the Data Standards Body are seeking input on the development of rules and standards to implement the CDR in the telecommunications sector. To support consultation and elicit informal feedback on these issues, a design paper is available for stakeholders’ consideration. 

Links and consultation dates can be found in the original post.

**Comment by JTRlaw** [comment]
Scope of data sharing 

In respect of developing sector-agnostic standards and rules, and to increase innovation and competition, we do not support a ‘de minimis’ threshold for telecommunications. This simply disadvantages consumers of data holders below such a threshold and reduces competition by excluding smaller players being seen when a consumer is comparing providers.  

Excluding access for some consumers, making the process cost and time prohibitive for small data holders to participate, defeats the ‘important objective’ noted in paragraph 47 of this paper ‘to support anticipated use cases such as price comparisons and switching’. The Australian Bureau of statistics series 81670 indicates that firms with 0-4 person represent 64.8% of employing business and 36.8% of businesses innovating. What is the lost opportunity for not requiring data holders in this category from participation in the CDR?  

Of particular concern is the interpretation by retailers under such a threshold to provide data voluntarily.  Currently the rules allow data holders to charge a fee to provide voluntary data which is in addition to the data identified in the designation instrument. Yet, if even providing any data is voluntary for long tail retailers, will they be entitled to charge for the provision of any data? 

We understand the concern of the burden of accreditation on data holders that are seen as small businesses in a sector. To address this concern, we consider it is the process of accreditation that should be reviewed rather than creating an uneven playing field for consumers and small businesses in certain designated sectors where access to CDR data should be available to all participants. Rather than address the imbalance of power held by large players, this simply attracts consumers that seek to access the benefits of the CDR regime moving to large players as they are designated data holders. 

Improving the accreditation process to accommodate all data holders better aligns with the overarching aim for the standards and rules to be sector agnostic. Creating ‘de minimis’ thresholds for certain sectors, that may need to change over time as technology and consumer use changes, increases the complexity of an already complex regime and further empowers larger players in a sector. 

Ensuring all data holders in a designated sector can participate will not only enable full consumer participation but incentivise consumer participation with access to data across all data holders. 

 2. Eligible CDR consumers 

For consumers, we again raise the persistent gap in the roll out of the CDR, for consumers to request and receive their own data in a machine-readable form direct from data holders. As depicted in the High-level CDR standard data flow on page 7, implementation to date means the consumer must engage a third party to access their own data.  

The designation of another sector continues to force a consumer to engage an Accredited Data Recipient (ADR) to gain any benefit from access to their own data over a secure digital channel. Consumers must pay a provider, authorised in the CDR, for a service such as comparing products to facilitate switching. An undertaking many consumers could do themselves given access to the data. 

We challenge the presumption that consumers lack the digital literacy to be able to understand how the CDR works when the use of CDR will require these same consumers to manage multiple digital dashboards to consent to others accessing their data. We also seek the data on which the view that few consumers would have the ability to accept machine readable data was formed.  

For example, trusted advisers in the CDR will be CDR literate and able to receive CDR data. Trusted advisers are also consumers and, realising the benefits of the CDR, be digitally able to directly receive data through a CDR channel. 

We also challenge the concern that providing consumer with direct access opens the consumer to the risk that a third party with ill intent will use this channel to obtain and abuse a consumer's data. We do not consider this risk any greater than a consumer being directed by a party seeking insights, an affiliate or sponsor or an ADR themselves seeking disclosure consent, and that party misusing a consumer's data. Where a consumer is confused by multiple dashboards, overwhelmed by the information on these dashboards or does not quite understand the implications of providing disclosure consent, there is equivalent risk with every consent given of their data being misused.  

While we do not dispute the risk of abuse exists in a direct channel to consumers, we do not support the framework for the CDR excluding the build of such a channel. We ask that the build of direct-to-consumer channels be reinstated to the schedule for the roll out. If data holders consider such a pathway would be cost or time prohibitive, consideration could be given to utilising existing pathways by including consumers as Trusted Advisers with the caveat that they can only access their own data.

**Comment by CDR-CX-Stream** [comment]
You can now provide feedback on the design paper up until 5 April 2022. The closing date for submissions was previously 29 March 2022 but a one‑week extension has been granted.

**Comment by ACCC-CDR** [comment]
The ACCC provides the attached submission in response to this consultation.

[ACCC Submission on CDR rules and standards design paper for telecommunications sector.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/8415764/ACCC.Submission.on.CDR.rules.and.standards.design.paper.for.telecommunications.sector.pdf)

**Comment by CDR-CX-Stream** [comment]
This consultation has now closed. The Treasury and DSB are now reviewing submissions to inform future rules and standards development.
