### ISSUE TITLE
Noting Paper 248 - Energy PRD

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#248]
The attached noting paper outlines the exposure patterns and obligations regarding product reference data (ie. Generic Tariffs) in the energy sector.

---
*edit 11th May*

An updated version of the noting paper is provided below:
[Noting Paper 248 - Energy PRD.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/8665947/Noting.Paper.248.-.Energy.PRD.pdf)

This version includes:
* statements indicating which patterns do, or do not, imply self-hosting by the energy retailer
* an additional statement regarding certificates is also provided for pattern 2 noting paper has been updated
* minor fixes of typos

The original noting paper is attached below for reference:
[Noting Paper 248 - Energy PRD 04-14.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/8665946/Noting.Paper.248.-.Energy.PRD.04-14.pdf)

---
This paper is not a proposal and therefore this thread is not a formal consultation.  Feedback or requests for clarification on the paper are, however, welcome.

**Comment by perlboy** [comment]
Firstly, thank you for preparing this Noting Paper on short notice to clarify the position with regards to the presentation of Generic Plan data, aka Product Reference Data (PRD) for Energy. Reading this through there seems to be some missing considerations that are _alluded_ to but not specifically addressed.

In response it is important to define a number of factual requirements relevant for this noting paper:
1) `PublicBaseUri` is used for PRD information _and_ the Status/Outages endpoints. This is noted briefly in `Pattern 2` but is, in fact, a global requirement regardless of technical solution. There is potential for more flexibility on this requirement if the Register was to bifurcate `PublicBaseURI` into two separate base uris (PRD and Status/Outages)
2) The current Metrics API _requires_ the statistical collection of Unauthenticated endpoint activity vis-à-vis the activity attributed to the `PublicBaseUri`
3) Metrics API is required to be available to the Regulator for Retailers delivering _Consumer Data Request Service_ (CDRS) 
4) ACCC currently requires additional 6-monthly reporting of PRD Requests via a manual form submission process

With these requirements now stated it is now possible to assess the suitability of the described patterns in more detail.

**Pattern 1: Direct to AER**
- The `PublicBaseUri` for Retailers adopting this pattern would be set to the AER
- Metrics collection for these endpoints would, by definition, be the responsibility of AER particularly since Admin Metrics endpoints for Retailers would presumably not be available until they had exposed their CDRS
- It is unclear how AER would differentiate between retailers. 
  - In the "traditional" PRD context this would be using a brand filter but metrics would be skewed for unfiltered requests.
  - Alternatively a base path could be specified for each retailer on the AER base domain although this could potentially increase implementation complexity for AER
- As noted this would no longer be viable when the Retailer was required to delivery Status and Outages APIs
- 6-monthly ACCC reporting would be the responsibility of AER _unless_ AER was to provide each Retailer with a report that the Retailer could submit via the existing channels

**Suitability**: Non-CDRS Retailer ✅  CDRS Retailer ⛔ 

**Pattern 2: DNS Redirection**
- The proposal suggests the use of a DNS CNAME and the diagram indicates that Consumer traffic would "flow" through the Retailer DNS to AER.
  - This appears to be technically inaccurate, a DNS CNAME provides a resolver outcome (ie. a name to an IP). This is then used to initiate HTTPS communication on which to perform API calls. Those API calls would be made using the Retailers `Host` header directly _to_ AER and AER services would be expected to respond appropriately to these retailer specific hostnames. 
  - AER would need to maintain or be given TLS certificates that match this Host header presumably via SNI for each of the Retailers selected domains which has the potential to run afoul of corporate policies with regards to the assignment and provision of TLS certificates to hostnames within the corporate namespace
- Metrics would need to continue to be collected by AER and would need to be the responsibility of AER because the Retailer is not hosting the API services themselves. 
- While a back channel reporting mechanism _may_ be possible the Metrics endpoint has a relatively high collection frequency (at least once every 24hrs) which, when considered in the context of processing requirements for AER to produce such a report for 100s of Retailers may be impossible to achieve.
- As noted, once a CDRS service was operated by a Retailer the Status & Outage APIs would make this pattern non-viable
- There is a reference to the concept that when a Retailer goes live they can continue to use the same domain. I assume this is a reference to the fact the CNAME can be changed to a service hosted by the Retailer as a DNS CNAME provides no other avenue for consistency enablement. It's not involved in the _actual_ API comms only the name resolution to the API itself.

**Suitability**: Non-CDRS Retailer ✅  CDRS Retailer ⛔ 

**Pattern 3: Proxy**
- This proposal implements a back-to-back API between the Retailer and AER
- While it is simpler to reference this as a Proxy this isn't technically accurate due to the implication that Metrics must be collected for reporting on Retailer Admin APIs. That is to say using a traditional "reverse proxy" pattern with COTS software would be unlikely to meet the requirements when considering the metrics collection requirements
- This pattern introduces the potential challenge that the latency between the Retailer Gateway and AER contributes to the overall time budget with respect to NFRs
- This pattern introduces the potential challenge that issues with the AER endpoint cascades implicitly into the Retailer. This is of particular concern because metrics may be incorrectly _skewed_ based on performance outcomes outside of the Retailers control. Given the NFRs define a 95th percentile obligation the distribution of such calls could give rise to the Regulator raising incidents (as it is already very quick to do) for NFR failures for which the Retailer will be unable to ameliorate.
- This pattern is, in essence, a similar pattern to the Secondary Data Holder architecture (ie. AEMO) but without such a designation the Metrics API will not expose potential discrepancies between how long it takes AER to provide a response and how long it takes the Retailer to distribute that response to the Consumer

**Suitability**: Non-CDRS Retailer ✅  CDRS Retailer ✅ (provided the above concerns are handled)

**Pattern 4: Self-Hosted**
- This is essentially an alignment to the Banking sector PRD delivery
- As noted, this would allow consumer access to be monitored by the retailer and therefore Metrics to be collated in much the same way as is already occurring in Banking

**Suitability**: Non-CDRS Retailer ✅  CDRS Retailer ✅ 

**Pattern 5: Hybrid**
- This pattern proposes to implement a similar pattern to _Pattern 3: Proxy_ however with an added business rule transformation for supply of non AER products (such as C&I( from internal Retailer systems
- This pattern would require the dynamic merging of external and internal data for the purposes of Get Generic Plans. Given this endpoint has various filters and pagination behaviours this is likely to be more technically complex than perhaps meets the initial evaluation
- The issues associated with Metric collection and potential latency from AER provided endpoints outlined in _Pattern 3_ remain

**Suitability**: Non-CDRS Retailer ✅  CDRS Retailer ✅

**Comment by CDR-API-Stream** [comment]
This is a very good summary of the position outlined in the paper and the suitability assessment presented is accurate.

There is one item to note arising from this commentary, and this is something we may need to add to the paper, or clarify via other guidance.

An energy retailer that is not providing their own Product Data Request Service is not required to report on the PRD end points and is not accountable for the non-functional requirements related to that service.  This means that the retailer can exclude these endpoints from the unauthenticated metrics in the Get Metrics API and in periodic reporting to the ACCC.

This is why it is highlighted as a disadvantage for the Self-Hosted and Hybrid patterns.  These patterns result in the retailer actually presenting a Product Data Request Service themselves and the rules state that they would then become accountable for all of the obligations of that service (including metrics collection).

We did discuss separating `PublicBaseURI` into two different URIs but decided against pursuing this route due to the complexity of change required for the Register and existing participants for a situation that is probably unique to the energy sector.

Apologies if the diagram for the DNS redirection pattern looks incorrect.  I was trying to make the pictures simple and representative for visual readers and differentiated pass through traffic from redirected traffic by the use of the API endpoint notation (line + circle).  It is correct to highlight that the DNS redirection pattern does not result in the retailer actually receiving any traffic as this is one of the advantages of that approach.

**Comment by perlboy** [comment]
> This is a very good summary of the position outlined in the paper and the suitability assessment presented is accurate.

Thanks!

> The callout that AER would need to be provided certificates for DNS Redirection to work is a good one and should be added to the paper.

I know this is a noting paper only but administratively that's going to be quite painful so maybe AER should be providing comment (@joe-aer, I'll drag you in here 😄 ). It may be worth adding a note that to reduce party to party (ie. AER to Retailer) dependencies the Retailer might be requested to setup a TXT record in addition to the CNAME to support [Email to DNS TXT contact DCV](https://docs.digicert.com/manage-certificates/demonstrate-control-over-domains-pending-certificate-order/#email-to-dns-txt-contact-dcv-method)... I'm really not sure though, even putting aside security policies etc, pretty dubious on the sustainability of this (with 100s of retailers AER is going to need a dedicated cert renewal person....)

> 
> There is one item to note arising from this commentary, and this is something we may need to add to the paper, or clarify via other guidance.
> An energy retailer that is not providing their own Product Data Request Service is not required to report on the PRD end points and is not accountable for the non-functional requirements related to that service. This means that the retailer can exclude these endpoints from the unauthenticated metrics in the Get Metrics API and in periodic reporting to the ACCC.

Hmm, this is an important clarification and is appreciated.

> This is why it is highlighted as a disadvantage for the Self-Hosted and Hybrid patterns. These patterns result in the retailer actually presenting a Product Data Request Service themselves and the rules state that they would then become accountable for all of the obligations of that service (including metrics collection).

More for clarification than anything, I believe this is a reference to this part of the rules?

> 9.4  Reporting requirements
> Reports that must be prepared—data holder
>              (1)  A data holder must prepare a report for each reporting period that:
>                      [snip]
>                      (c)  sets out the number (if any) of:
>                               (i)  product data requests; and
>                              [snip]
>                             **received** by the data holder during the reporting period; and

This covers the 6 monthly reporting requirement ✅  but I don't believe the Rules speak to the Get Metrics endpoint directly? It would be good to add a clarifying statement on Get Metrics to explicitly call out it is _only_ metrics received directly by the Data Holder?

> We did discuss separating `PublicBaseURI` into two different URIs but decided against pursuing this route due to the complexity of change required for the Register and existing participants for a situation that is probably unique to the energy sector.

I'm not confident such assumptions can be made and while I'm not seeking to push it here there's some direct benefits even in banking for doing so. I'm dubious about making decisions because a single participant (the Register) classifies it as a complex change - by that definition very little will get done.

> Apologies if the diagram for the DNS redirection pattern looks incorrect. I was trying to make the pictures simple and representative for visual readers [snip]

Hmm, I guess it's a style choice. A dotted line to Retailer DNS then a solid line to AER would be clearer imo.

**Comment by CDR-API-Stream** [comment]
In response to the feedback from @perlboy, with a call to action to split the `PublicBaseUri` value on the register, the appropriate place to raise this is as a CR in standards maintenance.  It may be the easiest solution for many retailers although the implementation constraint noted is also material in nature.

This would not, however, resolve the branding issues related to the presentation of the PRD endpoints for energy which may be important for some retailers.

Regarding your analysis of the rules, the noting paper was written to specifically clarify some of the ambiguities you raise and our understanding of the rules aligns with the content of the noting paper.

**Comment by perlboy** [comment]
>Basically, a retailer doesn't have to provide a Product Data Service but if they choose to do so they have to do it according to the obligations under the rules.

This is a contradiction to the guidance given in the Noting Paper. The DSB appears to imply that "proxying" (which it technically isn't) is different to providing a Product Data Request Service which, for the purposes of the Rules, it isn't. 

The retailer _can_ voluntarily provide this data but, by the very nature of it being voluntary, requests to these endpoints will return a 404 at the `PublicBaseUri` related url for these endpoints if they choose not to. It's baffling why the DSB appears so intent on confusing this but clearly it is now the prerogative of the Holders and potentially Vendors delivering on Holder obligations to take a position in the absence of the DSB providing unambiguous guidance.

**Comment by biza-io** [comment]
Biza.io cannot speak directly for its customers however, we have requested our customers make their feedback in this matter known via the appropriate channels. 

When providing technical guidance to our customers we have noted there are a significant number of unresolved operational concerns with the models outlined in the Noting Paper. Further we note that the DSB itself has acknowledged issues with the presented solution and has taken 2 months to suggest the creation of a CR to rectify a clear technical design failure. 

A prudent action would be for the DSB to reopen consultation on these endpoints and reevaluate prior feedback in this new context if it intends to continue to suggest these endpoints must be functional at the Retailers published `PublicBaseUri`. Should the DSB choose to do this Biza.io will proceed to produce the change requests it believes are necessary to support this operating topology.

As this thread now potentially forms a key piece of evidence in any legal proceedings arising from the Regulator launching enforcement action with regards to Data Holders obligations associated with these endpoints we wish to place in the same record the historical occurrences where @CDR-API-Stream or members of the DSB have provided statements which appear to contradict the _clarification_ this Noting Paper was apparently providing.

[Decision Proposal 190, 11 October 2021, James Bligh](https://github.com/ConsumerDataStandardsAustralia/standards/issues/190)
> This data cluster is designated to be provided **by the Australian Energy Regulator (AER) and the Victorian Department of Environment, Land, Water and Planning (DELWP) on behalf of Retailers**.

[Energy Draft Feedback Cycle 3, 30 May 2021, @CDR-API-Stream](https://github.com/ConsumerDataStandardsAustralia/standards/issues/180#issuecomment-850946641)
> It was raised that it is not clear how plans for Corporate and Institutional customers will be handled. It has been clarified that EME and VEC do not currently hold these plans so, if they are to be made available, that would be a change at the discretion of AER and DELWP. **The CDR designation is to make available the data held by EME and VEC and therefore C&I plans will only come into scope if EME or VEC data sets are expanded**.

[Design Paper: a peer-to-peer data access model in the energy sector, 27 May 2021, @CDR-API-Stream](https://github.com/ConsumerDataStandardsAustralia/standards/issues/177#issuecomment-849213038)
> The design paper does not address this as this is not an area of the designation that is impacted by the P2P model change. Generic product data **will be delivered to ADRs by EME and VEC using data provided to them by retailers as per the current designation instrument for the energy sector.**

[Energy Draft Feedback Cycle 1, 8 Mar 2021, @CDR-API-Stream](https://github.com/ConsumerDataStandardsAustralia/standards/issues/149#issuecomment-792396180)
> The designated data holders for the generic tariff structures is EME and VEC. **Currently retailers are not expected to implement the generic tariff endpoints**.

[Decision Proposal 111, 4 August 2020, James Bligh](https://github.com/ConsumerDataStandardsAustralia/standards/issues/111) [pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/5024748/Decision.Proposal.111.-.Generic.Tariff.Data.Payloads.pdf):
> As stipulated in the designation instrument the **data covered by this proposal is expected to be provided by the Australian Energy Regulator and the Victorian Government as the specified data holders**.

**Comment by PratibhaOrigin** [comment]
Origin supports the policy views and solution issues raised by @perlboy . That is, we do not believe that there is any legislative requirement in relation to retailers providing product data held by Energy Made Easy or Victorian Energy Compare.  

In the energy sector, plan information can be split into two data categories:
1. General product data – this is generally available, public offer data (data held by Energy Made East or Victorian Energy Compare); and   
2.  Tailored customer product data – this is data that is specific to the customers (ie data held only by retailers)

The intention of the Energy Designation for CDR and the CDR Rules was that 1) general product data be provided by Energy Made Easy and Victorian Energy Compare) while 2) tailored customer product data be provided by energy retailers.  The distinguishing difference being general product data was related to the availability of market offers from any retailer operating in the market and tailored product data was related to the current product the customer was being supplied on.  

Further to the analysis of the Energy CDR Rules by @perlboy , this distinction is clear in the Energy CDR Designation Instrument.  Section 9 of the Energy Designation Instrument is in relation to “information about retail arrangements”.  This is information relating to an arrangement such as tariffs, fees, benefits or rebates. Section 12 of the Energy Designation then defines who is the Data Holder for each of the relevant data sets.  The Table in section 12 of the Designation Instrument (extract below) sets that the AER and Victorian Government is designated Data Holder for information related to retail arrangements except to the extent the information relates to a tailored arrangement (item 4 below).  Retailers are then designated in item 5 below as a Data Holder for tailored retail information. 
 
<img width="436" alt="PRD" src="https://user-images.githubusercontent.com/72119982/176571386-0425757a-42b0-4c23-be19-3b0a955d95eb.PNG">



It is our view, that it is clear that the AER and Victorian Government have been designated as Data Holders for general retail arrangement information.  It was not the intention of the Rules nor the Energy Designation Instrument for retailers to have an involvement in providing general product data.  Origin does not believe that we should be required to be involved in the process nor take on the additional responsibilities and requirements that come with being assigned this role.  This proposal by the DSB goes beyond the intention of the Rules.

**Comment by CDR-API-Stream** [comment]
In response to the feedback from @biza-io, @PratibhaOrigin and @perlboy:

The requirement to supply the base URI for public endpoints to the Registrar and to expose status and outages endpoints arise from the obligation to support a *Consumer Data Request Service* under the rules.  This obligation applies to the three major energy retailers from the November date and not the October date.

As stated above and in the noting paper, a simple proxy of the PRD end points to allow them to be exposed from the base public URI (as required for the above obligation) does not constitute voluntary hosting and also does not mean that the retailer becomes responsible for the obligations inherent in providing a *Product Data Request Service*.  The retailer is technically facilitating the traffic but is not supplying the data and is not taking on the role of data holder under the rules.  This means, for instance, that there is no obligation to provide NFRs under get metrics for the PRD end points (although the obligation to report on the public admin end points remains).

The statement that proxying the PRD end points **is** equivalent to voluntary hosting is not the case.  The DSB confirmed this understanding with stakeholders in the ACCC and Treasury prior to publishing the noting paper.

Statements have also been made indicating that it is technically difficult and costly to implement a simple pass through proxy for PRD end points.  When the concept of AER and DELWP being designated for the PRD end points, as a way to reduce retailer implementation costs, was being consulted on the DSB asked whether a proxy model would be technically difficult and the feedback from retailers was that this would not be the case.  This feedback aligned with the experience in the banking sector where similar patterns are used to support OSPs and also aligns with a priori expectations.  If a retailer's specific technical context makes a proxy model difficult, however, we would appreciate understanding the specifics that makes this the case.  This would help us formulate guidance to reduce impact as the current position of the standards is based on the feedback previously received.

It should also be noted that the patterns presented in the noting paper are intended to be helpful but not exhaustive or comprehensive.  Any solution that meets the obligation that the base public URI exposes both the admin end points and the PRD end points would be sufficient.  If we have missed a viable pattern that meets these outcomes we would happy to add it to the noting paper.

**Comment by perlboy** [comment]
Wow, just wow.

> The requirement to supply the base URI for public endpoints to the Registrar and to expose status and outages endpoints arise from the obligation to support a _Consumer Data Request Service_ under the rules. This obligation applies to the three major energy retailers from the November date and not the October date.

This appears to be conflating the definition of a Consumer Data Request Service and, if taken literally, would mean that the status & outages endpoint would comply with the rules associated with CDR eligibility (1.13(1)(a)(i)) and accredited persons (1.13(1)(b)(i)). On this basis these endpoints would be MTLS and authorisation bound as there is no other way of assessing eligibility and accreditation.

The outages & status endpoint have no data set classification and ultimately appear only captured by Division 8.4, 8.11(1)(h) involving _"provision of administrative or ancillary services by CDR participants to facilitate the management and receipt of communications between CDR participants"_.

> As stated above and in the noting paper, a simple proxy of the PRD end points to allow them to be exposed from the base public URI (as required for the above obligation) does not constitute voluntary hosting and also does not mean that the retailer becomes responsible for the obligations inherent in providing a _Product Data Request Service_. 

I keep saying it but it's like trying to explain first year network engineering to someone who simply isn't interested in learning. This **isn't** a simple proxy but a back to back API which comes with it problems. 

As a _really_ simple demonstration (don't know why the DSB can't see this) if Retailer X implemented a reverse ("simple") proxy the net result would be that their endpoint would expose **all retailers plans** from the AER endpoint. If the retailer implemented a reverse proxy with the `brand=Retailer X` set in the query string they would be serving a _non compliant_ endpoint if the requesting client chose to include their own `brand` field. Further if Retailer X sells things under _multiple_ brands the Generic Tariffs specification _does not support_ a list of brands.

I could go further but the constant trivialisation of this suggestion to a "simple proxy" is either the DSB being _willing and demonstratively_ **blind** to the problems present or simple not having sufficient competence to grasp the technical concepts being put forward. Please stop making assertions that don't appear to be factually correct.

>The retailer is technically facilitating the traffic but is not supplying the data and is not taking on the role of data holder under the rules. This means, for instance, that there is no obligation to provide NFRs under get metrics for the PRD end points (although the obligation to report on the public admin end points remains).

The rules define both product data and consumer data request services as an "online service". The DSB can twist things however it likes but it's quite obvious a judge during a determination will assess an "online service" as something on the internet.

> The statement that proxying the PRD end points **is** equivalent to voluntary hosting is not the case. The DSB confirmed this understanding with stakeholders in the ACCC and Treasury prior to publishing the noting paper.

Then the DSB, the ACCC & Treasury are redefining the legal definition of an "online service" and this appears to be legally precarious in nature if applied to any other carriage service doing any other online activity.

> Statements have also been made indicating that it is technically difficult and costly to implement a simple pass through proxy for PRD end points. When the concept of AER and DELWP being designated for the PRD end points, as a way to reduce retailer implementation costs, was being consulted on the DSB asked whether a proxy model would be technically difficult and the feedback from retailers was that this would not be the case. 

**_Where_** was this stated by **_any_** retailer in **_any_** thread **_anywhere_**? Or is the DSB now going to refer to faceless "people" as the evidence to support this statement? If anything retailers appear to have raised issues with the specification on numerous occasions and were shutdown on the basis they were only intended to be delivered by AER & DELWP.

A search for the word _proxy_ on the Standards repository mentions proxy _zero_ times since 2019 so whatever narrative the DSB wishes to believe seems to be one of fiction:
![image](https://user-images.githubusercontent.com/4291448/178670347-b9f0011c-4378-4d8b-9ed7-e6dc3d02df1d.png)

>This feedback aligned with the experience in the banking sector where similar patterns are used to support OSPs and also aligns with a priori expectations. 

Once again, another conflation. The banking sector doesn't do a proxy model yet this is used as a factoid for justification.

>If a retailer's specific technical context makes a proxy model difficult, however, we would appreciate understanding the specifics that makes this the case. This would help us formulate guidance to reduce impact as the current position of the standards is based on the feedback previously received.

This isn't a decision proposal so is not a consultation, all I'll do is repaste what Biza.io already stated: _"A prudent action would be for the DSB to reopen consultation on these endpoints and reevaluate prior feedback in this new context if it intends to continue to suggest these endpoints must be functional at the Retailers published PublicBaseUri. Should the DSB choose to do this Biza.io will proceed to produce the change requests it believes are necessary to support this operating topology."_

It seems peculiar that the DSB now expects the Regulated party to solve for a clear technical deficiency in its design.

> It should also be noted that the patterns presented in the noting paper are intended to be helpful but not exhaustive or comprehensive. Any solution that meets the obligation that the base public URI exposes both the admin end points and the PRD end points would be sufficient. If we have missed a viable pattern that meets these outcomes we would happy to add it to the noting paper.

To be clear, the onus is on the DSB and the Chair to provide a **functional** data standard to comply with. In this matter it has failed to do so and as it continues to persist with it's apparent commitment to a forced implementation without rectifying the concerns raised this conversation is now bordering on the Chair failing to have consulted effectively on this topic.

**Comment by agl-cdrprogram** [comment]
The PRD noting paper 248 is in contradiction with rules & energy designation instrument. It has significantly expanded the scope of what is required to be done by data holder under the CDR Rules by including the facilitation of a product data request service. AGL’s position is that there is no legislative requirement in relation for data holders to provide a product data request service. AGL also does not consider the ‘Noting paper’ to be the appropriate vehicle to effectively make changes to requirements under the Rules.

**Alternative Option Proposed:** 
Noting Paper 248 is a technical workaround addressing a capability gap that could be addressed through an enhancement within Registrar. It would more effective and economical for the registrar platform to support multiple base-URIs instead of asking multiple retailers to do short term and long-term options.  

Please find attached more supporting information for reference. 

[PRD Changes & Impacts.pptx](https://github.com/ConsumerDataStandardsAustralia/standards/files/9109162/PRD.Changes.Impacts.pptx)

**Comment by CDR-API-Stream** [comment]
The Treasury have confirmed the following regarding this thread:
* As previously stated the facilitation of PRD endpoints is not equivalent to self hosting or the implementation of a Product Data Request Service
* The requirement under the standards that a single PublicBaseUri be used to access both PRD and Admin endpoints is not clearly enforceable under the rules for the initial retailers on the 15th November and is therefore not mandatory
* Voluntary implementation by Retailers is possible and would be welcome
* The Treasury rules team will seek to amend the rules in coming rules development cycles to ensure clarity of enforceability for this issue

**Comment by biza-io** [comment]
Biza.io thanks the DSB for clarifying this is not required as part of the current Rules setting. We look forward to collaborating with Treasury on how to technically and reasonably enable this service in the future.

**Comment by RubberDucky73** [comment]
Hi everyone, 

Excuse me for not reading every word of what is an extremely lengthy thread regarding Noting Paper 248, but I think I have already run into issues regarding this noting paper and trying to access custom PublicBaseUris for unauthenticated endpoints. Both the Origin and AGL PublicBaseUris no longer follow the same format prior to Nov 8th, and consequentially, the GET requests made using with these new PublicBaseUris are sending a 404 error; previously using the old format, they worked without a problem.

Does it seem like this is all related?

It would be great to have a standardised PublicBaseUri path for these endpoints like almost every retailer currently has. It makes data retrieval exponentially easier for data recipients and will minimise maintenance costs as more retailers join the Consumer Data Request Service.

From a data recipient standpoint having a standardisation to the PublicBaseUri is most preferable. More standardisation and no changes to essential endpoint paths. Trying to work with endpoints that keep changing the PublicBaseUri is pretty frustrating.

**Comment by perlboy** [comment]
Hi @RubberDucky73,

The Origin and AGL PublicBaseUri points at their own endpoints for the purposes of disclosing Status & Outages. This will be something which will repeat as more retailers come online as it is impossible to not implement Generic Plans _and_ provide these mandated endpoints. I highlighted this in [my April response](https://github.com/ConsumerDataStandardsAustralia/standards/issues/248#issuecomment-1099253779):

> PublicBaseUri is used for PRD information and the Status/Outages endpoints. This is noted briefly in Pattern 2 but is, in fact, a global requirement regardless of technical solution. There is potential for more flexibility on this requirement if the Register was to bifurcate PublicBaseURI into two separate base uris (PRD and Status/Outages)

The new uris _don't_ return 404 for the endpoints mandated on Holders (Status & Outages).

As a standalone question, most likely separated from this thread, there is an ambiguity that is present as to whether the Generic Plans **paths** are _actually_ in scope for the Standards because they aren't mandated. The implication here is that this would imply that other completely unrelated endpoints (like Banking endpoints for Energy providers, or Telco for Energy & Banking) should now also provide a Standards defined response. If this was the case it would result in a global CDR wide changes being required whenever _any_ endpoint is added which seems counterintuitive.

Once again, repeating the suggestion from April, the cleanest solution here if the government is so inclined is to bifurcate (ie. separate) the endpoints advertised for PRD/Plans from Status/Outages.

**Comment by RubberDucky73** [comment]
HI @perlboy, thanks for the quick reply. Yeah, I can't talk to the Status and Outages endpoints as I haven't used those yet. My issues are primarily with the PRD/plans endpoints. Though from my perspective of working with multiple endpoints, the more that the Uri paths are standardised and follow the same formatting, the easier my work has been up until this point. Apologies for the detour!

**Comment by jxeeno** [comment]
Hi all,

I've created a CR in standards maintenance to discuss separation of PRD and status/outage endpoints in the Register API.

https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/561
