### ISSUE TITLE
Decision Proposal 266 - Telco Balance and Usage Payloads

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#266]
This decision proposal contains a recommendation for the candidate payloads for the Balance and Usage data clusters for the telecommunications sector.

The decision proposal is embedded below:
[Decision Proposal 266 - Billing Balance and Usage Data Payloads.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/9596587/Decision.Proposal.266.-.Billing.Balance.and.Usage.Data.Payloads.pdf)

This consultation will be open for feedback until the 17th October 2022.

**Comment by CDR-API-Stream** [comment]
The decision proposal has been attached to the issue's [original comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/266#issue-1323599077).

**Comment by saif-akil** [comment]
Hi DSB,

As it stands, payments can only be allocated to the entire customer account and not to the multiple services that are associated with the customer account.  

An example of this is that a customer may have a separate NBN service and a separate mobile service, however only one invoice is issued in relation to both of these services.  

In order to address this issue, we propose that you amend the URI/telco/accounts/ balance, balance values for the "Service" as optional."

**Comment by perlboy** [comment]
Here's a summary of things I noticed in a few minutes of review:
- Internet connectivity can be metered in a directional fashion. That is to say `UNMETERED` seems to imply unlimited in both directions, this assumption is invalid. A _very_ common fixed internet plan in corporate is a quota for download and unlimited upload (or unlimited download, quota upload for data centre services)
- It's unclear how a pay per MB plan would be described, it is effectively `METERED` but the "remaining" upload/download is unlimited. It is actually quite common, at least in corporate plans but some retail ones, to have a 0MB commitment and a pay per MB. Unclear how this is displayed in the Balances List payload
- `voice.national` and `voice.international` are marked as mandatory but should be conditional if `planType` is `UNSUPPORTED`
- As per comments on internet MMS and SMS can have different `planType` based on destination. For instance unlimited domestic and unsupported international.
- There doesn't appear to be a "fair use" descriptor, these are quite common in retail environments
- There doesn't appear to be a "stepped" usage capability whereby the first X GB transferred are at full speed, the next Y GB are at throttled and beyond this service is terminated
- Total Duration of international voice calls is almost impossible to provide. Tariffs on international calls are always per country and often based on routing mechanism (physical line, satellite etc)
- Total number of SMS for international is almost impossible to provide. SMS (and MMS) are charged on a per country basis
- There doesn't appear to be support for addon packs altering a balance live. For instance a roaming charge with per country fees might apply unless the consumer chooses to signup for a $10/day international roaming cap, at which point characteristics change for the day which can either be set to unlimited or simply set a quota (ie. 500MB for the day)

**Comment by Telstra-CDR** [comment]
**Please review this in conjunction with #264 & #265 as there is common feedback across the proposals.**


_data.accounts[].[account.name](http://account.name/)_

The definition states "The display name of the product" which implies there is only 1 product applicable to an account. Would product apply at the 'service' level instead?
Consider removing this as an attribute for Telco.

_data.accounts[].account.services[].service.balances.balance_


is the intention to show the remaining balance available
If so, the description for the attributes need to reflect the requirements. The mix of language for different attributes is confusing. e.g.
•	“**Remaining** upload data in megabytes (MB).”
•	“**Amount** of data **used** overseas in megabytes (MB)”
•	“Total **duration** (hours, minutes, and seconds) of national voice calls”
•	“Total duration (hours, minutes, and seconds) of international voice calls **available**”
•	“Number of national SMS messages **remaining**.”
It looks like the want is three different things depending on the attribute:
1.	how many units are left/remaining (seems to be correct for a balance)
2.	how many units were used
3.	how many units were included in the plan


_data.accounts[].account.services[].service.balances.balance.data.download
and
data.accounts[].account.services[].service.balances.balance.data.upload_

What is the expectation when the data balance is shared for both upload and download? E.g. 40 GB data but we count both uploads and downloads towards the 40 GB.



__data.accounts[].account.services[].service.balances.balance.voice.international.duration_
Total duration (hours, minutes, and seconds) of international voice calls available. Required unless planType is UNSUPPORTED or UNMETERED
and
data.accounts[].account.services[].service.balances.balance.voice.international.number_
Number of international voice calls available Required unless planType is UNSUPPORTED or UNMETERED

Both of these are interested in international calls, which attribute captures the value for roaming?
Duration is a TimeString which limits the value to 23:59:59Z. how is time zone is useful and why we limit it to ~24 hours for a period.

_data.accounts[].account.services[].service.balances.balance.voice.international_
How do cater for situations where roaming calls are metered and there is an inclusion for IDD?

_data.accounts[].account.services[].service.usage.data.roaming_

consider rate/meter/charge applying for uploads as well as downloads.



_data.accounts[].account.services[].service.usage.voice.domestic_

The language has now changed to domestic and is different from National? 


_data.accounts[].account.services[].service.usage.voice.international_

“Calls made overseas” sounds like calls made when roaming. I assume the intent here is to capture international/IDD calls and roaming calls.

_Response Payloads_

Design Proposals #264 and #265 both return accountId as part of the account object but this proposal doesn’t. Should this be a consistent attribute across account objects since you need the list of accountIds in order to retrieve balance and usage for a specific accountId.
Also, in APIs where many accounts can be returned, there is no way to know which account the usage/balance is for.

_Response Payloads > data > accounts > account > services > balances > data > roaming_
Balance of data roaming charges. Required unless planType is UNSUPPORTED.

This would allude that the user has an active “roaming” service active even if they do not?

**Comment by CDR-API-Stream** [comment]
This consultation is now being closed for feedback.

As described in [Noting Paper 255 - Approach to Telco Sector Standards](https://github.com/ConsumerDataStandardsAustralia/standards/issues/255), next steps will be to:
* respond to the feedback already given
* integrate that into a draft standard including all of the designated data clusters
* open a holistic consultation to obtain further participant feedback.

**Comment by CDR-API-Stream** [comment]
Marking this consultation as `No Decision Made`.  While the proposal and feedback for this consultation have been incorporated into the draft standards this is not yet a formal decision of the Chair.
