### ISSUE TITLE
Decision Proposal 030 - Product Payloads

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards#30]
This decision proposal outlines a recommendation for the payloads for offered products as per the end points defined in decision proposal 017.

Feedback is now open for this proposal. Feedback is planned to be closed on the 1st November.
[Decision Proposal 030 - Product Reference Payloads.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/2498093/Decision.Proposal.030.-.Product.Reference.Payloads.pdf)

Please note the specific concerns. Also note that the date is very close to the scheduled date for publishing the first version of the standard.  As a result I will respond with an amended version based on feedback to date on the 26th October.

**Comment by JamesMBligh** [comment]
Please note, we have brought the feedback date back 1 day to allow for a draft standard to be published on the 2nd of November.

-JB-

**Comment by speedyps** [comment]
Just a question, there does not appear to be a link from an account back to a product.  Should a user of the API not be able to get details on which Product the account is part of?

**Comment by JamesMBligh** [comment]
This was a deliberate decision.  Once an account is created its conditions become static whereas the original product could change conditions over time (especially since some bank products can last decades).  As this is the case the product related fields that are relevant for an account have been included in the detailed payload.  Information such as constraints and eligibility have not been included as they are not applicable once an account is created.

-JB-

**Comment by da-banking** [comment]
**Discounts**
We will discuss how discounts are applied to fees below. However we want to call out that our ADIs make use of a feature where discounts are applied not just at the account level but at the customer relationship level. Some examples:
- For example Beyond Bank has a concept where customers who have been with them for more than 20 years are rewarded with [Life Membership](https://www.beyondbank.com.au/blog/2014/11/life-membership-beyond-bank/), where customers get additional discounted rates and fees.
- Many banks also give their own staff members discounts through the same mechanism.
- Similarly within business banking, a portfolio of accounts can attract different fees/discounts depending on the balance of the portfolio, not just the accounts.

In these scenarios, we would not be able to relate a discount to any one product specifically. It is defined against the customer. There are categories of customer, with different discounts for each category.

It seems that customer-level discounts do not fit well within the proposal which is product-centric by nature.

We are concerned that if we do not find a way to incorporate the customer-level discounts, then products that use this may incorrectly appear less attractive on comparison sites that use this data.

**Fees**
Fees are a very complex area of banking products. It appears that the only kind of fee considered so far is a fee that debits a discrete amount from a customer account. The following kinds of fees would also be in scope for the ADIs we work with:
- a penalty rate applied to the account balance.
- a penalty rate applied to a transaction amount.

Penalty rates could either be considered their own kind of thing `penaltyRates Array[Object]`, or as a kind of fee. We will assume the latter, and prefer that approach because they can be combined with discrete amount fees.

>Example 1: if a Visa card is used to make a purchase in a foreign currency, the customer may be charged *3% of the transaction amount*.
 
To support Example 1, we recommend that the `amount` field be made Conditional, and a new Conditional field be introduced `transactionRate` of type `RateString`, with one or other of the fields being mandatory. 
 
```
"fees": [
	{
		"name": "Foreign purchase",
		"feeType": "TRANSACTION",
		"transactionRate": "3",
		"additionalValue": "This fee is applied for purchases on a Visa card in currencies other than AUD"
	},
]
```

>Example 2: if a customer wants to make an early withdrawal from a Term Deposit product with a 5% interest rate, they might incur a fixed $25 penalty fee, and a -5% penalty rate, deducting all of the interest that would be payable on maturity.

To support Example 2, we recommend that the `amount` field be made Conditional, and a new Conditional field be introduced `balanceRate` of type `RateString`, with one or other of the fields being mandatory. We further recommend that fees with the same name be added more than once, to indicate that multiple fees can apply for the same condition.

```
"fees": [
	{ 
		"name": "Early Withdrawal",
		"feeType": "TRANSACTION",
		"amount": "25.00",
		"additionalValue": "You will be charged a penalty fee if you withdraw money from your term deposit before the maturity date"
	},
	{ 
		"name": "Early Withdrawal",
		"feeType": "TRANSACTION",
		"balanceRate": "5",
		"additionalValue": "You will not be paid any accrued interest if you withdraw money from your term deposit before the maturity date"
	},
]
```

>Example 3: if a customer wants to make an early withdrawal from a Term Deposit product with a 5% interest rate, they might incur a fixed $25 penalty fee, and between -1% and -4% of the interest that would be payable on maturity, depending on how much of the term remains. [Real Example](https://www.beyondbank.com.au/dam/document-repository/Disclosure-documents/fees-and-charges.pdf) - see section 30.

If the goal is to list the fees for a human to read and compare, then conditions can be documented in the `additionalInfo`. However in this final example, the condition is so complex that it really needs a tabular representation to be intelligible. Here's an attempt:

```
"fees": [
	{ 
		"name": "Early Withdrawal",
		"feeType": "TRANSACTION",
		"amount": "25.00",
		"additionalValue": "You will be charged a penalty fee if you withdraw money from your term deposit before the maturity date"
	},
	{ 
		"name": "Early Withdrawal",
		"feeType": "TRANSACTION",
		"balanceRate": "5",
		"additionalValue": "If you withdraw money from your term deposit before the maturity date, then: if less than 20% of the term has elapsed, then the accrued interest will be reduced by 80%; or if 20% or more but less than 40% of the term has elapsed, then the accrued interest will be reduced by 60%; or if 40% or more but less than 60% of the term has elapsed, then the accrued interest will be reduced by 40%; or if 60% or more but less than 80% of the term has elapsed, then the accrued interest will be reduced by 20%; or if 80% or more of the term has elapsed, then the accrued interest will be reduced by 10%."
	},
]
```

It might make sense to allow a markdown version of the `additionalValue`, however formatting text really ought to be controlled with the `HTTP Accept` request header, which would raise this concern to become its own endpoint, and each fee would need an ID. An optional `additionalValueMD` property might be the simpler way to go.

If a conditions syntax could be defined in the standards, we could support this, enabling machine-readable comparisons of products. Probably not a day 1 concern though.

**Fee discounts**
Since fees are not just of type `amount`, but also `transactionRate` and `balanceRate` (on the above assumptions), we would expect the same fields to be attached to the `discount` object.

If a fee has a `transactionRate` of 3%, then there might be a discount `transactionRate` of 1%, leaving a 2% charge.

**featureType**
ADDITIONAL_CARDS - we have no natural limit to the number of additional cards. We are unclear what value to place in the `additionalValue` field. Would null be appropriate?

Gaps:
- FREE_TXNS_ALLOWANCE - We support FREE_TXNS, however it is more common for our ADIs to specify a fee per transaction type, with different transaction types attracting different fees. The customer would then receive a periodic (i.e. monthly) allowance for $x of transactions, with transactions in excess of this amount being charged.
- DIGITAL_WALLET - whether or not the account can be attached to a digital wallet like Apple Pay, Google pay, Samsung Pay, FitBit Pay, Garmin Pay etc.
- NPP_PAYID - whether or not the account can be mapped to a PayID and receive PayID payments.
- NPP_ACCOUNT - whether or not the account can receive BSB/Account Number payments.
- DONATE_INTEREST - whether or not a proportion if interest accrued to this account can be donated. For example to a community group, or charity, etc.
- BILL_PAYMENT - whether ot not the account can be attached to an automatic budgeting and bill payment service.

**feeType**
This is problematic as we model all time ranges as _a period and a term_. ADIs can customise these any way they want and we cannot guarantee that we can map them into the enumeration defined. For example, an ADI could define a _period_ of WEEKLY with a _term_ of 2 and charge a periodic fee FORTNIGHTLY which would not fit into the enumeration below.

A better representation of a duration for a machine would not be an enumeration, but something like can be achieved within [ISO8601](https://en.wikipedia.org/wiki/ISO_8601#Durations). For example:
- DAILY - "P1D"
- WEEKLY - "P7D"
- MONTHLY - "P1M"
- QUARTERLY - "P3M"
- SEMI_ANNUALLY - "P6M"
- ANNUALLY - "P1Y"

And any others like:
- FORTNIGHTLY - "P14D"
- NINETY_DAYS - "P90D"
- THREE_YEARS_SIX_MONTHS_FOUR_DAYS - "P3Y6M4D" :-)

Some other scenarios:
- An overdrawn fee might be a $10 charge per day that the account is overdrawn. This could be modelled as `{ ... "feeType": "PERIODIC", "additionalValue": "DAILY", "amount": "10.00"}` however the condition is key. Should the condition be captured in free text in `additionalInfo` or in a machine-readable way?
- Some fees are not explicit. For example the cost of breaking a fixed rate loan needs to be calculated by a lending consultant who may have a delegated authority to waive or reduce. Should these fees be omitted, or how should they be included? Should `amount` be optional in these circumstances?

Here are some other triggers for fees that we support, that might be of interest for inclusion. We've noted how we would map them if they are not supported explicitly:
- Discharging a mortgage - `"feeType": "EXIT"`
- Cashing a cheque - `"feeType": "OTHER_EVENT"`
- Stopping a cheque - `"feeType": "OTHER_EVENT"`
- Ordering a new cheque book - `"feeType": "OTHER_EVENT"`
- Over the counter activities often attract higher fees for many activities than are charged for the same activity through a digital channel - probably just capture this in the fee `name` property.
- Business banking - fees per transaction in a batch of transactions - `"feeType": "OTHER_EVENT"`
- Transfering to externally held accounts - `"feeType": "TRANSACTION"`
- Fee per card attached to an account, for card holders over the age of 18 - `"feeType": "OTHER_EVENT"`
- Card replacement - `"feeType": "OTHER_EVENT"`
- Dishonour fee if the account balance was insufficient to meet a payment - `"feeType": "OVERDRAW"`
- Paper statements - `"feeType": "OTHER_EVENT"`
- Loan establishment - `"feeType": "OTHER_EVENT"`

**depositRateType**
Many banks have tiered interest rates, where there are several tiers of conditions, each attracting a different rate. We think this can be accommodated within the current design, but thought it worth including here for discussion.

For example a balance-based condition might be modelled like so:
```
"depositRates": [
	{
		"depositRateType": "BONUS",
		"rate": "3.25",
		"additionalValue": "The average balance is between $1,000 and $2,000 for the month"
	},
	{
		"depositRateType": "BONUS",
		"rate": "3.5",
		"additionalValue": "The average balance is between $2,000 and $3,000 for the month"
	},
	{
		"depositRateType": "BONUS",
		"rate": "3.75",
		"additionalValue": "The average balance is over $3,000 for the month"
	}
]
```

And a time-based condition might be modelled like so:
```
"depositRates": [
	{
		"depositRateType": "BONUS",
		"rate": "3.25",
		"additionalValue": "No withdrawals for 3 months"
	},
	{
		"depositRateType": "BONUS",
		"rate": "3.5",
		"additionalValue": "No withdrawals for 6 months"
	},
	{
		"depositRateType": "BONUS",
		"rate": "3.75",
		"additionalValue": "No withdrawals for 12 months"
	}
]
```

**eligibilityType**
Many banks have products that are aimed at children. We believe that a `MAX_AGE` should be defined to capture this.

**Comment by JamesMBligh** [comment]
Thanks @da-banking.  This feedback is awesome.  The need for a percentage fee is a gap that should be filled.  I'll have a go at updating fees and discounts accordingly.  Obviously these changes would also be applied to the detailed account payload also.

The customer level discounts are problematic.  Under the current model you would either:
1. Have a separate product type with an eligibility restriction indicating that it is for long-term customers or staff members
2. Add the discount details on every product they apply to

I have attempted to cover bundle specific discounts but I'll review to see if I can close any gaps identified.

-JB-

**Comment by anzbankau** [comment]
-      Some international banks may not have more details than a country in SWIFT reference data, so the "address" field should not be mandatory for the bankAddress.

-      For international payments beneficiary details like name & address are not mandatory.

-      Account and payId need to be classified as conditional?

-      CRN in biller should be optional, as some billers change CRN every billing cycle. So, CRN capture for those type of billers is not mandatory.

-      For US banks, an online channel can allow payments via "Fedwire number" (as well as CHIPS) and account number, which does not fit into the response payload.

-      Sharing of International beneficiary details may be subject the local privacy regulations of the beneficiary accounts’ domiciled country. i.e. MAS in Singapore.
-     Are the International payee fields in keeping with SWIFT standards? What is a routing number?  Swift code should say Beneficiary Bank BIC.  What is a chip number?

S/RC/RD (181031-1)

**Comment by anzbankau** [comment]
-	CRN in biller should be optional, as some billers change CRN every billing cycle. So, CRN capture for those type of billers is not mandatory.
-	Some international banks may not have more details than a country in SWIFT reference data, so the "address" field should not be mandatory for the bankAddress.
-	For international payments beneficiary details like name & address are not mandatory.
-	Account and payId need to be classified as conditional?
-	For US banks, an online channel can allow payments via "Fedwire number" (as well as CHIPS) and account number, which does not fit into the response payload.
-	Sharing of International beneficiary details may be subject the local privacy regulations of the beneficiary accounts’ domiciled country. i.e. MAS in Singapore.
-	Are the International payee fields in keeping with SWIFT standards? What is a routing number?  Swift code should say Beneficiary Bank BIC.  What is a chip number?

S/RC/RD (181031-1)

**Comment by anzbankau** [comment]
-	Feature type enum - We need to cater for limited periods? e.g. offset only available for first year on a fixed rate home loan.
-	Eligibility type enum - Other potential values Minimum income, Employment status and Residency/Visa.
-	Lending rate type enum – Propose additional types: REPAYMENT_TYPE = 'INTEREST_ONLY', 'PRINCIPAL_INTEREST'. Also need to support periods for which they apply.
-	How would a FX Cash product be mapped?

S/RC/RD (181031-3)

**Comment by MacquarieBank** [comment]
Macquarie has the following feedback on the Product Payload:
•         We think there would be value in adding an optional query parameter to be able to filter by business/personal. This could optionally be combined with account-category to filter for relevant products.
•         We think there would be value in adding a query parameter to filter products based on brand (white label). Although brands (white labels) could be handled by different URLs, this can become inefficient where a bank has a large number of brands.
•         For loan products, we think it would be of value to be able to specify in the request, the following details:
o    Loan purpose (Owner Occupied, Investment)
o    Repayment Method (Principal & Interest, Interest Only)
o    Borrowing amount (dollar amount)
o    Deposit Amount (either a percentage, or dollar amount)
The above values have a real impact on what rate is given to a client. Without this, it would be too complicated to return all combinations

**Comment by JamesMBligh** [comment]
As we are publishing tomorrow we’re being strict with feedback closure.  Here are responses to feedback provided.

**Features**
For the scenario suggested (offset only available for first year on a fixed rate home loan) it is expected that the additionalInfo field, which is free form, would be used to provide qualification information such as this.

I will add ACCESS_TO_DIGITAL_BANKING and change DEBIT_CARD to CARD_ACCESS.

I will change the REDRAW meaning.  I assumed this is how it would be interpreted.

OTHER seems like it would be hard to use for clients.  preference is to identify exactly what OTHER be would be used for and then we can add that.

**Eligibility**
I will added Minimum Income, Employment Status and Residency Status as enum values.

**Rates**
- I will add a repaymentType enum field with values of PRINCIPAL_INTEREST, INTEREST and NEGOTIABLE (if absent defaults to PRINCIPAL_INTEREST).  I believe that will meet the feedback.  It should also address the NAB feedback requesting this in the feature list.
- Tiered interest rates would be represented as multiple elements in the rates array.  For instance, if there were two rate tiers for a fixed term then there would be two elements with type set to FIXED_MONTHS - the additionalValue field would have different term lengths for each. 
- The BONUS type is supplied to accommodate rates for savings products dependent on the balance.  The base rate would be an element set to VARIABLE and the increment obtainable for maintaining a specific balance would be another element with type set to BONUS.
- For products with rates that can’t be published and are available on application you would use the isNegotiable flag
There may be Floating Rates where a loan may be for a fixed term but the rate changes more frequently.
- I will add additional types for FLOATING, MARKET_LINKED and CASH_ADVANCE.  My assumption was FIXED_YEARS can be accommodated by months times 12 but I can add it if people feel it is needed
- Happy to specify use of additionalValue field for COMPARISON if you give specifics.  What distinctions are required.  If it is arbitrary or bank specific then use additionalInfo.

**Query Parameters**
Addition of a business/personal query type would be a good addition.  It might be best to leave it to provider interpretation as to how business vs retail products are filtered as some products can be either.  Alternatively we could defined some categories as business and some as retail so that the business/personal parameter is a proxy for a series of categories.  Open to thoughts on this.

I will add a brand parameter for filtering and a brand field.

Adding query information to change the response data substantially changes the use cases and utility of these end points.  It effectively prevents the ability to cache the result set unless input parameters are assumed.  I would recommend selecting a representative set of input and then document that in the additionalInfo fields or in a linked page.  Alternatively multiple rates could be provided with different input assumptions included to get wider coverage.

**name**
This is the issue I had with productName.  It can be interpreted as a display value where the intention was that it would be a reference.  Taking the approach suggested creates a link between account and product which is specifically being avoided. productName should actually be productType and name here should be the display name.

**Optionality**
There have been no fields that have been created in any of the with the interpretation that they are discretionary.  Optionality is based on the data not being captured in all cases or not being able to be technically transformed to the required format.  Discretionary will not be added as an option at this stage.

**isNegotiable**
This flag does not solely mean that price is available on application as it could apply to any of the product options such as eligibility, fees, etc.  Also that is a really long field name.  Happy to change the field name if there is a succinct suggestion that aligns to the intent.

**Fees**
I will add feeCurrency and change the description to cover charges.  Feedback has already been provided earlier in the thread on expanding fees to cover percentage based fees.

I am not keen on adding OTHER as discussed earlier for features.  Please indicate the specific Fee types that are missing.

-JB-

**Comment by JamesMBligh** [comment]
This is a response to the comment provided by @WestpacOpenBanking on the account details proposal thread:
https://github.com/ConsumerDataStandardsAustralia/standards/issues/31#issuecomment-434970255

The suggestion of an alternate structure is valid and of interest.  Unfortunately it is now a little late in the consultation period to accommodate this feedback.  This would constitute a wholesale change and would warrant comment from the entire community.  As such it will not accommodated at this stage but can be considered via feedback to the draft as a whole.

More specific comment on the suggested alternative is as follows:
- A specific, mixin structure is where this payload should end up.  As there is no standardisation in this space at the moment the time required to get to that level of specificity and maintain a clean data structure made this approach infeasible.  This is why a key/value pair structure was adopted (as discussed in the proposal document).
- This structure has a specific advantage over mixin during a period of high volatility in that client implementations do not have to make significant changes to data storage schemas or processing code as the payload evolves.
- As we have the ability to iterate on the CDR end points by design it is anticipated that over the next eighteen months this payload will evolve.  Once the velocity of change has slowed and the structure becomes more settled we could consider transitioning to a fully specified JSON structure with strong typing.  I would not expect this to occur until the regime has spread to all ADIs and not just the majors.

Additional responses to feedback are below...

**Updating of product information**
It is up to the provider how changes in product information would be handled whether that is 
 done by changes to existing productIds or the creation of new ones.  All options are permissable.  It is also possible that there are multiple entries in the category for what the provider considers to be a single product type (for instance a mortgage that can be fixed or variable).  One bank may use multiple approaches for different types of product changes.  For instance updates to variable rates, which may happen daily, may be handled to a significant restructure of the application of fees that are being rolled out across the product portfolio.

In this context the productId is not immutable.  This is also why the concept of providerType was introduced (although feedback has indicated that field should be renamed).

There will be no specific standard for how long a provider may give no notice of a change or if they give any notice at all.  The effective date fields are provided to give flexibility to the provider and allow them to manage their offerings to the market with more control.

ETag can be freely used if desired as stated in the headers proposal.  The lastUpdated field still has utility beyond pure caching and not all providers will want to implement via this mechanism.

Removing pagination entirely invites problems for providers with a very large number of products (depending how they choose to represent tiering).  The suggestion to order by lastUpdated date is a good inclusion.

**URIs**
The idea of the URIs was to provide the ability to link out to a valid page for the product on various topics.  That page can easily contain links to many other pages.  For instance, a product that can be included in many bundles can be accommodated by a page that lists all of the available bundles and provides additional links to more detail on each of them.

**Features**
- A feature type of CHEQUE_BOOK will be added
- I will modify the use of additionalValue for additional cards to accommodate unlimited

**Eligibility**
- If there are specific additions then they need to be articulated.  I'm not sure how to implement the feedback provided regarding turnover and eligibility.
- Max age will be added as per DA feedback
- A STUDENT criteria will be added to eligibility

**Deposit rates**
- Yes, the BONUS depositRateType can used to capture tiering or banding of rates and if the bonus is time limited.  Especially if the tiering is based on a constant base rate.  An alternative would be to have multiple alternate rates that have different eligibility criteria articulated in additionalInfo.
- Will add INTRODUCTORY to deposit as it is for lending

**Lending rates**
- Will change HONEYMOON to INTRODUCTORY
- Will update the description of DISCOUNT and PENALTY additionalValue to be more specific
If there are more lending rates required please be specific as to suggestions.

**Fees and discounts**
I don't think a BUNDLE discountType should be used to describe a discount on another product.  Only the product being referred to.

**Other Comments**
- The ability to host unauthenticated APIs independently from authenticated APIs will be considered. 
 It was not specifically the intention of the URI structure proposal to prevent this but the language does imply this.
- A brand field will be added
- In all the payloads we have Guidelines on the expected length of description and other text fields might help to increase the usefulness of these fields for data consumers
- Length of strings have not be stipulated for any of the read only fields.  Guideline is that content length should be reasonable for the context.  In most cases this is not an issue as there are existing constraints that reasonably limit size.  In this case text could potentially get out of hand.  Additional guidelines will be considered.
- Closed account for current customers are in scope as has been stated in the account proposal

-JB-

**Comment by JamesMBligh** [comment]
The finalised decision for this topic has been endorsed. Please refer to the attached document.
[Decision 030 - Product Reference Payloads.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/2551706/Decision.030.-.Product.Reference.Payloads.pdf)

-JB-
