### ISSUE TITLE
Decision Proposal 306 - Updates to Banking Product and Account Detail 

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#306]
The attached document describes proposed updates to Banking Product and Account Detail schemas.

[Decision Proposal 306 - Updates to Banking Product and Account Detail.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/11828209/Decision.Proposal.306.-.Updates.to.Banking.Product.and.Account.Detail.pdf)

~~Consultation on this proposal will close on 28 July 2023.~~

Following an [extension request](https://github.com/ConsumerDataStandardsAustralia/standards/issues/306#issuecomment-1652854175), consultation on this proposal will close on **11 August 2023**.

**Comment by CDR-API-Stream** [comment]
The [opening comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/306#issue-1713044240) has been updated and the Decision Proposal is now attached.

The Data Standards Body welcomes your feedback.

**Comment by nils-work** [comment]
This decision proposal references the following issues from [Standards-Maintenance](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues): 
- [Determining Interest Rate of BankingTermDepositAccount #132](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/132)
- [Product Reference Data - Residential Mortgage package discounts #283](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/283)
- [Product Reference Data - revert rates for fixed rate mortgages are absent #284](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/284)
- [Product Ref Data - leeway within standards makes fee comparison difficult #285](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/285)
- [Credit card balance plans and payment hierarchy: inadequate information within the CDS #292](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/292)
- [Update description of features[].isActivated to remove default #316](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/316)
- [PRD - Constraint types #387](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/387)
- [Additional credit card fields #471](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/471)
- [Define new Loan Repayment Type to relevant schemas #531](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/531)
- [Optionality of critical fields is facilitating data quality issues across Data Holder implementations #566](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/566)
- [BankingProductLendingRateV2 - Lending Rates – FIXED/INTEREST_ONLY period end date cannot be determined #567](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/567)
- [Home Loan Revert rate and product is not available #569](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/569)
- [Clarify Base and Adjustment Rate Types #585](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/585)
- [Add structured fields for rate applicability #588](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/588)

**Comment by perlboy** [comment]
Will review this internally but I think my first question would be what consideration there is for NBL related changes in this proposal. Based on the suggested FDOs the ecosystem could run out of windows to make further changes should they be required for NBL on overlapping endpoints.

**Comment by nils-work** [comment]
Hi @perlboy 

Yes, some consideration has been given to the introduction of Non-Bank Lending (NBL) in this proposal, including the addition of card details and allowing for more specific rate information for distinct account types.

Obligation dates for future changes to the same endpoints would be consulted on as necessary, and aligning to these dates would be an option.

**Comment by perlboy** [comment]
> Yes, some consideration has been given to the introduction of Non-Bank Lending (NBL) in this proposal, including the addition of card details and allowing for more specific rate information for distinct account types.

Ok, but what about things like BNPL? I'm reticent to start trying to tackle that sector but also cognoscente of the likely timeline challenges.

> Obligation dates for future changes to the same endpoints would be consulted on as necessary, and aligning to these dates would be an option.

This seems to pre-suppose implementers for NBL wouldn't be the _same ones_ for Banking. The reason this matters is that layering FDOs between Banking/NBL is likely to be highly problematic for providers of solutions operating in both (all) sectors. This is where my initial question came from because either FDOs are layered and implementors may respond by indicating they cannot service NBL (leaving _very_ few options in market) or NBL FDOs are stuck behind bank ones for overlapping endpoints (leaving just Q3/Q4 2024 available).

**Comment by da-banking** [comment]
DA have reviewed the contents of the Decision Proposal.
Changes to our core systems will be required to achieve what is being proposed.

DA Banking would like to propose that the obligation date of these changes be adjusted to accommodate the need to perform development on our core systems.
We propose the following:
-	Product Catalogue changes – required by **15/07/2024**
-	Get Account Detail changes – required by **31/12/2024**

This would provide significant benefit to our client group, who are constantly in a state of UAT for compliance work (not limited to OB). 
It would also enable the core system changes to be fully scoped, tested and implemented.

**Comment by biza-io** [comment]
Due to the complexity of the decision proposal and resource constraints Biza.io request an extension on providing feedback.

**Comment by nils-work** [comment]
At the request of @biza-io, consultation on [Decision Proposal 306](https://github.com/ConsumerDataStandardsAustralia/standards/issues/306) will be extended by two weeks to **11 August 2023**.

As there are some areas of this proposal that may become relevant to the NBL sector, participants are encouraged to review it in conjunction with [Decision Proposal 316 - Non-Bank Lending sector alignment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/316).

**Comment by cuctran-greatsouthernbank** [comment]
Great Southern Bank welcomes the opportunity to provide feedback on Decion proposal 306 - Updates to Banking Product and Account Detail.

We have carefully considered the proposal given our size, delivery capacity and availability of data in our systems. Overall, this is a very big piece of work for Great Southern Bank to deliver.

Below is our feedback regarding the scope and timeline for the proposed changes.

**Group 1 - Get Products and Get Product Detail**
We support both the proposed changes and the changes for consideration. 
We request the timeline for this change is July 2024.

**Group 2 - Get Account Detail - loan UType**
We support the proposed changes in this group including the changes for consideration.
However, we'd like to request a separate version of Get Account Detail for this group to ensure adequate analysis and testing. Requested timeline for this change is September 2024.

**Group 3. Get Account Detail – creditCard UType** 
This is the most complex change for us to implement as we do not have the information required locally stored. We will have to fully scope out the change with our card management vendor. The implementation cost is unknown to us at this stage. Therefore, we request a separate version of Get Account Detail for this group with obligation date beyond 2024.

**Group 4. Get Account Detail – termDeposit UType and Group 5. Get Account Detail – other account types** 
We support the proposed changes in this group with the implementation timeline being November 2024.

**Comment by WestpacOpenBanking** [comment]
Westpac welcomes the opportunity to provide feedback. Please find our response to the proposals attached.
[DecisionProposal306 Feedback.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/12256434/DecisionProposal306.Feedback.pdf)

**Comment by nils-work** [comment]
Hi @WestpacOpenBanking 

Thank you for your feedback.

On your response to the proposal relating to [#471 - Additional credit card fields](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/471); the proposal did not suggest the inclusion of cardholder name or card expiry date. Examples of the proposed detail were provided on page 8 and 12 of the [proposal](https://github.com/ConsumerDataStandardsAustralia/standards/issues/306#issue-1713044240) (extracts below).

**Get Products**
``` diff
"cardArt": [{
 "title": "string",
 "imageUri": "string",
+ "cardScheme": "AMEX / DINERS / EFTPOS / MASTERCARD / VISA / OTHER; mandatory",
+ "issuer": "string; mandatory",
+ "cardType": "CHARGE / CREDIT / DEBIT; mandatory"
 }],
```

**Get Account Detail**
``` diff
 "specificAccountUType": "creditCard",
 "creditCard": {
+ "cardScheme": "AMEX / DINERS / EFTPOS / MASTERCARD / VISA; mandatory",
+ "cardType": "CREDIT / CHARGE / DEBIT; mandatory",
+ "issuer": "string; mandatory",
+ "cardLimit": "AmountString; optional",
+ "repaymentHierarchy": ["subAccountId", "subAccountId", ...],
```

**Comment by aj-mozo** [comment]
On https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/285, @nils-work posed a question about fee comparability which I'd like to reply to as part of the request for comment in Decision Proposal https://github.com/ConsumerDataStandardsAustralia/standards/issues/306:

**1.  Are you able to provide examples of the most important or common fee types that are difficult to group and/or compare currently?**

Mozo believes that without significantly improved standardisation of the categorisation of fees, the CDR PRD dataset remains unusable for the programmatic comparison of products within an AFSL or ACL regulated environment.

Today there are just over 12,000 individual fee records in the Product Reference dataset of banking category TRANS_AND_SAVINGS_ACCOUNTS. 

Of those, just over 50% are EVENT based fees.
Unfortunately:

(a) There are 1,019 unique fee names given to those 6,300-odd EVENT fees. It's unclear what process PRD users are expected to use, to make any sense of 1,019 unique free text entries.

(b) Among the fees labelled as EVENT fees are things that should **not** be be categorised as Event, including:
- account keeping fee (20 instances; should be PERIODIC)
- administration fee (12 instances; should be PERIODIC)
- ATM withdrawal fee (21 instances under 5 different names, should be WITHDRAWAL/TRANSACTION)
- countless other transaction fees including bpay, cheque, branch withdrawal, transaction fee and plenty more (and I do mean **countless**, because there's no firm logic I can use to identify which of the fees labelled as event fees are actually not events fees).

Another approx 25% of fees are labelled TRANSACTION.
Unfortunately:

(a) There is a fundamental logic flaw in the fee type naming schema: withdrawals, deposits, purchases and payments are subsets of the class 'transactions'. There is no consistency in how Data Holders determine whether a withdrawal transaction is a withdrawal or a transaction. With 598 unique TRANSACTION fees names plus another 335 unique fee names across the 4 subsets of transactions, and no consistency in the definition of fee type itself, comparability of fees is not possible.

I've attached a spreadsheet containing all 12,000 fees, and some simple analyses.
[CDR PRD fee names and types trans_savings 20230810.xlsx](https://github.com/ConsumerDataStandardsAustralia/standards/files/12311097/CDR.PRD.fee.names.and.types.trans_savings.20230810.xlsx)

**Comment by aj-mozo** [comment]
Also on https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/285, I posted my concern that it is not possible to determine whether the **absence of a fee** from a PRD record means that no fee is charged or that the action is not available or that the data is incomplete. I'd like to reiterate this point as part of the request for comment in Decision Proposal https://github.com/ConsumerDataStandardsAustralia/standards/issues/306:

Mozo believes that without significantly enhanced guidance and regulatory enforcement around definition and completeness of data, the CDR PRD dataset remains unusable for the programmatic comparison of products within an AFSL or ACL regulated environment.

I will simply give you a current example to demonstrate that the standards and/or compliance with standards is too loose for the data to be used to power reliable, accurate and compliant consumer information. It is worth noting that this example has been live in the market for at least 3 years:

**Commbank Smart Access versus ANZ Access Advantage**

Here's the fees that Commbank list in their PRD API for their transaction account:
- Unpaid cheque or debit fee | 5 | EVENT
- Stop payment fee | 15 | EVENT
- Unpaid scheduled payment fee | 5 | EVENT
- Transaction listing or ad-hoc paper statement fee | 2.5 | EVENT
- Overdraw Fee | 15 | EVENT
- CBA ATM cash withdrawals in Australia | 0 | EVENT
- Account fee | 4 | PERIODIC
- Paper Statement Fee | 0 | PERIODIC
- Paper Statement Fee - Standard Cycle | 0 | PERIODIC
- Access fee - Overseas purchases |   | PURCHASE
- Cheque negotiated fee | 3 | TRANSACTION
- Access fee - Overseas ATMs | 2 | WITHDRAWAL
- Access fee - Overseas cash withdrawals |   | WITHDRAWAL
- Access fee - Overseas cash withdrawals | 5 | WITHDRAWAL
- Staff assisted withdrawals | 3 | WITHDRAWAL

And here is the complete list from the ANZ account: 
- Account Service | 5 | PERIODIC

Do you see the problem? ANZ charges many of the same fees as Commbank if you read page 11-12 of their booklet at https://www.anz.com.au/content/dam/anzcomau/documents/pdf/personal-account-fees-charges.pdf. But ANZ's CDR does not show this.

If ANZ was to publish a booklet containing just the 1 fee they would be engaging in misleading conduct.
If I was to power a consumer-facing comparison with those fees I would be engaging in misleading conduct.

Why is the CDR data allowed to operate below the standards required elsewhere in the industry? If it is intended to be consumer-facing data then it needs to be held to the same standards as a PDS, website or advertisement. I urge the DSB to do more work in this area.

**Comment by nils-work** [comment]
Hi @WestpacOpenBanking 

Regarding your response to the proposal relating to [#132 - Determining Interest Rate of BankingTermDepositAccount](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/132); the proposal provided an example of the proposed change to Account Detail for a Term Deposit in Appendix 4 at the top of page 13.

In summary, it proposed to include the rate detail alongside each term deposit object, allowing for different rates on different terms, rather than leaving the single `depositRates` array applying to all term deposits. This was in response to the scenarios provided in [issue 132](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/132).

**Comment by NationalAustraliaBank** [comment]
NAB welcomes the opportunity to provide the feedback for the issues collated in Decision Proposal 306. NAB has reviewed the contents of the Decision Proposal and due to implementation complexities. Changes to our core systems will be required to achieve what is being proposed.
NAB proposes the following:
* Product Catalogue changes by 31st July, 2024
* Get Account Detail changes by 31st December, 2024
 
#567 BankingProductLendingRateV2 - Lending Rates – FIXED/INTEREST_ONLY period end date cannot be determined
NAB’s Feedback: NAB supports Option 1 to provide two new date fields at the top of the [BankingProductLendingRateV2](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingproductlendingratev2) schema.
 
#569 Home Loan Revert rate and product is not available
NAB’s Feedback: We support Westpac’s feedback which states “Revert rate is subjected to market conditions and can vary from what was fetched at the time of API call to when the loan gets converted from fixed to variable.”


#316 Update description of features[].isActivated to remove default
NAB’s Feedback: We support Westpac’s and ANZ feedback. We agree, the isActivated field should be limited to the traditional boolean semantics implied by the 'is' prefix - with 3 values: True, False, Unknown/Not Applicable to support broad range of products and complex to determine activation status.

 
#132 Determining Interest Rate of BankingTermDepositAccount
NAB’s Feedback: We support Westpac’s feedback which states “DSB to provide workable examples and guidance for any structural changes planned to the APIs to further analyse the issue”

**Comment by anzbankau** [comment]
ANZ's response to this decision proposal has been uploaded: 
[ANZ feedback on DP306.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/12319243/ANZ.feedback.on.DP306.pdf)

We appreciate all the sample payloads provided in the change proposal and the considerable work that went into combining so many disparate change proposal with wide-ranging levels of detail.

**Comment by CDR-API-Stream** [comment]
The DSB are providing the linked response on behalf of CBA:
[CBA Responses - Decision Proposal 306 - 11 Aug 2023.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/12319467/CBA.Responses.-.Decision.Proposal.306.-.11.Aug.2023.pdf)

**Comment by nils-work** [comment]
Hi @anzbankau 

It may not change the general context of your feedback, but there appears to be an incomplete sentence near the top of page 11 of your submission, starting:
> While we recognise that termDeposit was changed

Would you like to provide any missing detail?

**Comment by anzbankau** [comment]
Thanks for picking this up @nils-work.

Please ignore the incomplete sentence for #132. It was intended to point out that the `termDeposit` property in [BankingAccountDetailV3](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingaccountdetailv3) schema was changed from an object to an array without pluralising the name. Our suggestion to have a `subAccounts` array for the more general case would no longer require a `termDeposits` array because the anonymous subAccount object can be of any type (unless constrained by a homogeneous collection convention).

## Conceptualisation of SubAccounts and Stages
The following snippets are provided only to demonstrate how the product/account phases and subAccount concepts described in [our response](https://github.com/ConsumerDataStandardsAustralia/standards/issues/306#issuecomment-1674308416) might be represented. They are not intended to form part of a proposal, to encompass all the change proposals in this decision proposal (original or as suggested in this response) or to be in any way complete. They should be the subject of a separate decision proposal, given the substantial change suggested (though intended to be simpler to produce and consume than the related proposals in this decision proposal).

### SubAccounts Example (subset)
```diff
{	"productCategory": "TERM_DEPOSITS             // Note: New enum(s) may be required for heterogeneous collections",
	"accountId": "string",
	"specificAccountUType": "termDeposit           // For a homogeneous collection",
#	"//Note: Additional fields representing the collective account": "",
+	"subAccounts": [{
		"specificAccountUType": "termDeposit      // For a heterogeneous collection",
+		"subAccountId": "Id Permanent",
		"lodgementDate": "string",
		"maturityDate": "string",
		"depositRateType": "FIXED",
		"standardRate": "RateString; mandatory",
		"effectiveRate": "RateString; mandatory",
		"calculationFrequency": "ExternalRef ISO 8601 Durations; optional",
		"applicationFrequency": "ExternalRef ISO 8601 Durations; optional",
		"depositRates": [{
#			"// Note.1: depositRateType excluded because provided at sub-account level": "FIXED",
#			"// Note.2: calculationFrequency excluded because provided at account level": "string",
#			"// Note.3: applicationFrequency excluded because provided at account level": "string",
```

### Stages Example (subset)
```diff
{	"productCategory": "RESIDENTIAL_MORTGAGES",
	"accountId": "string",
	"specificAccountUType": "loan",
#	"//Note: Additional fields representing the collective account e.g., lendingFacility{}": "",
	"loan":
		{
			"startDate": "string              // Replaces originalStartDate since it's above the stages",
			"loanAmount": "string        // Replaces originalLoanAmount",
			"loanCurrency": "string       // Replaces originalLoanCurrency",
+			"stagesRate": {
#				"//Note.1": "Applies to all stages. Exclude property if in a stage as overriding would be inaccurate.",
				"calculationFrequency": "string",
				"applicationFrequency": "string",
				"interestPaymentDue": "IN_ADVANCE"
				},
			"stages": [
+				{	"stageSequenceNumber": 1,
+					"stagePeriod": "DateTimeString, optional                     // Product, replaces fixedPeriod",
+					"stageStartDate": "DateTimeString, optional                // Account",
+					"stageEndDate": "DateTimeString, optional                  // Account",
+					"stageName": "Fixed Rate Period",
+					"stageType": "FIXED",
					"lendingRateType": "FIXED",
					"standardRate": "RateString; mandatory",
					"effectiveRate": "RateString; mandatory",
					"lendingRates": [{}]
				},
+				{	"stageSequenceNumber": 2,
+					"stageStartDate": "DateTimeString, optional                // Account",
+					"stageEndDate": "DateTimeString, optional                  // Account",
+					"stageName": "Variable Rate Period",
+					"stageType": "VARIABLE",
					"lendingRateType": "VARIABLE",
					"standardRate": "RateString; mandatory",
					"effectiveRate": "RateString; mandatory",
					"lendingRates": [{}]
```

**Comment by nils-work** [comment]
The DSB would like to thank participants for their valuable engagement and feedback on this proposal.
Submissions will now be considered and any outcomes from the consultation will be shared in due course.

**Comment by nils-work** [comment]
A decision has not yet been made on this proposal and an update will be provided once feedback on [BNPL](https://github.com/ConsumerDataStandardsAustralia/standards/issues/317) can also be considered.

The following two issues were consulted on in MI16 and the proposed changes to the Standards will be made together with the changes expected from DP306.
- [#593 - Interest paid at maturity guidance for applicationFrequency in BankingProductDepositRate](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/593)
- [#595 - Use of additionalValue field in Product Eligibility Types](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/595)

**Comment by CDR-API-Stream** [comment]
Decision 306 has been made by the Data Standards Chair:
[Decision 306 - Updates to Banking Products and Accounts - Candidate Standard Approved.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/13331281/Decision.306.-.Updates.to.Banking.Products.and.Accounts.-.Candidate.Standard.Approved.pdf)
 
This decision resulted in version 1.28.0 of the Data Standards being published on 10 November 2023, including a [Candidate Standard](https://consumerdatastandardsaustralia.github.io/standards/includes/additional/candidates/dp306/banking-dp306.html?diff) to represent the changes proposed and feedback received on this issue. The Candidate also includes elements proposed in the Non-Bank Lending [Draft Standards](https://consumerdatastandardsaustralia.github.io/standards/includes/additional/drafts/non-bank-lending/banking-non-bank-lending.html?diff) for completeness, as described in the [Release Notes](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.28.0.html#v1-28-0-release-notes).
 
More detail about Candidate, Draft and Experimental Standards is provided in the [Additional Standards](https://consumerdatastandardsaustralia.github.io/standards/index.html#additional-standards) section.

Further consultation on the Candidate Standard will continue in [Decision Proposal 338](https://github.com/ConsumerDataStandardsAustralia/standards/issues/338).
