### ISSUE TITLE
Noting Paper 308 - Categories of Standards

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#308]
This noting paper outlines a more formalised mechanism for the DSB to label standards at different levels and how they will be published by the DSB:
[Noting Paper 308 - Categories of Standards.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/11752718/Noting.Paper.308.-.Categories.of.Standards.pdf)

In the next version of the standards, these categories will be used to manage the emerging Non-Bank Lending standards and the postponed Telco standards.

While this is not a formal consultation we are open to feedback on this approach.

**edit:** In response to feedback, the noting paper has been slightly modified in relation to version management resulting from changes to candidate standards

**Comment by biza-io** [comment]
We fear without some rationalisation on tooling this is going to make the convoluted outcomes observed in standards-staging much much worse. This proposal for change has been suggested as a Noting Paper but appears to fundamentally change the acknowledged release process. Biza has significant concerns with the ambiguous nature of this Noting Paper and the implications on the Standards and more broadly the CDR ecosystem.

Immediate areas we see as problematic are:
- **Versioning**: Experimental has an entirely independent version, Draft/Candidates are being shipped as patch release but Binding Standards may have a major, minor or patch version change. This versioning approach will be very confusing to any mildly engineering focused person. We suspect a more effective mechanism for progression would be to breakdown the Standards into component pieces and instead bind each component individually. This is similar to the RFC approach whereby one RFC extends/changes/evolves prior RFCs over time.
- **Binding timeline**: There is no definition of binding timelines provided and yet every release up to Candidate standards requires no formal approval by the Chair. It is unclear how the Chairs obligations regarding having consideration for feedback provided are expected to be achieved or at what stage.
- **Definition of Material vs. Non-Material change**: It continues to be very ambiguous as to what a material and non-material change is and this sequence flow seems to dilute this further. It is of significant concern that non-material change can be made without the Chairs approval and yet there are multiple live examples of a non-material change evolving into needing a Decision Proposal to rectify.
- **Participation**: The convoluted nature of the versioning approach is likely to impact further participation in the development of Standards. It is going to be very unclear to organisations what resourcing they should allocate and at what stage. This will have the net effect of delaying the Go-Live date of changes because organisations will likely not evaluate the change until it is made binding.
- **Promotion of changes**: It is unclear how promotion of changes will effectively work. There is significant evidence to suggest that, perhaps unintentionally, changes have been lost during source control merges. We fear this will accelerate this further.
- **Decision Proposals**: There is precisely zero references to Decision Proposals in this Noting Paper. It seems this paper has been produced seemingly in isolation of the existing process. Decision Proposals form the backbone of the change process with regards to interaction with the CDR Rules so it’s unclear why this Noting Paper doesn’t actively mention it.

We believe the issues in this Noting Paper are significant enough that the DSB should formally consult on the approach to changing the Data Standards as the content of this Noting Paper appears to cause more questions then those answered.

**Comment by CDR-API-Stream** [comment]
In response to @biza-io:

There will be literally no change on any of the topics listed resulting from this labelling approach.  This is really only formalising the approach previously taken for banking, energy and telco.

**Comment by JamesMBligh** [comment]
I believe we have been pretty public and transparent with our processes as they have evolved so I'm not sure what specifically the feedback is about on that front.  If there are processes that are unclear we can fix that.

I'd be specifically interested in understanding how the Noting Paper is divergent from what we have done in the past.

I reviewing the document in light of this feedback I have noticed that we are saying that material changes to candidate standards requires a decision of the chair be we allow for that to be a patch version.  I think that is probably an error on my part and is a copy past from the draft standards section.  It should be that a change resulting from a decision is a minor version change.

Is there concern about experimental standards being on a separate version?  I thought that was appropriate as we are considering experimental standards to be transient so they will be rapidly created, changed and decommissioned.  We didn't want to let these experiments to muddy the waters for the enforceable standards.
