### ISSUE TITLE
Decision Proposal 316 - Non-Bank Lending sector alignment

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#316]
This decision proposal assesses the alignment between the existing Banking and proposed Non-Bank Lending sector requirements.

[Decision Proposal 316 - Non-Bank Lending sector alignment.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/12157881/Decision.Proposal.316.-.Non-Bank.Lending.sector.alignment.pdf)

Consultation on this proposal will close on **Friday 25 August 2023**.

**Comment by CDR-API-Stream** [comment]
The [opening comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/316#issue-1809135448) has been updated and the Decision Proposal is now attached.

The Data Standards Body welcomes your feedback.

**Comment by Australian-Finance-Industry-Association** [comment]
**AFIA Design Proposal 316 response**
The Australian Finance Industry Association (AFIA) notes that Decision Proposal 316 (DP316) has been released prior to draft Consumer Data Right (CDR) rules being released for the non-bank lending (NBL) sector.
AFIA further notes it is difficult for the NBL sector to interpret the data standards without the context of the CDR rules.  Accordingly, we do not agree with DP316 being released or considered at this time and recommend this be delayed until the NBL sector has had sufficient time to consider the CDR rules and for these rules to be finalised. 
The banking sector has had 3 years to consider rules, standards and implement functionality.
AFIA seeks further information as to why the data Standards for NBL are being considered at this point in time, prior to the release of the CDR Rules for NBL. We strongly suggest that the order of sequencing should be reversed, so that the Data Standards for NBL are only released after the CDR Rules for NBL have been subject to consultation and finalisation.   
We have further comments on some of the problems that DP316 presents.
DP316 leans towards standardisation of taxonomy between the banking and non-bank sector.  This assumes a like-for-like comparison of customer, product and transactional data between the two, which is incorrect.
We note that the relationship between banking and non-bank lending sector is not simple – the latter is not simply derivative of the former.
By definition ‘non-bank’ lenders are not banks.  Many members do not hold deposits, have transaction accounts, generate balances that fluctuate daily or otherwise hold the type of data that banks typically hold.
While some NBL products may have close analogues in banking, or even essentially equivalent offerings such as credit cards and personal loans, many do not. Some NBL products differ entirely in structure, purpose and provision from any banking products, which may render existing banking standards inapplicable for those products.
For example, leasing and fleet products are completely dissimilar to banking and often subject to regular variation across the life of an agreement. Therefore, they do not lend themselves to having the banking data standards applied to them. 
Examples of this issue can be readily drawn from the consultation questions in this design proposal, for example question 12: “Is the proposed alignment of the Direct Debits, Scheduled Payments and Payee endpoints appropriate, or are there further considerations for NBL?”. Non-bank lenders by their nature do not offer transaction accounts to their customers, so at least “Direct Debits” are inapplicable. It is conceivable that “Scheduled Payments” and “Payee” endpoints could be used for related concepts – perhaps to indicate a merchant – but it may be prudent to avoid forcing semantically distinct data into inappropriate systems that were specifically designed for a unique product class, i.e. transaction accounts.
A NBL lacking the product requirements of, for instance, transaction accounts will also not have the resulting technical build, as it is not necessary for their business. For example, an NBL may operate on a daily batch cycle in processing transactions, rather than processing intraday balance changes. This would mean that they would not have the ability to respond to such API calls.
The work of the Open Banking rollout should be leveraged wherever possible to align with the rollout to NBL.  However, a distinction should remain between the two which recognises that the products and industry differ. 
To that end, AFIA suggests that the NBL standards should be established separately, using the initial foundation of the banking standards which will need to be adapted to NBL as it exists today. As banking and NBL products and industries develop into the future, necessitating rule updates and maintenance, banking and NBL rules should be codeveloped as appropriate, rather than changes in the former automatically affecting the latter.
Additionally, this would mean that a different industry path would be required to allow for distinct API endpoints and standards.  However, this should only occur following the finalisation of CDR rules for the NBL sector.
This approach, where the Data Standards for the two sectors are completely separate, is preferable to avoid issues with version control or the need to ‘switch off’ certain aspects of the standard for the NBL context.

**Comment by nils-work** [comment]
For reference, the exposure draft rules to expand the CDR to the non‑bank lenders sector have been published - 
[Consumer Data Right rules – expansion to the non-bank lending sector](https://treasury.gov.au/consultation/c2023-434434-expansion)

**Comment by CDR-API-Stream** [comment]
In response to the feedback from the @Australian-Finance-Industry-Association...

The parallel development of rules and standards has been a feature of the CDR since inception and has proved to be an effective approach to ensure that the rules can take into account some of the practical issues and concerns that are only uncovered when the detailed technicalities are examined.  This is how the standards for both the banking and energy sector were developed.

This approach was outlined in [Noting Paper 292](https://github.com/ConsumerDataStandardsAustralia/standards/issues/292), in February, and feedback on the approach was requested at that time.

We have been looking in detail at the variations between bank and non-bank data structures for most of this year and are very sensitive to the potential for these differences.  We would welcome an ongoing engagement with the AFIA to help dig into these issues.  For the previous sectors the ABA, COBA and AEC were instrumental in helping ensure the standards were developed with a clear understanding of the nuances and specific needs of the current holders of the data.

**Comment by commbankoss** [comment]
CBA feedback to DP316 attached.
[CBA Response to DP316.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/12437011/CBA.Response.to.DP316.pdf)

**Comment by perlboy** [comment]
> The issue related to Energy PRD in the NBL consultation is to address issues arising the go live of the initial energy retailers last year. This issue came to the fore and was discussed in [Noting Paper 248](https://github.com/ConsumerDataStandardsAustralia/standards/issues/248).

For clarity the Noting Paper only further highlighted that the DSB hasn't designed an appropriate mechanism for forwarding nor has it consulted on one. Does the DSB intend to consult on this in the same way it is consulting on NBL Standards _ahead_ of Rules?

> At that time the Treasury indicated that they would seek to amend the rules in the future to resolve the issue and this has now been included in this consultation.

But it isn't mentioned _anywhere_ in this Decision Proposal. It seems appropriate this discussion is split into a standalone Decision Proposal so energy participants can respond in a targeted way. Leaving it buried inside "Non-Bank Lending" doesn't make much sense.

**Comment by biza-io** [comment]
Biza.io Data Standards Committee believes the operation of this Decision Proposal by the Data Standards Body is inappropriate and not in the best interest of Consumers. 

We note the following:
- the consultation was scheduled to close on the day Treasury (the parent department of the DSB) published draft Rules which would inform responses
- the Decision Proposal does not cover the scope of what the proposed Rules involve
- the Decision Proposal document contains various contradictions within it most notable that it claims no Standards will be made while being presented as a "Decision Proposal" and proposing Standards changes
- the Decision Proposal document asks various questions which cannot be reliably informed without the publics access to the proposed Rules, which were published on the consultation closure date, and previous feedback on the prior [Rules consultation](https://treasury.gov.au/consultation/c2022-341682) promised by the DSB in February.

Further we note that only one bank and one representative body have provided feedback on this proposal, quite possibly due to the lack of information provided by the DSB, limiting participants ability to be afforded "natural justice" in providing feedback. We request the Data Standards Chair refer to his obligations with regards to reasonably considering feedback provided across the plethora of threads on this topic and also request Treasury make available documents within its possession.

Our suggestion therefore is:
1. Extend this consultation to align with, or be very close to, the consultation closure date of the recently published Rules
2. Publish documentation received in prior consultations related to Data Standards
3. Split the consultation into its industry parts, notably the split of the proposed Energy changes to the Rules

**Comment by CDR-API-Stream** [comment]
In response to @biza-io:

> Biza.io Data Standards Committee believes the operation of this Decision Proposal by the Data Standards Body is inappropriate and not in the best interest of Consumers.

This is a concerning statement and the DSB works hard to incorporate consumer concerns into the standards development process.  Could you give more detail on how this consultation isn't in the best interest of consumers?

In response to the specific things noted in the submission:

> * the consultation was scheduled to close on the day Treasury (the parent department of the DSB) published draft Rules which would inform responses

This statement is misleading.  This consultation was scheduled to close on a specific date that was publicised the day the consultation was opened.  The rules teams in Treasury independently initiated a separate consultation on the rules.  The parallel development of standards and rules is standard practice for new sectors and this is an example of that practice.  This approach was outlined in [Noting Paper 298](https://github.com/ConsumerDataStandardsAustralia/standards/issues/292).  We have already created the placeholder thread for the holistic review of the standards that will likely occur in October where feedback on the NBL standards as a whole will be requested.  There will therefore be opportunity to revisit previous feedback in the light of the rules consultation and the remaining specific NBL standards consultations.

> * the Decision Proposal does not cover the scope of what the proposed Rules involve

Correct.  It was never intended to.  The DSB consults on the standards, not the rules.  The scope of our consultations are usually very clear and specific.  The rules consultation is a separate consultation that can be responded to by participants.

> * the Decision Proposal document contains various contradictions within it most notable that it claims no Standards will be made while being presented as a "Decision Proposal" and proposing Standards changes

This is not a contradiction.  As outlined in [Noting Paper 298](https://github.com/ConsumerDataStandardsAustralia/standards/issues/292) we proposed a series of decision proposals that will build on each other.  Once an emerging standard has evolved we will then put the standard as a whole to the Chair for approval to become a 'candidate' standard.  Then, once the rules are made and a final consultation is completed, we will ask for approval of the Chair to make the resulting standards binding.  This is the same process that was followed for the energy sector.

> * the Decision Proposal document asks various questions which cannot be reliably informed without the publics access to the proposed Rules, which were published on the consultation closure date, and previous feedback on the prior [Rules consultation](https://treasury.gov.au/consultation/c2022-341682) promised by the DSB in February.

We understand that the final rules may result in changes to the standards which is accommodated in our process.  With regard to the final statement, we do not understand this.  The DSB does not consult on the rules and can make no promises in relation to them.  We are also not in control of the feedback provided to previous rules consultations and make no decisions in relation to them.

> Further we note that only one bank and one representative body have provided feedback on this proposal, quite possibly due to the lack of information provided by the DSB, limiting participants ability to be afforded "natural justice" in providing feedback. We request the Data Standards Chair refer to his obligations with regards to reasonably considering feedback provided across the plethora of threads on this topic and also request Treasury make available documents within its possession.

The consultation was conducted for the appropriate length of time and all participants were publicly invited to respond.  The DSB consultation process is conducted in accordance with the rules and legislation.  The Data Standards Advisory Committee has not raised concerns with our consultation approach.  The DSB reject this characterisation.

We will, however, alert the Data Standards Chair to this feedback so that he can make his own assessment and discuss it with the Advisory Committee if he wishes.

> Our suggestion therefore is:
> 
> 1. Extend this consultation to align with, or be very close to, the consultation closure date of the recently published Rules
> 2. Publish documentation received in prior consultations related to Data Standards
> 3. Split the consultation into its industry parts, notably the split of the proposed Energy changes to the Rules

We will not be adopting suggestion 1 or 3.  There is nothing for us to do in relation to suggestion 2 as all of our consultations, and the feedback the DSB receives, is already public here on GitHub.

This feedback appears to be based on a misunderstanding of the processes used to develop the rules and standards for the CDR and the roles of the different agencies that manage the regime.  To rectify this we would like to offer to speak to Biza bilaterally and provide an overview of how standards are developed and the accountabilities of the different agencies involved.

We would be happy to make this same offer to any other participant also.  Email us at contact@consumerdatastandards.gov.au if interested.
