### ISSUE TITLE
Decision Proposal 318 - Non-Bank Lending Standards

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#318]
This consultation thread was created to allow for holistic feedback to be provided on the [Draft Non-Bank Lending Standards](https://consumerdatastandardsaustralia.github.io/standards/includes/additional/drafts/non-bank-lending/banking-non-bank-lending.html#high-level-standards) which were published on 10 October 2023.

As those Standards are currently in a Draft form, they will be iterated to include detail and updates from the [Buy Now, Pay Later](https://github.com/ConsumerDataStandardsAustralia/standards/issues/317) and [CX for Non-Bank Lending](https://github.com/ConsumerDataStandardsAustralia/standards/issues/320) proposals.

Feedback is now open on any issue related to the Draft. This consultation will be open for feedback until **8 December 2023**. The Decision Proposal is linked in this [comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/318#issuecomment-1807753374).

**Comment by jxeeno** [comment]
Hi,

Where should responses in relation "Amendments to facilitate access to energy product reference data" be provided?  There are links to corresponding GitHub issues provided for "non-banking lending" and "buy now pay later" [consultation page](https://treasury.gov.au/consultation/c2023-434434-expansion), but non provided for the proposed energy PRD changes.

<img width="721" alt="image" src="https://github.com/ConsumerDataStandardsAustralia/standards/assets/23213119/1567324f-5993-4fc8-bbc0-4efc6070d25a">

Thanks

**Comment by CDR-API-Stream** [comment]
In response to @jxeeno:

The issue related to Energy PRD in the NBL consultation is to address issues arising the go live of the initial energy retailers last year.  This issue came to the fore and was discussed in [Noting Paper 248(https://github.com/ConsumerDataStandardsAustralia/standards/issues/248).

At that time the Treasury indicating that they would seek to amend the rules in the future to resolve the issue and this has now been included in this consultation.

Responses on this topic should be provided to the Treasury via email as they have indicated on the consultation web page.  The links to the NBL consultations hosted by the standards are to facilitate  the inevitable technical discussions arising from the rules consultation noting that the bulk of the consultation is oriented towards enabling the NBL sector.

**Comment by perlboy** [comment]
> At that time the Treasury indicating that they would seek to amend the rules in the future to resolve the issue and this has now been included in this consultation.

Actually a representative of the DSB made this statement and it was actually in “reserve the right to revisit in future Rules amendments” double talk. Upstream Treasury officials melted into the background and said nothing when the Chair realised the basis on which the DSB made the claim of mandatory implementation was found to be false. I know because I was in receipt of various messages on the matter. I won’t bother covering the fact this was after numerous statements by the DSB during consultation it wouldn’t be (Ref NP248 historical quotes).

> The links to the NBL consultations hosted by the standards are to facilitate the inevitable technical discussions arising from the rules consultation noting that the bulk of the consultation is oriented towards enabling the NBL sector.

What about the existing (rather than inevitable) technical discussion regarding the issues raised in NP248? Information security risks seem to be the domain of the DSB (no?) so why are [technical] participants being fobbed off to the room full of lawyers writing Rules? Is it so submissions can be lost in translation by those with their own agendas or, dare I say it, commercial benefit? Is this so the DSB can “claim” it’s consulted in future and provide no FDO and immediate binding with a “gotcha”?

The DSB seems to want its cake and eat it. On one hand we see a stream of threads for a sector which isn’t mandated with limited context for participants yet on the other hand a change that impacts an entire existing sector with identified issues in the suggested implementation approaches being hand-balled to the folk who have an almost stick figure technical understanding of the problem space.

**Comment by CDR-API-Stream** [comment]
@perlboy, the tone of your post is needlessly accusatory and aggressive.  Members of the DSB and Treasury are public servants and this is their workplace.  We will not facilitate an unsafe work environment by encouraging such submissions with a response.

If you would like to resubmit your questions without the unnecessary emotion we would be happy to respond.

**Comment by perlboy** [comment]
> @perlboy, the tone of your post is needlessly accusatory and aggressive. Members of the DSB and Treasury are public servants and this is their workplace. We will not facilitate an unsafe work environment by encouraging such submissions with a response.
> If you would like to resubmit your questions without the unnecessary emotion we would be happy to respond.

I'm not sure what the DSB is referring to as no individual was accused of anything so unsafe workplace claims don't appear to be based on any Fair Work rules. Statements of fact are not accusations they are statements of fact. It's worth noting that a _vast_ number of DSB representatives are paid contractors not FTE of the Australian Government so questions on probity and transparency are entirely appropriate. Nonetheless, sure, let's try again:

- Why is the DSB doing pre-rules consultation on Non Bank Lending but not the Energy sector changes? Does it intend to launch a pre-rules consultation on the matter?
- Does the DSB believe it has already provided sufficient guidance on how Energy providers could provide such a service? If so, has the DSB assessed the information security context of the guidance and can it provide such documentation so it can be reasonably assessed by the public?

**Comment by CDR-API-Stream** [comment]
> * Why is the DSB doing pre-rules consultation on Non Bank Lending but not the Energy sector changes? Does it intend to launch a pre-rules consultation on the matter?

We have published an approach for consultation on the NBL sector due to the need for stable standards with maximum lead time.  That is what our current consultations are in relation to.

It is not, and has never been, the practice of the DSB to conduct pre-emptive standards consultations for all possible rule changes.  In this case, if rules are made in relation to energy PRD and there is a perceived need for the standards to change as a result then we will consult on those changes once the rules are made.

> * Does the DSB believe it has already provided sufficient guidance on how Energy providers could provide such a service? If so, has the DSB assessed the information security context of the guidance and can it provide such documentation so it can be reasonably assessed by the public?

We can't possibly answer the first question as we don't know what final form the rules will take yet.

In the guidance we provided we were clear that it was guidance but the obligation for implementation choice remains with the energy data holders.  We don't currently see a need to be prescriptive in how energy data holders implement solutions in this space.  This gives energy data holders freedom to address the risks that they perceive as they see fit.

Finally, we would like to state that we support the rules team in this consultation.  Based on internally conversations, the team involved have been thoughtful and diligent in developing the current proposal.  They are now being open and transparent in attempting to resolve an issue that was raised by CDR participants and is currently having a tangible impact.

**Comment by CDR-API-Stream** [comment]
A holistic Decision Proposal for Non-Bank Lending Data Standards will be provided in due course.
Previous consultation links are below for reference -

**Sector Designation**
- [Consumer Data Right (Non-Bank Lenders) Designation 2022](https://www.legislation.gov.au/Latest/F2022L01522)

**Rules Exposure Draft** 
- [Consumer Data Right rules – expansion to the non-bank lending sector](https://treasury.gov.au/consultation/c2023-434434-expansion)

**Data Standards**
- [Noting Paper 292 - Approach to developing Data Standards for the Non-Bank Lending Sector](https://github.com/ConsumerDataStandardsAustralia/standards/issues/292)
- [Decision Proposal 316 - Non-Bank Lending sector alignment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/316)
- [Decision Proposal 320 - CX Standards | Non-Bank Lending](https://github.com/ConsumerDataStandardsAustralia/standards/issues/320)
- [Decision Proposal 317 - ‘Buy Now, Pay Later’ Product and Account Detail](https://github.com/ConsumerDataStandardsAustralia/standards/issues/317)
- [Decision Proposal 318 - Non-Bank Lending Standards](https://github.com/ConsumerDataStandardsAustralia/standards/issues/318) _(this issue, holistic proposal pending)_

**Comment by nils-work** [comment]
The [opening comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/318#issue-1809138477) has been updated and this thread is open for holistic feedback on the [Draft Non-Bank Lending Standards](https://consumerdatastandardsaustralia.github.io/standards/includes/additional/drafts/non-bank-lending/banking-non-bank-lending.html#high-level-standards).

Detail about the changes from the Banking Standards to the NBL Draft has also been added to [this comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/318#issuecomment-1769570540).

**Comment by CDR-API-Stream** [comment]
The Decision Proposal to support consultation on the [Non-Bank Lending Draft Standards](https://consumerdatastandardsaustralia.github.io/standards/includes/additional/drafts/non-bank-lending/banking-non-bank-lending.html) is now attached.

[Decision Proposal 318 - Non-Bank Lending Standards.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/13333231/Decision.Proposal.318.-.Non-Bank.Lending.Standards.pdf)

**Comment by CDR-Engagement-Stream** [comment]
The team have put together a short video on [Decision Proposal 318](https://youtu.be/JzjfDDb9ijc?si=Yg2z3PWr7QBzzwKf).

**Comment by NationalAustraliaBank** [comment]
This DP states that is provides a chance to submit holistic feedback on the Draft Non-Bank Lending standards. Our feedback is that it will not be possible for data holders (particularly those captured within Tranche 1) to implement these standards within the proposed timelines. We recommend that the “Tranche 1 date” be set as twenty-four (24) months from the date that the standards become binding

**Comment by Australian-Finance-Industry-Association** [comment]
Dear @CDR-API-Stream,

AFIA welcomes the opportunity to provide feedback on Decision Proposal 318. Please see attached our submission. 
[AFIA Submission_Decision Proposal 318_FINAL.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/13608233/AFIA.Submission_Decision.Proposal.318_FINAL.pdf)

Regards,

AFIA Team

**Comment by commbankoss** [comment]
CBA welcomes the opportunity to provide feedback on DP 318 – Non-Bank Lending Standards and acknowledges the publication of draft standards. CBA has previously responded to DP 316 – Non-Bank Lending sector alignment in which we provided feedback that CBA broadly agrees with the approach to encompass the Non-Bank Lending (NBL) sector within Banking, that is, new endpoints should not be developed specifically for NBL. We also encouraged, and continue to encourage, alignment of consultation sought by the ACCC and DSB on CDR Rules, Data Standards and CX Standards for NBL. 
 
To this end, CBA strongly recommends that consultation on DP 318, and any further data standards consultations for the NBL sector, are paused until the relevant CDR Rules are finalised. Reflecting on our learnings from implementation in the Banking sector, CBA believes CDR Standards can be more effectively developed and consulted on once final CDR Rules are issued. This is due to the CDR Rules providing requirements that directly impact our implementation approach and flow through to the scope and parameters of the data standards. By sequencing consultation on the data standards post final CDR Rules, we believe the industry is better placed to assess proposals and ensure these are fit for purpose and feasible to implement. Further, confirmation of implementation timeframes will better inform the timeline in which standards for the NBL sector need to be defined.
 
Each such consultation requires careful consideration and multiple internal stakeholder consultations. Further, ecosystem participants are required to assess multiple parallel consultations, such as DP 338 – Updates to Banking Products and Accounts - Binding Standards. 
 
CBA respectfully requests the DSB to consider this feedback to pause further consultation on DP 318, and any further data standards consultations for the NBL sector, until final CDR Rules for NBL have been issued.

**Comment by CDR-API-Stream** [comment]
This consultation is now closed. Thank you to all who responded.

**Comment by nils-work** [comment]
Decision 318 has been made by the Data Standards Chair: [Decision 318 - Non-Bank Lending - Candidate Standard.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/13721403/Decision.318.-.Non-Bank.Lending.-.Candidate.Standard.pdf)

The Draft Standards for the Banking and Non-Bank Lending sector will be made as Candidate Standards.

More detail about Experimental, Draft, and Candidate Standards is provided in the [Additional Standards](https://consumerdatastandardsaustralia.github.io/standards/index.html#additional-standards) section.

**Comment by CDR-API-Stream** [comment]
Decision 318 has been made by the Data Standards Chair: [Decision 318 - Non-Bank Lending - Candidate Standard.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/13721403/Decision.318.-.Non-Bank.Lending.-.Candidate.Standard.pdf)

The Draft Standards for the Banking and Non-Bank Lending sector will be made as Candidate Standards.

More detail about Experimental, Draft, and Candidate Standards is provided in the [Additional Standards](https://consumerdatastandardsaustralia.github.io/standards/index.html#additional-standards) section.
