### ISSUE TITLE
Decision Proposal 032 - Payee Payloads

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards#32]
This decision proposal outlines a recommendation for the payloads for direct debit authorisations as per the end points defined in decision proposal 015.

Feedback is now open for this proposal. Feedback is planned to be closed on the 1st November.
[Decision Proposal 032 - Payee Payloads.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/2497696/Decision.Proposal.032.-.Payee.Payloads.pdf)

Please note the specific concerns. If there is significant early feedback I will reissue with amendments prior to the closure date.

**Comment by anzbankau** [comment]
Some billers change a customers crn (reference number) every billing cycle. When a customer saves this biller in an online channel, typically he/she may not be allowed to store the crn, only billerCode and billerName are saved. To cater to this scenario, consider making crn optional/conditional.

**Comment by anzbankau** [comment]
Clarification please.
payeeId (ASCIIString, mandatory, "ID of	the adhering to the	rules of ID permanence"). Decision.009.ID.Permanace-->"IDs	must be immutable across sessions but	must not	be transferable across data consumer".
In a scenario where a customer has 1 payee and provides consent to 5 TPPs to share this data. Our reading of the ask is that the payee resource should have 5 unique payeeIds, is the correct?
-S

**Comment by JamesMBligh** [comment]
Please note, we have brought the feedback date back 1 day to allow for a draft standard to be published on the 2nd of November.

-JB-

**Comment by JamesMBligh** [comment]
@anzbankau, regarding the ID query, that is correct.  This is to prevent the accidental creation of an identifier that is useful outside of the context of the CDR APIs.

-JB-

**Comment by da-banking** [comment]
In general we are unclear on how this data is intended to be used.

In future versions when a `PUT /banking/account/transfer` is being supported, we would expect transfers to payees to pass in the `payeeId` and not the details.

We think that the data shared under `/banking/payees` is well within the remit of the authenticated user. We think this would be all the detail necessary to support third-party initiated payments to saved payees in future versions.

However many fields under `/banking/payees/{payeeId}` are sensitive. The authenticated user is sharing _someone else's_ BSB/Account Number, PayID etc here. We see this additional data being of use in a bank account portability scenario, but not otherwise.

We see that an additional security scope `Bank Payees Data` has been introduced, but we recommend adding a further `Detailed Bank Payees Data` scope to control access to the richer `/banking/payees/{payeeId}` endpoint. If the ACCC is to define a graduated accreditation levels, then accessing `Detailed Bank Payees Data` should require a higher level of accreditation.

**International**
Deliberate typo: this object should have a lower-case _i_ in the name as per the naming conventions.

**international.beneficiaryDetails.message**
We are unclear what this is. The description "Response message for the payment" makes no sense on a saved payee. Is this perhaps a reference number that should be sent to the payee when performing a payment?

**biller.crn**
This text field can contain a PAN. As such we treat it as we would any other field in the scope of PCI compliance, encrypted in transit and at rest. We would show this to the authenticated customer or staff only when masked. Allowing this value to leave the bank and go to 3rd parties would bring them into scope of PCI compliance.

We recommend masking anything that looks like a PAN on the fly if it matched a card number pattern. Masking would break a bank account portability scenario, but we consider that preferable to bringing 3rd parties into the scope of PCI compliance.

**Is the PayID represented correctly in the detailed payee object?**
For `payId.type`, we assume `ORG_NUMBER` is ABN, and note that it is possible to register an `ORG_NAME` as a PayID so this should be supported by the enumeration.

Not an immediate concern, but there are rules in NPP for use of a stored PayID. Essentially before the PayID is used, we check to see if the associated name has changed. This prevents a PayID being ported to another user, without the payer realising it. 

We would recommend adding a `lastUsedDateTime` or similar, as the PayID data may not be current when it is retrieved.

**Payments to credit cards has been excluded.**
We have saved payee data to PANs. Obviously this is sensitive, but the same risk applies to including `crn` as discussed above. With the same controls - `Detailed Bank Payees Data` and masking applied, it could be in scope.

**Comment by JamesMBligh** [comment]
@da-banking, comments below:

Your initial comments are accurate.  Account portability is a useful policy goal hence the information being included.

The need for an additional scope is noted.  An alternative would be to reserve the Payee scope for detailed information and give access to the payee list under basic account data.  The information in the list end point is pretty minimal.  Interested in thoughts on this option.

**International Typo**
Microsoft Word continues to helpfully change the capitalisation of field names.  Looking forward to transitioning to swagger.

**international.beneficiaryDetails.message**
A message on the payment was the intent of this field

**biller.crn**
Valid feedback.  We can add this comment to the field description.  Account portability can still be managed by asking the customer to provide the full value

**PayID**
Feedback noted.  I'll look into options.  The suggested last used field may only be a partial solution because the change could have happened even if the payee was used only a short while ago.  A description indicating that the PayID needs to be revalidated prior to use may be more appropriate

**Credit Cards**
Noted

-JB-

**Comment by da-banking** [comment]
@JamesMBligh comments below:

>The need for an additional scope is noted. An alternative would be to reserve the Payee scope for detailed information and give access to the payee list under basic account data. The information in the list end point is pretty minimal. Interested in thoughts on this option.

Payee data is a different _kind_ of data to account data, but in terms of sensitivity, the basic payee data is not more sensitive than the basic account data. 

There is a definite distinction in sensitivity between the basic payee data and detailed payee data, your suggestion would allow this distinction to be controlled so is workable from our perspective.

**Comment by anzbankau** [comment]
-	Some international banks may not have more details than a country in SWIFT reference data, so the "address" field should not be mandatory for the bankAddress.
-	For international payments beneficiary details like name & address are not mandatory.
-	Account and payId need to be classified as conditional?
-	CRN in biller should be optional, as some billers change CRN every billing cycle. So, CRN capture for those type of billers is not mandatory.
-	For US banks, an online channel can allow payments via "Fedwire number" (as well as CHIPS) and account number, which does not fit into the response payload.
-	Sharing of International beneficiary details may be subject the local privacy regulations of the beneficiary accounts’ domiciled country. i.e. MAS in Singapore.
-	Are the International payee fields in keeping with SWIFT standards? What is a routing number?  Swift code should say Beneficiary Bank BIC.  What is a chip number?

S/RC/RD (181031-1)

**Comment by NationalAustraliaBank** [comment]
NAB does not support the inclusion of Personally Identifiable Information (PII) and other sensitive payment data that belong to other people without their explicit consent. The transfer of this data would effectively involve the transfer of personal information whereby the individual to whom it relates has not explicitly consented to its transfer.

**Comment by da-banking** [comment]
@NationalAustraliaBank - we are curious if you had a view on account porting. This is largely a manual process today - where the user would recreate the payees they have with a former bank manually with their new bank. In this scenario, it seems that the user has a legitimate reason to share the payee data they already have access to with their new bank, who would get access to it manually anyway.

We proposed the introduction of an additional scope to govern access to this data so that the ACCC might only accredit banks (or equivalently accredited and audited institutions) with this in the first instance, and allow the transfer of this data only for the purposes of account porting.

**Comment by JamesMBligh** [comment]
As we are publishing tomorrow we’re being strict with feedback closure.  Here are responses to feedback provided.

**Biller**
- I will make CRN optional.  To accommodate the situation where the CRN is a PAN I can add a description that the CRN should be masked according to the MaskedPANString common type

**Payee**
- Will add ORG_NAME as a PayID type and add commentary about checking PayID validity before use

**International**
- Name and bankAddress will be made optional
- Account and PayId will be fixed to mark them as conditional
- Fedwire number and account number will be added as options
- Will change swift code to be beneficiaryBankBIC

For clarification, routing number is the equivalent of a BSB in other jurisdictions and chip number is the number for the CHIPS system

**Scopes**
I will change the basic list to utilise the basic account info scope and details to use payee info scope although this will be subject to change based on feedback from the research to be conducted by the UX stream.  The UX stream will review the customer understanding of all of the scope boundaries.

-JB-

**Comment by JamesMBligh** [comment]
Westpac have indicated that the comment below was accidentally posted to the incorrect proposal:

--------------

It is likely that sensitive details of a third party would be shared via this endpoint. This risk is increased as it is our view that customers may use NPP as a message service and not be aware that the information they enter could be accessed beyond the intended payee. Careful consideration should be given to this issue from consent, security scope and/or masking viewpoints.

We have the following additional questions and comments:

We agree with the comments made by @anzbankau and @da-banking on crn.
Any derived data, such as a list of payees, which also relies on consumer input may contain a higher level of errors than raw data we actually hold. Obligations around accuracy should take this into consideration.
We agree with the comments made by @anzbankau on making mentioned fields related to international payments, account/payId as conditional and international privacy rules. The International and beneficiaryDetails objects should be conditional. bankAddress should be optional.
The type field and account object haven’t been specified as mandatory conditional or optional.
We don’t understand the message field in the beneficiaryDetails object.
How should bankDetails be used if there is an intermediary?

**Comment by JamesMBligh** [comment]
The finalised decision for this topic has been endorsed. Please refer to the attached document.
[Decision 032 - Payee Payloads.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/2551710/Decision.032.-.Payee.Payloads.pdf)

-JB-
