### ISSUE TITLE
Decision Proposal 320 - CX Standards | Non-Bank Lending

### ISSUE THREAD

**Issue by CDR-CX-Stream** [ConsumerDataStandardsAustralia/standards#320]
The purpose of this decision proposal is to define the data language standards to be used to describe Non-Bank Lending data. This paper proposes that the Non-Bank Lending sector adopt the existing [Banking data language standards](https://consumerdatastandardsaustralia.github.io/standards/#banking-language). The DSB is seeking views on this proposal and, if it is not supported, why divergence may be necessary to accommodate the NBL sector. 

The community is invited to provide feedback on this paper by **Friday 8 September 2023** ~Thursday 31 August 2023~.

Decision Proposal 320 on CX Standards for Non-Bank Lending can be found below:
[Decision Proposal 320 - CX Standards for Non-Bank Lending.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/12246843/Decision.Proposal.320.-.Non-Bank.Lending.Data.Language.pdf)

Key consultation queries include:
1. Do the existing data language standards sufficiently accommodate the designated Non-Bank Lending datasets?
2. If not, what alternatives or divergence should be considered, and why?
3. Do the existing data language standards for banking sufficiently relay the scope of data to be
shared in a way that is meaningful to consumers?
4. Are there any factors not covered in this proposal that the DSB should consider?

--------
Edit 11.09.23: consultation closed; the thread will remain open as per [this comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/320#issuecomment-1713198076)
Edit 01.09.23: consultation period extended by 1 week to 8th September
Edit 03.08.23: placeholder updated to include consultation paper

**Comment by CDR-CX-Stream** [comment]
The Decision Paper for the consultation on Non-Bank Lending Data Language has been published and can be found in the original post.

**Comment by da-banking** [comment]
Data Action agrees that the existing data language standards used for Banking sufficiently accommodate the designated Non-Bank Lending datasets. Data Action also agrees that the existing data language standards for Banking sufficiently relay the scope of data to be shared in a way that is meaningful to consumers.

**Comment by nils-work** [comment]
Hi @perlboy 

Whether new endpoints will be required for Non-Bank Lending is yet to be determined, but previous papers have considered aligning to the Banking Standards, and the endpoints, scopes and error handling are part of that consideration. 

Acknowledging that a Non-Bank Lending Data Holder may become a Bank is also part of the consideration for alignment to the Banking Standards.

For reference -
- [Noting Paper 292 - Approach to developing Data Standards for the Non-Bank Lending Sector](https://github.com/ConsumerDataStandardsAustralia/standards/issues/292) **(Now closed)**
- [Decision Proposal 316 - Non-Bank Lending sector alignment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/316) **(Open until 25 August)**
- [Decision Proposal 317 - NBL Placeholder](https://github.com/ConsumerDataStandardsAustralia/standards/issues/317) **(Expected to explore BNPL in further detail)**

Regarding scopes, where you've said "If they are overlapping it could pose issues" can you clarify what you meant?

**Comment by perlboy** [comment]
> Regarding scopes, where you've said "If they are overlapping it could pose issues" can you clarify what you meant?

If the authorisation scope is uniform and an organisation merges there could be a situation where an ADR is granted access to additional endpoints/data that historically wasn't the case (i.e. the Consumer wasn't expecting it). Concern I have here is that it could become very fuzzy very quickly because the Standards have over committed to unified scopes. I ponder whether it's worthwhile _deliberately_ overlapping scopes (i.e. have endpoints that are accessible for >1 scope if a Holder supports multiple sectors). For instance have `bank:accounts.basic:read` and `nbl:accounts.basic:read` that start out as being carbon copies for existing endpoints (including language) facilitating more nuanced approach in the future if required (for instance the merged entity giving 2 different account views).

Another example that comes to mind that probably breaks rigid adoption of overlapping endpoints (and therefore consideration for split scopes) is payment schedules. In energy there is an endpoint for this but in banking it's wrapped up in lending rates with a repayment type. If we take a classic BNPL product they don't _have_ a lending rate but do have a fee and do have a repayment schedule. Maybe it's fine for those products to simply list a rate of 0% but that isn't really _true_ either because of penalty charges. Again, if the scopes were separated it would be possible to add to the data language specific to NBL rather than the alternative of creating a new data cluster for payment schedules alone.

It's quite challenging giving answers without a Rules draft here to provide the much needed nuance to assess whether it's possible for all in scope products to adopt unified endpoints/scopes or if there is specific call outs for separate endpoints (and scopes). I'm pretty concerned around declaring CX Standards when the DSBs own references seem to indicate there's room for variability, I think this is probably a bit of the cart before the horse.

**Comment by CDR-CX-Stream** [comment]
Hi @perlboy 

Thanks for this feedback.

In relation to this concern:

>I'm pretty concerned around declaring CX Standards when the DSBs own references seem to indicate there's room for variability, I think this is probably a bit of the cart before the horse.

The NBL data language standards proposals are based on the current technical standards assumptions. It's assumed that if the technical standards positions change, the data language standards will need to adjust accordingly. The following is stated in the decision proposal to clarify that a subsequent consultation will be conducted, which is expected to occur later in the year when the technical standards consultations are further progressed:

>If the recommendation to adopt the banking data language standards is supported, the DSB expects to propose that this be made binding in a subsequent decision proposal, subject to the finalisation of the NBL rules.

The intention with this approach is to provide the community more time to provide feedback in multiple iterative rounds.

**Comment by commbankoss** [comment]
CBA supports using existing Banking sector data language standards for the Non-Bank Lending (NBL) sector. In reviewing the permission language, the existing banking data standards are broadly compatible with the NBL sector due to similarity of NBL and bank data. In addition, NBL customers are familiar with these language standards. CBA recommends the DSB revisit the approach to NBL standards as deeper Rules, Standards and CX design work is undertaken.

**Comment by CDR-CX-Stream** [comment]
@perlboy you've noted:

>On one hand there's a statement of an assumption (which isn't specified in the DP) and on the other hand what is in the DP is that the DSB expects to make it binding not that it will be consulted on again. 

[This comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/320#issuecomment-1690802271) clarified this assumption and also that a subsequent consultation would be conducted.

You've also raised a separate issue regarding submissions being made public. The Data Standards Body does not manage the Treasury website, or the publication of submissions sent to the Treasury, so this query has been relayed to the Treasury for their consideration.

**Comment by CDR-CX-Stream** [comment]
Following the recent publication of the [exposure draft rules for non-bank lending](https://treasury.gov.au/consultation/c2023-434434-expansion), this consultation will be extended by one week, to Friday 8 September, to allow the community to consider them in conjunction.

**Comment by CDR-CX-Stream** [comment]
Thanks to all who provided feedback. This first round of consultation is now closed, but the thread will remain open for community engagement until the DSB conducts a subsequent consultation that includes proposals for CX NBL standards to be made binding.

**Comment by CDR-CX-Stream** [comment]
The consultation on NBL CX data language standards progressed in [DP318](https://github.com/ConsumerDataStandardsAustralia/standards/issues/318), and concluded with a [decision](https://github.com/ConsumerDataStandardsAustralia/standards/issues/318#issuecomment-1863667909) made by the Data Standards Chair. This thread will now be closed.
