### ISSUE TITLE
Decision Proposal 055 - Accounts & Balances V1

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards#55]
This issue has been opened to propose and publish the final decision paper for Accounts & Balances that establishes version 1 of these end points and payloads.

The proposed decision is below. Feedback will close on 26th April.
[Decision 055 - Accounts & Balances V1.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3123436/Decision.055.-.Accounts.Balances.V1.pdf)

**Comment by JamesMBligh** [comment]
Added the final decision proposal as an attachment to the comment.  Note that an additional end point for balance of a single account has been added in response to feedback.  Also, I have reassessed the inclusion of balance data in the detailed payload and have decided to leave it out for caching reasons.  Obtaining the balance from an dedicated end point is much more cacheable and will be more performance for all participants.

-JB-

**Comment by anzbankau** [comment]
Hi James 
We have the following points on the Account endpoints:
1.	is-owned is missing the definition of enumerations for search, this was present in the previous version but is not present in V1. Please also note that enumerations didn’t match the response values.
2.	V1 seems to have introduced the concept of a singular DepositRate and LendingRate where previously it was only an array of DepositRates and LendingRates. Is this intentional, if so it could be seen as unnecessary as it could be represented by a single element in the array. 
3.	isActivated is represented outside of the features object (changed in V1), is this intentional? 
4.	Amount has changed to be mandatory within the fees and BankingAccountDiscount object we believe this should be optional/conditional due as the description of other fields effectively describing it as non-mandatory “One of amount, balanceRate, transactionRate and accruedRate is mandatory”
5.	Product-category values are missing from the decision proposal. Please add or make reference to another specification.

**Comment by JamesMBligh** [comment]
Response to feedback is as follows:

- isOwned was intended to be boolean in line with the field name form of a flag.  It has now been consistently applied as such and the descriptions updated to clarify usage.
- Regarding rates, a set of singular rates have been introduced for simplicity.  These are considered base rates.  However, the fully complex rate structure matching product reference data is also included that can be used to express the full range of additional bonus, penalty or conditional rates as necessary.  The singular rates should be interpreted as the "rate at the time of the API call"
- The isActivated field is intended to be represented as an additional field on the feature object.  This was conveyed via indentation but this is hard to identity.  The description has been .updated to clarify this.
- The reference to BankingAccountDiscount reflects the fact that the swagger does not reflect the new V1 document fully.  The proposal now essentially aligns the product and account structures so the account specific structures are now redundant will be removed from the swagger and documentation.  This feedback is valid, however, and has been applied to BankingProductDiscount.
- The reference to product category exists on the productCategory field (which is referenced from product-category)

The document in the main comment has been updated and swagger changes have been made.  Swagger changes will be published once all current feedback is incorporated.  Note that the account specific structures have not yet been removed but will be shortly.

-JB-

**Comment by JamesMBligh** [comment]
Please find attached the final decision covering this issue
[Decision 055 - Accounts & Balances V1.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3251507/Decision.055.-.Accounts.Balances.V1.pdf)
