### ISSUE TITLE
Decision Proposal 059 - Customer v1

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards#59]
This issue has been opened to propose and publish the final decision paper for Customer that establishes version 1 of these end points and payloads.

The proposed decision is below.  Feedback will close on 26th April.
[Decision 059 - Customer V1.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3123359/Decision.059.-.Customer.V1.pdf)

**Comment by JamesMBligh** [comment]
Please note that the decision proposal for this item has been added to the issue description

-JB-

**Comment by NationalAustraliaBank** [comment]
NAB would like to provide the following initial feedback on the Customer v1 definition.

#### `isPreferred` flag for `phoneNumbers`and `emailAddresses` objects
We recommend that the `isPreferred` flag for phone numbers and email address be consistently reflected in the definition and that the `isPreferred` flag be reflected as conditional for both.

Referring back to previous feedback by NAB (https://github.com/ConsumerDataStandardsAustralia/standards/issues/39#issuecomment-441159032) and the community (https://github.com/ConsumerDataStandardsAustralia/standards/issues/39), there should be consideration towards supporting the ability for data holders to not reflect a preference if one is not held.

#### `organisation` object
1. The `lastUpdated` field is missing an optionality definition.
2. `abn` as mandatory has regressed from the Swagger definition. The Swagger currently reflects a previous decision on making `abn` optional: https://github.com/ConsumerDataStandardsAustralia/standards/issues/26#issuecomment-433881373

**Comment by anzbankau** [comment]
Hi James

We have the following points on the Customer endpoints:

**Organisation**
The description states for the Organisation object: This object is mandatory if the authorisation for access was given in the context of an agent for a business customer. It should not be present if retail consumers, on their own behalf, gave the authorisation for access.
Should it instead be worded to be returned if the owner of the accounts is an organisation? This would possibly better represent who the customer is in this case.

**phoneNumbers.areaCode**
Area code should be changed to optional as it is not always available (even for non-mobile).

**phoneNumbers.fullNumber**
The description states that this must be the fully formatted number in RFC 3966 form. It is not always possible to adhere to this standard. What is the expected behaviour in this case?

**emailAddresses.address**
The description states that this must be the formatted in RFC 5322form. It is not always possible to adhere to this standard. What is the expected behaviour in this case?

**Organisation.legalName**
Should be optional as we note that some organisation may only provide a business name and not a legal name. 

**Organisation.ABN**
ABN is now mandatory, needs to be optional as we note that some organisations may only provide either ABN or ACN or nothing.

**Comment by JamesMBligh** [comment]
In response to feedback:

- isPreferred has been made consistently conditional.  The feedback that a preference should be optional has been reviewed and the choice of conditional has been made.  The absence of a preferred entry means that the client needs to made this choice and they have the least context of all participants to make this decision.  As such it is preferred for the holder to make this delineation.  If a customer has not made a preference the implication is that all entries are equally preferred so a random selection for communication is a reasonable outcome.
- lastUpdated has been fixed in the document and swagger.
- abn field has been corrected in the document and the swagger and is mandatory.  As was previously stated in feedback `Without an ABN you can't establish a business bank account in Australia. This implies that an ABN being required is valid. As we address other industries we may revisit this and make it conditional`
- The Organisation description is deliberate.  The consent is provided by a customer and the set of accounts is then derived from the customer rather than the other way around.  Selecting the customer type based on the accounts that are accessible is not the intent.
- areaCode has been made optional in swagger and document.
- For fullNumber - if a number cannot be formatted in a standard format then it also cannot be used to make an actual phone call.  In this situation it would be recommended to remove the record as the data is corrupted beyond usability.  It should also be a flag to correct the held data for the customer to improve data quality but this is a concern for the holder.
- For email addresses that cannot be formatted as valid addresses the same commentary applies.
- Regarding legalName, it is assumed that the name for the business collected during origination and KYC is the legal name.  Preference is to keep this mandatory and to assume that the business name provided is the legal name of the business.  This will be kept for v1 but we can revisit at a later date for v2 if there are real issues encountered during production rollout

I have made these changes locally and will be uploading them in the main comment and to the public standards repo shortly.

I will also be closing feedback on this issue thread.

-JB-

**Comment by JamesMBligh** [comment]
Please find attached the final decision covering this issue
[Decision 059 - Customer V1.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3251490/Decision.059.-.Customer.V1.pdf)
