### ISSUE TITLE
Decision Proposal 069 - Reauthorisation

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards#69]
This issue has been opened to capture, document and obtain feedback on a subset of the Information Security profile for the CDR regime with a view to finalisation and endorsement by the Chair of the Consumer Data Standards body.

This issue specifically describes the technical mechanism for a reauthorisation of a sharing arrangement to be requested by a Data Recipient and concluded by a Data Holder.

The proposal is published below.  Feedback will be open until the 17th May.
[Decision Proposal 068 - Reauthorisation.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3147050/Decision.Proposal.068.-.Reauthorisation.pdf)

**Comment by WestpacOpenBanking** [comment]
We have also given the following feedback to the CX working group. We believe that there should be a single flow for reauthorisation. In particular, we suggest that expiry notifications are only sent from the Data Recipient and that re-authorisation is only initiated at the recipient. The most pragmatic approach may be a simplified redirect flow similar to the authorisation flow (combining flows 3.3 and 3.4 in the phase 2 cx prototypes), but a [CIBA flow is a possibility with some caveats](https://github.com/ConsumerDataStandardsAustralia/infosec/issues/65#issuecomment-489017154). We recommend this approach as notifications from both Data Recipient and Data Holder may be confusing for customers.

**Comment by JamesMBligh** [comment]
I have published a proposal for this topic in the main comment above.  I believe this should meet the feedback provided by @WestpacOpenBanking but still leaves significant room for the CX work stream to determine the specific experience for the Customer.

-JB-

**Comment by darrenallen85** [comment]
Hi James - given that the re-auth process is asynchronous, what is the intended behaviour if a second reauth request is sent before the first one completes ?
Darren

**Comment by darrenallen85** [comment]
Hi James,
I have been thinking about the proposed implementation of sharing id. Currently as I understand it we are proposing the following changes to incorporate sharing_id:

Impacted Endpoint | Change Description
--------------------- | ----------------------
Authorization | Add support for new sharing metadata in the request object
Token | Add support for issuing sharing_id
Introspection | Add support for introspecting sharing_id
revocation | Add support for revoking sharing_ids and associated tokens
reauthorization | New API to support reauth of sharing_ids

a) is this roughly correct ?
b) if this is correct - isn't this a rather large set of changes to base OIDC functionality ? It seems to be a large % of the total endpoints.
c) technically i am drawn to a solution that keeps all ( or at least the majority ) of these impacts in one place ie It seems attractive to me to centralise the responsibility for sharing_id management in one endpoint rather than across multiple endpoints. Thoughts ?

**Comment by NationalAustraliaBank** [comment]
Rather than taking a rushed approach, NAB requires collaborative design workshops to be facilitated between CX/UI and InfoSec groups to ensure a robust re-authorisation solution is adequately implemented. More specifically:

- Continuous iterations for re-authorisation: NAB understands that customer experience lives with the CX/UI group and have been providing feedback via the same. However, it’s part of InfoSec’s responsibilities to outline the initial Security Requirements, including the need for customer authentication and authorisation through the Data Holder for re-authorisation purposes. Since Data Holder's are the custodians of customer data, the extension of Data Recipient’s access to a customer data must be properly authenticated, authorised and recorded at the Data Holder.

- As previously [articulated](https://github.com/ConsumerDataStandardsAustralia/infosec/issues/65#issuecomment-483950028), NAB strongly recommends that for day 1 of CDR and Open Banking that re-authorisation is performed using the existing authorisation flow for re-authorisation to simplify and de-risk implementation.

**Comment by dpostnikov** [comment]
This is one of the use cases that CIBA standard was designed for. Why wouldn’t we re-use all the work that has been done for us (endpoints, payloads, flows have been designed and reviewed. If we think some parts of CIBA not required we could profile it for our use case (for example, Data61 might say we don’t want to support “push” for authorization result for CDR in Australia). CIBA is aligned with OpenID Connect and opens up a lot of future use cases.

https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0-ID1.html

**Comment by JamesMBligh** [comment]
> Hi James - given that the re-auth process is asynchronous, what is the intended behaviour if a second reauth request is sent before the first one completes ?
> Darren

The profile is not specific which implies it is left in the competitive space, although more prescription may appear warranted once the CX stream have conducted testing.  If there is a consensus opinion that a prescribed position is desirable then that would be considered.

-JB-

**Comment by JamesMBligh** [comment]
@darrenallen85, in regard to your comments about consent API I have provided a detailed comment on this topic here https://github.com/ConsumerDataStandardsAustralia/standards/issues/62#issuecomment-493259502.

It might be worthwhile responding in that thread to keep the commentary together.

-JB-

**Comment by JamesMBligh** [comment]
@dpostnikov, the initial position of the DSB was that CIBA would be an appropriate candidate for reauthorisation.  A more minimal approach has been taken in response to feedback from recipients and holders indicating that this would be an unjustifiably large implementation overhead so the position was modified to address this feedback.

-JB-

**Comment by JamesMBligh** [comment]
Thanks for all of the feedback. By request this issue will be kept open for further consultation until mid week.

**Comment by SlatsFR** [comment]
Hi James

ForgeRock would like to understand the reasoning for moving away from CIBA, and the suggested alternative approach. As per @dpostnikov, this is explicitly what CIBA has been designed to do. 

If the implementation of CIBA is too onerous, would it not be better to work with the standard to address the issues raised? (obviously depending on the breadth and scope of the issues at hand).

Matt.

**Comment by commbankoss** [comment]
CBA believes that reauthorisation should not deviate from CIBA standards which have been designed specifically for Open ID Connect (OIDC). The current Decision Proposal is a modification to CIBA and would likely require significant work in order to be implemented, such as: definitions of endpoints; details of request and response payloads; definitions of time-outs or error scenarios; and details regarding the payload for introspection API. Existing CIBA standards provide all the benefits of existing standards including definitions, documentation and testing. 
 
We note that “a more minimal approach has been taken in response to feedback from recipients and holders indicating that this would be an unjustifiably large implementation overhead” and are keen to fully understand these concerns. We understand that the CIBA standards have a degree of optionality in the way CIBA is implemented and therefore a ‘minimal approach’ may not be necessary.

**Comment by WestpacOpenBanking** [comment]
Westpac believes that a simplified redirect with known channel authentication flow is the most pragmatic option for go live and we endorse @NationalAustraliaBank’s [comments](https://github.com/ConsumerDataStandardsAustralia/standards/issues/69#issuecomment-492891459) on this recommendation. We support CIBA for re-authentication with the following ([previously mentioned](https://github.com/ConsumerDataStandardsAustralia/infosec/issues/65#issuecomment-489017154) caveats:

* The compliance date to support reauthorisation is deferred to allow implementation by Data Holders and Data Consumers.
* Customers are notified of the need for a reauthorisation to be sent by Data Recipients rather than Data Holders.
* Language which allows for the decoupling of the expiry date of the refresh token from the expiry date of the authorisation is used.

We agree with @dpostnikov’s [comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/69#issuecomment-493261631) on CIBA and recommend pre-existing standards based approaches over the current proposal.

**Comment by JamesMBligh** [comment]
Please find attached the final decision covering this issue.  For reauthorisation this decision represents no decision being taken yet.
[Decision 061-066,068 - Information Security Profile.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3251465/Decision.061-066.068.-.Information.Security.Profile.pdf)
