### ISSUE TITLE
unclear interaction between x-v and x-min-v http headers

### ISSUE THREAD

**Issue by rfc6919** [ConsumerDataStandardsAustralia/standards#74]
per the v0.9.3 spec, if an API provider is not capable of servicing the API version specified in a client x-v header, but is capable of servicing a version >= than requested in x-min-v, it still must return 406 Not Acceptable. presumably the description for x-v should be updated to allow service of versions less than requested, as long as x-min-v is satisfied.

**Comment by CDR-API-Stream** [comment]
Hi @rfc6919 - this is very welcome feedback.  Due to the mechanisms we have in place for the Chair to approve changes it is preferred if comments of this nature are added to existing issue threads rather than having a new issue created (we acknowledge this is not normal GitHub convention).

To facilitate this I will copy this comment to the open thread and close this issue.

**Comment by fahadbinrahat** [comment]
**Question # 1:-**

Please clarify if this understanding is correct:-

The integer in x-v represents <minor> in <major>.<minor>.<bugfix> of documentation versioning?
If not kindly clarify with example what can be a minor version and how will a x-v version map to CDR requirement version for traceability.


**Question # 2:-**

In light of definitions given on standards for URI version, x-v and x-min-v, can you please confirm if API response shown below is expected as per API requests

**API Request:-**

_**Given:-**_

**URI:-** /cds-au/V1/banking/accounts
**x-v:-** 4
**x-min-v:-** 2

**_Provided:-_**

Holder’s highest implemented version is 1.2

**API Response**
API responds with
**x-v:** 2
