### ISSUE TITLE
Decision Proposal 84 - September Draft Feedback Cycle

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#84]
This thread has been created to accept feedback on v0.9.6 of the standards. This thread is for feedback on information security profile and the overall standards, API URIs and payloads.

**Comment by perlboy** [comment]
I note commits over the weekend regarding a move to the `standards-maintenance` repository for what appears to be individual issues here:  https://github.com/ConsumerDataStandardsAustralia/standards-maintenance

Given there is 150+ watchers on this repository and <5 on the new one my first question would be whether the DSB intends to do a mailout to the mailing lists (which appears to have been abandoned) regarding the change in work item delivery?

Regarding issue management. It appears the plan is to establish an 8 week long sprint cycle? Is there a decision proposal available for this change in approach? 

Thirdly, I note there is currently 9 issues open within this repository. Could the DSB provide guidance on when they expect to complete the initial publishing of currently open issues current tracked internally? It seems reasonable that participants should have the ability to submit their list of open issues for consideration with sufficient time prior to sprint kick off 30 September.

Finally, has the DSB coordinated with the testing team within the ACCC? From their published timelines (available here https://www.accc.gov.au/focus-areas/consumer-data-right-cdr-0/cdr-assurance-strategy-banking) the current proposed timeline suggests testing being 75% complete prior to the DSB completing a single sprint:
![image](https://user-images.githubusercontent.com/4291448/64496528-1c912d00-d2e9-11e9-819d-89954134bd54.png)

At this stage and at face value, Biza.io's immediate recommendation would be to target a much higher velocity than proposed of either 2 or 4 week sprints.

**Comment by CDR-API-Stream** [comment]
The exposure of the new repository is a soft launch so that specific feedback could be obtained from non-internal stakeholders.  A wider announcement is intended for later in the week addressing some of the questions raised.

The proposed model is aligned to the noting paper published on issue #50 with feedback considered.  The issues raised are those that the DSB have previously stated will be added to the backlog with an intention that community members will be able to create their own issues which is something that various participants have previously requested.

**Comment by perlboy** [comment]
> The exposure of the new repository is a soft launch so that specific feedback could be obtained from non-internal stakeholders. A wider announcement is intended for later in the week addressing some of the questions raised.

I don't know what that last sentence means (is that announcement for feedback of the process, request for issues, responses to the 100+ responses in the July thread, something else?) but I repeat my first question:
_Given there is 150+ watchers on this repository and <5 on the new one my first question would be whether the DSB intends to do a mailout to the mailing lists (which appears to have been abandoned) regarding the change in work item delivery?_

It seems that changes have been made preemptively based on a thread that was "grave dug" by @commbankoss that was previously idle and unclosed since March. This appears to be originally related to feedback receipt management and not work item management (these are two different things). It also appears the proposed approach intends to treat an agile sprint approach as the same as the original feedback cycle with issues.

Simultaneously, the `standards` repository has had statements with respect to not opening issues or pull requests on it.

> The proposed model is aligned to the noting paper published on issue #50 with feedback considered. 

Where is the feedback considered version published for consideration or will it be published as a Decision already approved by the DSB Chair? I repeat the question asked again:
_Regarding issue management. It appears the plan is to establish an 8 week long sprint cycle? **Is there a decision proposal** available for this change in approach?_

>The issues raised are those that the DSB have previously stated will be added to the backlog with an intention that community members will be able to create their own issues which is something that various participants have previously requested.

Yes, which Biza.io supports, the question is by when: _Could the DSB provide guidance on **when they expect** to complete the initial publishing of currently open issues current tracked internally?_

Agile sprints rely on velocity and after 6 months of inaction the change is now being forced through while appearing to not really adopt many of the core principles of agile task management. Relative to the governments timeline, much of the sand has now passed through the hourglass so faster iterations and guidance on when the DSB will have synchronised it's internal issues lists is not only prudent but most likely **necessary** to achieve the currently published timelines.

**Comment by elliots** [comment]
There is a small issue with the swagger file (apologies if this is the wrong place for this issue, I'm a bit confused about how this repository works).

In `BankingScheduledPaymentRecurrenceIntervalSchedule` the field `nonBusinessDayTreatment` is type `string` but has a default value of `ON` which is a yaml reserved word (it is parsed as the boolean `true`). It should be replaced with `"ON"` for both the default and the enum value. 

See: https://yaml.org/type/bool.html

I couldn't see where the file is (or is generated from) or I'd provide a pull request.

**Comment by CDR-API-Stream** [comment]
In response to @elliots:

The yaml file has had `ON` replaced with `"ON"` in both the default and enum fields in v1.0.0

If more changes are recommended please raise them as an issue on the new maintenance repo where we are aiming to operate the issue tracker in a more standard GitHub fashion.

**Comment by CDR-API-Stream** [comment]
With the release of v1.0.0 of the standards this thread is now being closed.  Further queries or issues should be raised on the new maintenance repo at:
https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues
