### ISSUE TITLE
Decision Proposal 85 - Concurrent Consents

### ISSUE THREAD

**Issue by CDR-InfoSec-Stream** [ConsumerDataStandardsAustralia/standards#85]
This decision proposal outlines a recommendation for enabling concurrent, or overlapping, consents under the CDR regime.

The consultation draft for this decision proposal is attached below:
[Decision Proposal 085 - Concurrent Consent.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3674229/Decision.Proposal.085.-.Concurrent.Consent.pdf)

Feedback is now open for this proposal. Feedback is planned to be closed on the 11th of October.

Final decisions has been attached below:
[Decision 085 - Concurrent Consent.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3943313/Decision.085.-.Concurrent.Consent.pdf)

**Comment by anzbankau** [comment]
ANZ supports option 2 and prefers this was included in the February release as this is simpler for data holders to implement and allows for more flexibility for ADRs and Customers.

**Comment by WestpacOpenBanking** [comment]
Westpac supports the ability for customers to have multiple concurrent active consents for a single data recipient use case. Until the publication of the v0.9.6 standard we had previously relied on CX guidance and have been building under the assumption multiple consents were possible as in Option 2. For this reason, this is the approach we continue to recommend for February. 

In the medium term, after February, we recommend that:

1. The standards incorporate a consent API to allow robust consent management. This API would likely include a consent identifier, fine-grained consent information (as will be discussed at the CX stream’s October 22) and perhaps contain other consent related information which may have otherwise been centrally stored in the register and associated with software products rather than particular consents.
2. The standards develop a re-authorisation mechanism distinct from the authorisation process using the consent identifier. 

This approach has similarities with option 1, but there is no need to restrict to a single consent relationship.
 
We don’t recommend further customisations to security standards and remark that the use of security tokens as consent identifiers is an unfavourable approach because of the careful token management required.

**Comment by CDR-API-Stream** [comment]
Feedback is now closed and a proposal will be developed for approval by the Chair in due course.

In response to the feedback provided:

* There is currently no support in the CDR rules for a simplified reauthorisation flow so this cannot be considered at this time.  In making this decision support for reauthorisation from a technical perspective must be considered as the current, single consent, position actively supports reauthorisation.
* The current position of the standard provides for reauthorisation via the single consent mechanism.  Adopting option 2 for February actually removes this support reducing the capability the standards make available to data recipients.  This is undesirable.
* Option 1 without the single consent constraint represents an adoption of a consent API but does not resolve any of the concerns raised regarding reauthorisation and concurrent consents.  This is why this option was not suggested.

Based on the above the recommendation contained in the proposal still appears to be preferred as it addresses the stated requirements for all stakeholders.

The need to accommodate implementation concerns for February is important (as stated in the proposal).  In the final decision the DSB will therefore attempt to allow implementation options for February that provides data holder implementation flexibility but still provides implementation certainty for data recipients.

**Comment by CDR-API-Stream** [comment]
A decision on this issue has been posted in the issue description above.

It is noted that the decision allows for maximum flexibility for data holders in their implementation choices for February.  It is also noted that there are indications that further consultation on the target state would be appropriate to accommodate additional feedback in the community so a new decision proposal issue will be raised to facilitate this.
